### ISSUE TITLE
Sorting in line list view

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1005]
Would be great to include sorting in line list view.

I downloaded CSV and used sorting function in excel, R which worked fine but is just taking a lot longer. UX may be better having such a simple functionality in the line list view.

**Comment by allysonjp715** [comment]
There is a bug in material-table around sorting with remote data. Hopefully it is fixed soon:
https://github.com/mbrn/material-table/issues/2322
https://github.com/mbrn/material-table/issues/2252

**Comment by attwad** [comment]
We'd also need to add indexes in mongo for ALL kind of sorting we'd want to do (all columns currently shown in the linelist) because we've had OOMs in the past due to missing indexes (could not go to the last page for example as the server had to hold the whole dataset in memory in order to sort).

**Comment by abhidg** [comment]
Seems like we don't have indexes, which is why #1765 happened. This was fixed in https://github.com/globaldothealth/list/commit/71145e387fdbb5f738f05fd66cdf243d12137118 but it's not proper sorting as it doesn't use the entire dataset, only the current view.

What's the best process to add indexes? I suppose it could be a one-time operation on dev and prod, but maybe also from CI? @iamleeg @jim-sheldon @maciekz1996

**Comment by iamleeg** [comment]
Indices are currently defined in the `cases.index.json` and similar files in the backend services, and updated by GitHub workflows.

**Comment by abhidg** [comment]
Correction: it appears that we do have indices, but sorting is still slow before https://github.com/globaldothealth/list/commit/71145e387fdbb5f738f05fd66cdf243d12137118

**Comment by abhidg** [comment]
@maciekz1996 @sergioloporto Sorting works in most cases :tada: but sorting for USA (14.8m cases) or over the entire dataset (29m cases) fails with 504. Sorting for countries with fewer cases works fine.

**Comment by iamleeg** [comment]
504 is gateway timeout so we may be able to reconfigure the ingress controller to wait longer, unless it's something upstream (like maybe mongodb atlas has a load balancer or ingress controller that's timing out waiting for mongodb, but that seems unlikely). That's only a short term fix until "make it faster", but "make it faster" sounds difficult.

**Comment by abhidg** [comment]
Remaining bit in #1875
