### ISSUE TITLE
After opening a line list entry in the Linelist view on the website on page 'X' after closing it user should stay on same page 'X' not on page 1 as it is now

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1006]
When I open a line list entry in the Linelist view on the website on let's say page 4 and close it again it defaults back to Page 1. This makes data validation a bit tricky.

1. Go to 'https://curator.ghdsi.org/cases'
2. Click on arrow to go to page 2 on line list view
<img width="1191" alt="Screenshot 2020-09-14 at 11 52 32" src="https://user-images.githubusercontent.com/8478551/93071734-ca63b400-f680-11ea-96fa-cd13269dc35d.png">

3. Open line list case.
4. Close line list case
5. You should be defaulted back to page one.

The same behaviour is true when using the filtered view.

It would be better to stay on that same page or same filtering view.

**Comment by allysonjp715** [comment]
Nearly had a fix for this by saving the page number in the location state, but there is a bug in material table for setting the initial page: https://github.com/mbrn/material-table/issues/964

We should be able to save the search query.

**Comment by dakrownie** [comment]
Material  table is owned by external parties. May need to reach out

**Comment by axmb** [comment]
There've been a handful of PRs sent to address the material-table issue -- the owner is usually pretty responsive, but PR authors seem to ghost after changes are requested. The number of actual (source) lines changed to fix this issue is ~20. We could probably just write/send a change for this ourselves.
