### ISSUE TITLE
Filtering of verification status in curator portal

### ISSUE THREAD

**Issue by beoutbreakprepared** [globaldothealth/list#1010]
We discussed the addition of filters to the curator portal GUI to facilitate processing  @allysonjp71 @axmb 

e.g. Allow for filtering on verification status so all verified entries can be dropped
e.g. Sorting by Confirmed date so all cases in same time period can be aggregated together more quickly 5

**Comment by axmb** [comment]
Believe we're waiting on a bug for sorting (CMIIW, @allysonjp715). For filtering, we'll get verification status added ASAP.

**Comment by allysonjp715** [comment]
Yep, sorting tracked here: https://github.com/globaldothealth/list/issues/1005
Filtering for dates tracked here: https://github.com/globaldothealth/list/issues/985

We can leave this bug open for filtering by verification status

**Comment by allysonjp715** [comment]
One question I have for filtering by verification status will be how users will know what to search for, since the status shows up as an icon in the UI. We could add info in the tooltip for now, but ideally we could come up with something else (https://github.com/globaldothealth/list/issues/936 ? )

**Comment by beoutbreakprepared** [comment]
The iconography is pretty clear from my perspective - could it be a toggle with three option: all, verified, unverified. Am naive as to how difficult that is to implement.

**Comment by allysonjp715** [comment]
I meant when searching for cases. So we'll add a filter option for 'verficationStatus:' (or similar) and they will need to know to type in the search bar the values 'verified' or 'pending'. But those values don't show up in the table since they are represented as an icon.

**Comment by allysonjp715** [comment]
@shroothless @sratcliffe118 any thoughts on my last comment?

**Comment by sratcliffe118** [comment]
IMO we could solve this with a hover over for the icon at the top of the table with the copy:

Verified (Icon): The data source upload has been verified
Unverified (Icon): The data source upload has yet to be verified

**Comment by sratcliffe118** [comment]
@shroothless WDYT?

**Comment by sratcliffe118** [comment]
![Screen Shot 2020-09-16 at 9 57 38 AM](https://user-images.githubusercontent.com/63205311/93315542-13dc0c80-f803-11ea-8766-c2e60fc18e2e.png)
Currently shows as coming soon, we could change this to Verification status

**Comment by allysonjp715** [comment]
Just to double check: I'm talking about searching (aka filtering) rather than sorting. I suppose if we made the hover state of the P icon "pending" and the hover state of the V icon "Verified", and "Verification status" in the header cell as you said. Then in the search bar the users may know what to search for i.e. "verificationStatus:verified" or "verificationStatus:pending". SG enough?

**Comment by sratcliffe118** [comment]
SGTM

Thanks,

Stephen



<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Stephen Ratcliffe*

*  • * Google Pay, Product Manager

*  •  *sratcliffe@google.com

  •  Google, Inc.



*If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.*
