### ISSUE TITLE
Notification of parser status and issues

### ISSUE THREAD

**Issue by beoutbreakprepared** [globaldothealth/list#1011]
We know that parsers will fail

Idea:
 - automated status reports on parsers stating success, catastrophic failures (e.g. url has changed), temporal failures (e.g. there is no new data in the parsed location) or other failures
 - either to ping a set mail-list of users or write to a slack channel

**Comment by beoutbreakprepared** [comment]
@axmb ?

**Comment by axmb** [comment]
Yep! We have an issue tracking this (at least an 80/20 implementation) in #978.

Those changes should be in dev today, and in prod by EOTomorrow.

**Comment by beoutbreakprepared** [comment]
Great - will close
