### ISSUE TITLE
Adjust structure of downloaded csv file

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1015]
Not all the demographic information available when viewing individual cases in the line list is shown when you download the line list. I have added a tab (CaseDemosVSLineListDownload) in the G.h Data Checking Issues google doc (https://docs.google.com/spreadsheets/d/1AZ-RHootmz5NOVyJ4c37fs6lNU3IN27xUZhNJemxWnE/edit#gid=0) where I have listed the demographic categories that are in individual case information and also listed the columns I see when I download the line list. I have noted what is missing or needs changing in the line list.

**Comment by allysonjp715** [comment]
Remaining requests are
- remove `[]` from the download when the value is an empty array 
- expand arrays of objects into individual fields in download (e.g. events)

**Comment by allysonjp715** [comment]
For the first request, `[]` does not show up in the download from the UI, it only shows up in the daily exports cc @attwad

**Comment by axmb** [comment]
Was this intentionally reassigned to me? Is there something particular I can help out with, @allysonjp715 ?

**Comment by allysonjp715** [comment]
I was leaving it open for anyone to pick up when they had the time. I described what's needed in my last two comments.

**Comment by axmb** [comment]
Got it. I'm not actively working this, but will pick it up if I work through other issues.

**Comment by sratcliffe118** [comment]
@axmb @z023 do we see this as blocking the friends and family launch? or can we bump this to be fixed prior to public launch?

**Comment by z023** [comment]
Could probably push it back on the priority list at the moment.

**Comment by WeronikaMichaluk** [comment]
HTD need to see an example during the call to better understand the task

What is expected and what do you receive. Examples when there is not an empty array.
turn it into a comma-separated string?
turn each existing symptom into a column?

Chris to check and update us on it.
