### ISSUE TITLE
Duplicate line list cases for Japan data set: 2 rows for a USA case

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1046]
Looks like there are 2 duplicate data rows for the Japan line list data source

Filter Line list by:
Country: United States

@Mougk Interesting point here is that the data source if Japan but these cases were identified as surfacing in USA. 
![Screen Shot 2020-09-16 at 9 58 19 AM](https://user-images.githubusercontent.com/63205311/93316487-2a369800-f804-11ea-987b-0c74e502dee4.png)

**Comment by attwad** [comment]
https://en.wikipedia.org/wiki/Japan,_Missouri

/facepalm

**Comment by attwad** [comment]
Those have the unique source IDs 10890 and 10891 (check their details), so they are not duplicates.

**Comment by sratcliffe118** [comment]
I did a quick google search and spotted that too :)

Oh ok will close if WAI (good call on the IDs, should have checked that)

**Comment by attwad** [comment]
That's still wrong to attribute to US, this was a Japan case.
Here's the raw case that we try to parse:

```
{
    "patientId": "10890",
    "dateAnnounced": "2020-07-09",
    "ageBracket": 20,
    "gender": "F",
    "residence": "Unspecified",
    "detectedCityTown": "Mid airport",
    "detectedPrefecture": "Port Quarantine",
    "notes": "Unspecified",
    "prefecturePatientNumber": "Port#347",
    "prefectureSourceURL": "https://www.mhlw.go.jp/stf/newpage_12340.html",
    "sourceURL": "https://www.mhlw.go.jp/stf/newpage_12340.html",
    "confirmedPatient": true
  },
```

"Mid airport" and "port quarantine" ended up being geocoded as that Missouri Japan county which is wrong.

**Comment by attwad** [comment]
Looking at the data set, these are the only two cases like that...  we could adapt the parser to ignore them.

**Comment by Mougk** [comment]
Either adapt or we can do manually and note that these ID's do not get updated with new auto ingestion. Also adding @z023 and @outbreakprepared

**Comment by z023** [comment]
@Mougk Is this the same issue as Indonesia appearing in the Japan dataset?

**Comment by sratcliffe118** [comment]
Also just checked again and it appears these cases are now duplicated in the line list with the same Source IDs

![Screen Shot 2020-09-16 at 3 21 40 PM](https://user-images.githubusercontent.com/63205311/93350550-aba41f80-f830-11ea-811c-fea207706a19.png)

**Comment by z023** [comment]
I re-uploaded Japan and Thailand and thought it would override the cases but it seems to have duplicated them??

**Comment by sratcliffe118** [comment]
@attwad thoughts on what is happening here and next steps to fix?

**Comment by attwad** [comment]
I might be wrong, but I think that Japan is a bit special in that the source URL changes every day (it has the current day built-in the URL), which makes our deduplication logic not happy somehow.

The two cases have the same sourceID and entryID but the URL changes between the twos so perhaps that matters...

https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/2020-09-15.json
https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/2020-09-16.json

What we could do is delete those two cases and see if the new schema change about upload ids that we pushed recently fixes the deduplication issue as well. Will do that now.

**Comment by attwad** [comment]
So after having deleted the cases they are back in the wrong location (united states, that's expected as they don't have a proper location set to them in the line list (just saying they got caught at the airport coming from the US).

The good part is that deduplication seems to work and those cases haven't been showing up more than twice as it was the case before (so my previous comment 8 days ago can be ignored).

I think we can close this and curators can ignore those two cases / add notes about them pending https://github.com/globaldothealth/list/issues/1013 to remove specific IDs from auto ingestion.
