### ISSUE TITLE
Download option for sources list

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1049]
It would useful to be able to download the sources list. As a curator, if I am having to delete and re-enter sources it would be helpful to download the list and then I can copy the source information from the list.

**Comment by allysonjp715** [comment]
Curious about the user flow here. Why do you need to delete and re-enter a source? Is the edit functionality not sufficient?

**Comment by z023** [comment]
I think if changes are made to the parser, just clicking trigger retrieval might not be initiating the changes??

**Comment by abhidg** [comment]
With the stable API keys work merged (#2142), curators will be able to fetch the sources endpoint to get a list of sources.
