### ISSUE TITLE
Add Individual cases tab, should be what is currently Cases: 3D with new color bands

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1055]
Notes:

See [slide 2](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g978baf5528_8_0) 

See color bands [here](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g978baf5528_0_46)

[Link to beta testing blockers sheet](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Assigned to tommyshimko@google.com

**Comment by lmanul** [comment]
I believe the change in navigation UI is covered by other bug reports. Closing. For further changes to color bands, it would be nice to have a spec as to what number of cases those should correspond. I've tweaked those myself given the data, but UX input would be better :-)
