### ISSUE TITLE
Add Cumulative cases tab, should be what is currently Aggregate, with colored country boundaries and not 3D

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1056]
Notes:

See [slide 2](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g978baf5528_8_0) 

See color bands [here](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g978baf5528_0_46)

[Link to beta testing blockers sheet](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Assigned to tommyshimko@google.com and Manu

**Comment by shroothless** [comment]
Cumulative cases should have the country list. See mock [here](https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab/G.h-Map?node-id=1088%3A431).

**Comment by lmanul** [comment]
@shroothless The Figma link requires a login (no idea what I should be logging in with). Could you post openly accessible?

**Comment by shroothless** [comment]
Can you login with your Google account. Employees have reader access. I
don't know how to convert it to openly accessible :(

**Comment by lmanul** [comment]
@shroothless Erm, I'm pretty sure there's all sorts of policies asking us not to enter our corp password into a non-google.com domain?

**Comment by lmanul** [comment]
We should probably also assume that someone who isn't @google.com (e.g. @rkassa ) may take this bug.

**Comment by shroothless** [comment]
You can sign in with Google, I believe, Stephen, Allyson, Tim all have been
able to access.

**Comment by sratcliffe118** [comment]
Screenshot attached

![Screen Shot 2020-09-17 at 1 14 41 PM](https://user-images.githubusercontent.com/63205311/93469025-cab1b880-f8e7-11ea-9330-9d5ab268f519.png)

**Comment by shroothless** [comment]
Robel has been accessing as well. If you don't have Figma you can follow
these steps here
<https://docs.google.com/presentation/d/1ZcWPkEQ_4o76r5SjUYhqu1tijgcbBgJuUgCLu-R2Aso/edit#slide=id.g5dacf448a6_23_88>

**Comment by lmanul** [comment]
Thank you @sratcliffe118 for the screenshot!
