### ISSUE TITLE
Add search/drop down with all countries. Picking a new country will focus the map on enter or click to change the focus of the card to data for that country

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1057]
[Link to beta testing blockers list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
duplicate with #1079
