### ISSUE TITLE
Adjust all typefaces to Inter

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1060]
Notes:
Will align to brand

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by lmanul** [comment]
I would argue font face is not P0? If everything is P0, nothing is ;-P

**Comment by sratcliffe118** [comment]
This is duplicate of #1102

Not a P0 either, agreed, 1102 is a P1
