### ISSUE TITLE
G.h Map: Remove the download link from the visualization

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1063]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by lmanul** [comment]
I have no idea what this means. "Remove download"? What is "download" and from where should it be removed?

**Comment by dakrownie** [comment]
Add mocks that Avani would provide here

**Comment by sratcliffe118** [comment]
Download link removed
http://covid-19.global.health/#casemap
