### ISSUE TITLE
Mock up and style country zoom

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1064]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Assigned to tommyshimko@google.com and Manu

**Comment by lmanul** [comment]
What is Tommy's Github handle? This probably shouldn't be assigned to me just yet.

**Comment by dakrownie** [comment]
I've asked Tommy if he is on Github, and would reassign once I get his handle.

**Comment by sratcliffe118** [comment]
@shroothless any update here, please add mock to the issue

**Comment by shroothless** [comment]
See hover state [here](https://www.figma.com/file/tfBStxWn2bORj0RyJD0zaB/User-Study-Sept-21?node-id=1%3A843)

![image](https://user-images.githubusercontent.com/67452108/93883675-e2a28700-fcaf-11ea-9c9f-f84ad1a44028.png)

**Comment by lmanul** [comment]
This looks the same ass issue #1070 ? The mock is the same.

**Comment by lmanul** [comment]
Duplicate of #1070
