### ISSUE TITLE
Mock up and style search drop down

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1065]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Assigned to tommyshimko@google.com and Manu

**Comment by lmanul** [comment]
What is Tommy's Github handle? This probably shouldn't be assigned to me just yet.

**Comment by sratcliffe118** [comment]
Duplicate #1079
