### ISSUE TITLE
Link to download the data dictionary form the list view

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1069]
Provide a unique link to download the line list data dictionary when in the line list tab view

@shroothless Please add in the UX for location and link and assign to @allysonjp715

**Comment by shroothless** [comment]
@acansler @sratcliffe118 I think this also should be at the account menu.

**Comment by sratcliffe118** [comment]
Sgtm, think we should have a link somewhere visible on the line list of
download area too

**Comment by shroothless** [comment]
I have it on the intro panel and in the account menu. I'm not sure how it
would fit hierarchically on the linelist page unless you want to pull it
out of the account menu and move it to the left hand nav. Is it that
important?

**Comment by sratcliffe118** [comment]
I don't think it is worthy of the left hand nav. What about around the download button? My concern is the account nav doesn't feel like the natural place a user would look for this, having it around the download seems a bit fit.

**Comment by shroothless** [comment]
We could add another button in that row but that’s even more prominent than
the left nav. The download button is in a single row and we should try to
keep it that way. Also once a researcher has understood the data doc. It’s
unlikely they will want it each time.

Let me  mock ups some options. Maybe it’s in an alert? That’s dismissible?

**Comment by sratcliffe118** [comment]
Sure an alert sounds good, with a note that details where the dictionary can be found post first time use

**Comment by allysonjp715** [comment]
Added it to the account menu. You can assign it back to me once we know where else we want the link to appear.

**Comment by sratcliffe118** [comment]
Mock for list view here: https://www.figma.com/file/TqqzDnXF4KTBAGUchpt4mQ/Global.Health-Marketing-Website?node-id=837%3A2571
