### ISSUE TITLE
Visual bug bash issues

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1071]
UI issues identified form the bug bash

**Comment by dakrownie** [comment]
@acansler Please add feedback from the beta testing that we'll need to work on.

**Comment by sratcliffe118** [comment]
https://docs.google.com/presentation/d/1z7dJvNBGhbg75Q5iZoTfdfwqzcNQIX8J2GxVSnjQcWY/edit#slide=id.p

**Comment by calremmel** [comment]
There's some valuable stuff left in these slides. To do: split this into smaller issues, prioritize and close.

**Comment by rkassa** [comment]
@joe-brilliant 

Can we close this? The last update on this was 01/04 and the "bugs" pointed out in these decks are already broken out into issues.

**Comment by joe-brilliant** [comment]
@rkassa yes we can close, thanks for tidying up!
