### ISSUE TITLE
Link from the curator portal to the G.h Visualization (aka G.h Map)

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1072]
Link from the curator portal to the G.h Visualization (aka G.h Map) [link](http://covid-19.global.health/#coverage)

@shroothless please add the UX mock and assign to @allysonjp715

**Comment by shroothless** [comment]
See mock [here](https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab/G.h-Map?node-id=1085%3A829)
![image](https://user-images.githubusercontent.com/67452108/93412152-98ae4100-f86a-11ea-8762-dedd01e5c095.png)
