### ISSUE TITLE
It is unclear if data is the same as available for download

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1075]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by lmanul** [comment]
This isn't very actionable -- what is the bug here exactly?

**Comment by sratcliffe118** [comment]
Agree, this is covered in the other raised issues around individual case view so closing.
