### ISSUE TITLE
The Line List/Portal link is broken

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1077]
https://curator.ghdsi.org/cases

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by lmanul** [comment]
I wouldn't know how to fix the portal :-) If you give me a different link, I'm glad to switch to that.

**Comment by sratcliffe118** [comment]
link works for me, not sure as to the issue here

**Comment by dakrownie** [comment]
@acansler Can we close this?
