### ISSUE TITLE
Add search/drop down with all countries. Picking a new country will focus the map and change the focus of the card to data for that country

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1079]
[See slide 3](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g978baf5528_0_38
)

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by shroothless** [comment]
Design is ready for eng.

**Comment by sratcliffe118** [comment]
Moving task to public launch milestone

Will use mocks for initial user testing: https://drive.google.com/file/d/1D0qgf8kWR8_BB5dAYEOuG0r-Syvs6Du1/view

**Comment by calremmel** [comment]
This seems done to me. Are we good to close this? @rkassa
