### ISSUE TITLE
The navigation is  different (linelist cases and aggregate cases views)

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1083]
WIP update here p5 ([link](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g987c4c1b8f_3_50
))

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
Duplicate
