### ISSUE TITLE
Rollover states 

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1085]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
@shroothless do we have more details here?

**Comment by shroothless** [comment]
For each filter we need to show a rollover state and active state. Tommy is
working on these.
