### ISSUE TITLE
Visual details 

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1086]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
We need more detail on this

**Comment by dakrownie** [comment]
@shroothless Any idea what visual details is referenced here?

**Comment by shroothless** [comment]
Making sure everything is pixel perfect and the right colors.
