### ISSUE TITLE
Add the date updated in the header instead of per filter

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1088]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
Not sure what this referencing, can we add more details?

**Comment by shroothless** [comment]
Add the date updated in the header instead of per filter. Like [this](https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab/G.h-Map?node-id=1089%3A116)
