### ISSUE TITLE
Global.health Terms of Use on Line List tab

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1092]
We need to add the Terms of Use to the LineList tab in the G.h List view.

Terms of use content can found [here](https://docs.google.com/document/d/1zj_4TNcqEzYxPk-NKdgPJRchhySNrlb5m56cp2bP2hA/edit)

@shroothless can you mock up where these could go on the page, we can either have them fully displayed or they could be access via a link: Terms of Use

**Comment by shroothless** [comment]
Let's add to the menu under account - Let's put it under About
![image](https://user-images.githubusercontent.com/67452108/93374402-a640d800-f824-11ea-997f-87e7b173d99d.png)

**Comment by sratcliffe118** [comment]
I do think we need it somewhere on line list view too even if it's terms of
use which links out to the copy.

Could we include on the first time user dialogue too

**Comment by shroothless** [comment]
+1 for first time use as well. Adding.

**Comment by shroothless** [comment]
See mock [here](https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab/G.h-Map?node-id=1085%3A829)
![image](https://user-images.githubusercontent.com/67452108/93409284-8df0ad80-f864-11ea-8376-0be6e67ed67d.png)

**Comment by allysonjp715** [comment]
The page and links have been added. Please reassign me once the Terms text is finalized and I will update.

**Comment by sratcliffe118** [comment]
@rkassa please confirm the production url we will be using for the website so we can close out the Terms of Use

**Comment by sratcliffe118** [comment]
Confirmed via slack

@allysonjp715 confirmed this finalized from my side.  Docs [here](https://docs.google.com/document/d/1zj_4TNcqEzYxPk-NKdgPJRchhySNrlb5m56cp2bP2hA/edit)
