### ISSUE TITLE
For the beta test, data viz can be a static image

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1093]
Moving all data viz action items to Data Viz tab

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Leslie: @shroo@google.com can you assign to the owner who will update the data viz to a static image for the Beta Test only?

**Comment by sratcliffe118** [comment]
closing as this is the uber bug for visuals and not needed
