### ISSUE TITLE
What data is actually available?

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1094]
Data for Beta Test with Researchers should be latest/greatest real world data

Currently at 10 sources ([https://curator.ghdsi.org/sources](https://curator.ghdsi.org/sources))

List of parsers available ([link](https://github.com/globaldothealth/list/blob/main/ingestion/functions/README.md#writing-a-parser-where-deduplication-of-patients-cannot-be-done))

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by dakrownie** [comment]
Currently at 10 sources
[](https://curator.ghdsi.org/sources)
List of parsers available: [](https://github.com/globaldothealth/list/blob/main/ingestion/functions/README.md#writing-a-parser-where-deduplication-of-patients-cannot-be-done)

**Comment by sratcliffe118** [comment]
List of parsers are here

https://github.com/globaldothealth/list/tree/main/ingestion/functions#parsers

**Comment by sratcliffe118** [comment]
Not sure what the issue is here?
