### ISSUE TITLE
20 different countries available in the line List data set

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1095]
Seems like this is working as intended for Beta. We have 10 available for configuration now, which is [the target we'd set](https://docs.google.com/document/d/1kYKNW56Ta7KaLSYD15Jqoz0wEshHwLNqil_cQp0JCr8/edit#heading=h.6s5o6poh8b3a) 

Plan is 20 within the next 12 days. The available parsers are [documented here](https://github.com/globaldothealth/list/tree/main/ingestion/functions#parsers), and the UI Sources table should document which of these are configured in the app.

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
As of today we are at 10

**Comment by sratcliffe118** [comment]
Bumping the milestone to public launch as the sources we have for F&F meet the case number requirements

**Comment by sratcliffe118** [comment]
We are now focused on supporting the number of cases and not the number of data sources themselves, as such I am going to close this issue

**Comment by axmb** [comment]
For posterity: we've reached ~31 sources (which cover about 15 distinct countries/states). I'll be working with Zoe to get these backfilled; the results of which are tracked in #1121.
