### ISSUE TITLE
Create a static image for G.h website

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1096]
Will use static images for beta test which will improve performance.  Will mark as done when we can do a preview with static image

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
Static file: https://drive.google.com/file/d/1D0qgf8kWR8_BB5dAYEOuG0r-Syvs6Du1/view
