### ISSUE TITLE
Pop-up for first-time users on Line List Platform/G.h Map

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1098]
[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

Need to add a first time use state, status: Design TBD

**Comment by dakrownie** [comment]
Assigned to tommyshimko@google.com and Shroo

**Comment by shroothless** [comment]
See mocks [here](https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab/G.h-Map?node-id=1085%3A1472)

We will need content from the marketing team. I've also added links to the terms of services and data dictionary

**Comment by allysonjp715** [comment]
I have this code ready, but I don't think it makes sense to add to the build until we have the proper content to go in the dialog. Who will create that content?

**Comment by sratcliffe118** [comment]
@dakrownie who from marketing can pick this up?

**Comment by dakrownie** [comment]
matilde@google.com is handling this.
There is an email thread with @sratcliffe118 and @shroothless in copy.

**Comment by allysonjp715** [comment]
I just filed #1133 and thought, what if this isn't a first time popup but instead the home page or about page? WDYT @shroothless ?

**Comment by shroothless** [comment]
I don’t think there’s enough content there to be a home page yet? We could
add this content to an about page as well though.

**Comment by allysonjp715** [comment]
Closing out in favor of the homepage as per https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab?node-id=1085:1472#41702084
