### ISSUE TITLE
G.h Website: Global Cases - headers/links don’t work

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1099]
Add articles in wordpress- Need admin access to wordpress (Marketing, Design)

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
@shroothless 
Can we define the expected behavior for the headers and links. What is the expected behavior and needs eng fixes?

**Comment by shroothless** [comment]
- Click **Get Involved** anchor link to About page at the **Get Involved** section
- Click **Map**  image or Map, go to G.h Map
- Click **List** , or List promo with cases (right module) go to G.h List
- Click **Projects** go to Projects page
- Click **About** go to About page
- Click a project/news/event item headline go to the detail page

**Comment by rkassa** [comment]
Header/main nav links are all updated per @shroothless's comment ☝️
