### ISSUE TITLE
G.h Website: Map at a Glance - no link

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1100]
Link to G.h Map: Cases - map image loads too slowly (will be slow for beta)

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
no delay in image loading, marking as done
