### ISSUE TITLE
G.h Website: Get involved link broken

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1101]
Get involved content - consolidated to 1 menu item. 
Need to reduce menu options:
Map, List, Project, About 

[Link to beta testing blocker list](https://docs.google.com/spreadsheets/d/1wM6se-GPNic3xxyggXPEsk0W6qMo6zl_RRcEwU6OcoU/edit#gid=1506108781)

**Comment by sratcliffe118** [comment]
What is the expected behavior when a user clicks on the get involved button? Is there a form that they will in, or does the link take them to a page with more information and details on how to get involved?

@shroothless

**Comment by shroothless** [comment]
Captured in another bug as well.

*Get Involved* should anchor link to the Get Involved form on the About page

**Comment by dakrownie** [comment]
@shroothless Do we close this then?

**Comment by shroothless** [comment]
Yes. Its handled in another bug

**Comment by avanianchala** [comment]
![Screen Shot 2020-09-17 at 2 47 49 PM](https://user-images.githubusercontent.com/71466164/93521905-4dda0b00-f8f6-11ea-977f-db427d84b643.png)
