### ISSUE TITLE
G.h Map: Color adjustment for all map views

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1103]
Color adjustment for all map views as per spec: https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g978baf5528_0_46

**Comment by sratcliffe118** [comment]
Let's keep open to check off when done

**Comment by lmanul** [comment]
So I _think_ all colors should be correct now. Can someone take a look and tell me if anything still needs changing?

http://covid-19.global.health/#casemap
http://covid-19.global.health/#cumulative

**Comment by lmanul** [comment]
Closing, please reopen with details on what needs changing if applicable. Thanks!
