### ISSUE TITLE
Line List data download user flow

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1110]
**Is your feature request related to a problem? Please describe.**
There is no visual indication as to the data download progress, time remaining or status. This plus the slow download rate makes it hard for the user to see what is going on and could result in multiple attempts to download thinking something is wrong, or give up and navigate away

**Describe the solution you'd like**
A UX treatment to show the progress of the download including the time or progress of the data download

UX treatment the user currently sees attached (the download button has a spinner and that is it)

![Screen Shot 2020-09-17 at 12 21 51 PM](https://user-images.githubusercontent.com/63205311/93463983-693a1b80-f8e0-11ea-9625-762cb8557564.png)

**Comment by sratcliffe118** [comment]
@shroothless is this on your radar? Think this is a key user journey we need to make sure we have covered

**Comment by shroothless** [comment]
I'm not following I think:  Step 1 Click download Step 2 .csv downloads in
browser

If we want to add some orientation hovers to call out what the download
button does we can add that?

**Comment by sratcliffe118** [comment]
I just went through this process for 137k cases and the button was spinning for 5mins before i gave up.

Either we need to speed the download process up, or have some UX to show that the download is happening and how long it will take otherwise users will just give up as it is too slow

**Comment by shroothless** [comment]
Got it, I can add UX treatment. Does it spin before the download starts?

**Comment by sratcliffe118** [comment]
No, it starts spinning as soon as it's clicked

**Comment by shroothless** [comment]
Got it, adding to my list.

**Comment by allysonjp715** [comment]
The data download progress is now shown on the browser's download object (e.g. the bottom bar in chrome).
