### ISSUE TITLE
G.h Website: Line List dataset and product explainer content on homepage

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1111]
Open question: Do we need to put information about the group  and the product more front and centre on the website?

User journey
- I land on the website and want to find out more about the product (line list) and the dataset
- Currently there is the map and blank space on right with cases
- Is there a clear CTA for the line list dataset and explanation of the product and dataset

**Comment by shroothless** [comment]
We can use the left hand area for that or alternatively, add more
introduction text on G.h. below the 3 modules. The intention was to use
those areas to promote relevant work so whatever we want to add to be more
G.H LIst focused sounds good.

**Comment by sratcliffe118** [comment]
I think we need more content around the products and data. The GISAID [homepage](https://www.gisaid.org/) has sections that detail and explains the data and products they offer. I think we need something similar

**Comment by shroothless** [comment]
@dakrownie Can you help here please? If we can get the content we want to show from the Marketing folks, we can quickly design for it.

**Comment by dakrownie** [comment]
@shroothless I sent miatort@google.com an email and copied you.

**Comment by sratcliffe118** [comment]
Duplicate bug closing

https://www.figma.com/file/tfBStxWn2bORj0RyJD0zaB/User-Study-Sept-21?node-id=1%3A1684
