### ISSUE TITLE
Website Map at a glance: No anchoring / referencing to Covid-19

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1112]
Need to anchor what the map is displaying (covid-19 cases) and the dataset that underlies it, as users could land here form new articles where there is limit context about the group

![Screen Shot 2020-09-17 at 12 34 05 PM](https://user-images.githubusercontent.com/63205311/93465089-309b4180-f8e2-11ea-8955-eb1c9cff664c.png)

**Comment by shroothless** [comment]
Will add COVID-19 label and global view. We are waiting on the 3D map color
adjustment to update the image however.

**Comment by rkassa** [comment]
<img width="426" alt="Screen Shot 2020-09-29 at 11 00 11 PM" src="https://user-images.githubusercontent.com/201428/94638233-8939e980-02a7-11eb-8e08-5e923b489776.png">

Resolved

**Comment by shroothless** [comment]
I believe we decided to move to the 2D map? Can we update.
