### ISSUE TITLE
Content and website sections to explain the G.h products

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1114]
Content and website sections to explain the G.h products
G.h List
G.h Map

Currently
List and Map navigation links just redirect users to the line list and the map view. Need some content to explain the products and what they are / the data behind them

**Comment by rkassa** [comment]
<img width="875" alt="Screen Shot 2020-09-30 at 2 58 49 PM" src="https://user-images.githubusercontent.com/201428/94727973-7e299c80-032d-11eb-9ea7-c68c6a11cea4.png">

Mini descriptions are added to the homepage. @sratcliffe118 I'll defer to you for closing this issue, in case the current state doesn't satisfy the issue you logged.

**Comment by rkassa** [comment]
Closing this as suggested changes are resolved.

Handling any further copy changes separately.
