### ISSUE TITLE
White screen after running a search on LineList

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1115]
**Describe the bug**
https://curator.ghdsi.org/cases showed a completely white screen after running a search query

**To Reproduce**
1. Go to the line list view
2. Searched - Occupation:Builder
3. White screen appeared

**Expected behavior**
Search results displayed

![Screen Shot 2020-09-17 at 12 55 13 PM](https://user-images.githubusercontent.com/63205311/93467014-0b5c0280-f8e5-11ea-9123-0c9856efe78b.png)

**Comment by allysonjp715** [comment]
@sratcliffe118, are you able to reproduce this? I just tried following your steps and could execute the search you mentioned and others in prod.

![Screen Shot 2020-09-18 at 5 43 13 PM](https://user-images.githubusercontent.com/30459667/93623304-6faabf00-f9d6-11ea-9c92-361afbcfcb37.png)

**Comment by dakrownie** [comment]
I tried the steps and got the same screen as Allyson. The error is no longer apparent and I will close this out.

**Comment by sratcliffe118** [comment]
Just had this issue again:

Steps to recreate:
1. Searched line list by gender: male
2. Searched line list by gender: female
3. White screen

I was logged in under sratcliffe@google.com and form a chrome browser

**Comment by sratcliffe118** [comment]
Note reloading the browser / refreshing it fixed the issue

**Comment by attwad** [comment]
I abused my keyboard doing logs of searches and got a white screen in dev yes:

![image](https://user-images.githubusercontent.com/1255432/93879393-eb10b700-fcdb-11ea-870d-b258e01537a6.png)


The query was just "aaaa" though.

The error I see in the console is 

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ys (react-dom.production.min.js:230)
    at ma (react-dom.production.min.js:163)
    at ButtonBase.js:288
    at os (react-dom.production.min.js:211)
    at gu (react-dom.production.min.js:257)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wo (react-dom.production.min.js:122)
    at mu (react-dom.production.min.js:257)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
```

That error is

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

so it seems we have some kind of race condition where an infinite loop creates infinitely nested children...

**Comment by attwad** [comment]
I will try to reproduce this in dev where we have the full stack trace/error.

**Comment by allysonjp715** [comment]
Perhaps we could try disabling the search bar input until the search HTTP response is returned.

**Comment by attwad** [comment]
Yup that's what I'm trying to do after failing to reproduce locally.
