### ISSUE TITLE
Change upload list ordering from latest date to oldest

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1116]
**Describe the bug**
Change upload list ordering from latest date to oldest

Currently set from oldest to newest so need to scroll through to end to check out the latest uploads for verification
![Screen Shot 2020-09-17 at 1 03 24 PM](https://user-images.githubusercontent.com/63205311/93468113-66422980-f8e6-11ea-89ba-1b6809ad9768.png)

**Comment by allysonjp715** [comment]
Leaving open to track adding indexes for the fields that are sorted on.
