### ISSUE TITLE
Upload 5f634e1d7c45bc3228102c1a showing as an error but cases added to line list

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1117]
Upload 5f634e1d7c45bc3228102c1a showing as an error but cases added to line list

1 case has been created despite the upload stating there was an error and showing 0 cases created
![Screen Shot 2020-09-17 at 1 05 43 PM](https://user-images.githubusercontent.com/63205311/93468402-d2249200-f8e6-11ea-9d75-1a1610e92d02.png)

![Screen Shot 2020-09-17 at 1 08 21 PM](https://user-images.githubusercontent.com/63205311/93468438-e1a3db00-f8e6-11ea-9bff-fbc10c3e0497.png)

**Comment by attwad** [comment]
So the way things are written currently, if an error occurs mid-way the upload doesn't get updated with the current created/updated counts, we should update it with those numbers.

**Comment by attwad** [comment]
Mid-upload fails are now reported correctly, we won't see uploads that ended up in ERROR with no associated cases if some cases were successfully uploaded.
