### ISSUE TITLE
Create GDPR compliance pop-up

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#1119]
**Is your feature request related to a problem? Please describe.**
We will soon store user preferences (https://github.com/globaldothealth/list/issues/1098) and use cookies for user login, I am unsure at which point we will need the GDPR compliance popup that most website have now where they have to accept cookies or tune their settings somehow.

This issue is to investigate if we're subject to GDPR to start with and how we should comply with it if we need to.

**Comment by sratcliffe118** [comment]
Synced with Emily from BCH and they use https://www.iubenda.com/en/ for GDPR compliance across their product set and wish to use the same approach here. Are we able to support this?

**Comment by emcohn** [comment]
Let me know if I can be helpful setting this up. Mark from our team has set it up for other platforms in the past.

**Comment by attwad** [comment]
Thanks, I'm happy to put those on the website once we have them generated but to start the process one needs an account it seems and I'd prefer someone who already did it to do it, @emcohn can you assign the right person to this please?

**Comment by WeronikaMichaluk** [comment]
BCH has to set up an account on https://www.iubenda.com/en/  and generate code; 
HTD will check the source code of that integration; 	

GDPR compliance (cookie?);  BCH to provide all information
Someone from the organization has to create an account and generate a proper code to set this up.

**Comment by MarkOglia-IDHA** [comment]
**PRIVACY POLICY LINK - Place this code in the <body>, where you want the link to appear:**

<a href="https://www.iubenda.com/privacy-policy/89575059" class="iubenda-white iubenda-embed" title="Privacy Policy ">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>

**COOKIE POLICY LINK - Place this code in the <body>, where you want the link to appear:**

<a href="https://www.iubenda.com/privacy-policy/89575059/cookie-policy" class="iubenda-white iubenda-embed" title="Cookie Policy ">Cookie Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>

**TERMS AND CONDITIONS LINK - Place this code in the <body>, where you want the link to appear:**

<a href="https://www.iubenda.com/terms-and-conditions/89575059" class="iubenda-white iubenda-embed" title="Terms and Conditions ">Terms and Conditions</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>

**COOKIE BANNER EMBED CODE:**

Here is the embed code for the Cookie Banner (at bottom of this comment) and instructions:

Add to the HEAD

Embedding and setting up is simple. Simply copy the code snippet by clicking on the "COPY" button and paste it within the HEAD tags across all your website pages.
Alternatively, you can use one of our plugins where available. Currently we have plugins available for WordPress, Joomla!, Prestashop and Magento. You can click the “Use a Plugin” tab above for more info and links.

Implementing prior blocking and asynchronous re-activation
Our prior blocking option prevents the installation of non-exempt cookies before user consent is obtained (as required by EU law) and asynchronously activates (without reloading the page) the scripts after the user consents.
To use, you must first enable this feature: simply select the “Prior blocking and asynchronous re-activation” checkbox above before copy and pasting the code snippet into the HEAD as mentioned in the preceding paragraph.
Next you must tag the scripts you'd like to block using one of the methods described in this guide.
Note: using one of our plugins partially automates this process. For more information, please see the “Use a Plugin” tab above.




<script type="text/javascript">
var _iub = _iub || [];
_iub.csConfiguration = {"whitelabel":false,"lang":"en","siteId":2070778,"cookiePolicyId":89575059, "banner":{ "rejectButtonColor":"#4394e2","rejectButtonCaptionColor":"white","position":"float-top-center","textColor":"white","backgroundColor":"#000001","acceptButtonDisplay":true,"acceptButtonColor":"#4394e2","acceptButtonCaptionColor":"white","customizeButtonDisplay":true,"customizeButtonColor":"#212121","customizeButtonCaptionColor":"white" }};
</script>
<script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>

**Comment by MarkOglia-IDHA** [comment]
I have updated the instructions text file by removing the Terms and Conditions requirements while I check with the third-party solution on the issue we've seen. Please implement just the cookie banner, privacy policy link, and cookie policy link per the updated instructions. Thank you!
Mark
[gdpr-instructions-20201124.txt](https://github.com/globaldothealth/list/files/5591659/gdpr-instructions-20201124.txt)

**Comment by joe-brilliant** [comment]
Hi @calremmel @rkassa I didn't see any cookie / GDPR compliance notifications on the beta URLs. Can we double-check this is implemented and behaving as expected, and reopen if need be? Thanks!

**Comment by joe-brilliant** [comment]
Flagging for @WeronikaMichaluk in case we want to have HTD take a look at this and take this on
