### ISSUE TITLE
Upload tab: Long Source URLs push the cases number off the screen

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1120]
@shroothless what would you suggest here for UX treatment, can we elipse the urls at 20 characters?

![Screen Shot 2020-09-17 at 3 43 28 PM](https://user-images.githubusercontent.com/63205311/93486901-9bf20d00-f8fc-11ea-9207-cf80fb36c60b.png)

**Comment by shroothless** [comment]
Sgtm
