### ISSUE TITLE
1M line list cases in the dataset

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1121]

**Comment by axmb** [comment]
Next step is establishing a figure for the number of line list cases _available_ globally. I'll carve up a draft looking at that by-country, then take a swing at categorizing percentages of cases as technically- blocked or feasible.

I loved a suggestion from the sync, which would be to create an ideally live KPI on the percentage of available cases included, but we can cross that bridge at a later step.

**Comment by axmb** [comment]
[Working doc](https://docs.google.com/spreadsheets/d/1zsqkmTL39HeF9mb8bfSQgC2yFuWA6strGnlr0pBCfQc/edit?ts=5f64b5e5#gid=0) in which we're collecting some numbers on this.

**Comment by sratcliffe118** [comment]
Data sources currently planned for ingestion [> 5M cases](https://docs.google.com/spreadsheets/d/1zsqkmTL39HeF9mb8bfSQgC2yFuWA6strGnlr0pBCfQc/edit?ts=5f6866aa#gid=0)

**Comment by sratcliffe118** [comment]
As of 24th Sept @ 240k cases

**Comment by axmb** [comment]
Today was our first real day post-prod-database reset.

After several wonderful hours backfilling, Zoe and I completed a few countries worth of data, including Peru (810k cases worth)! We're now at around 1.2M cases in prod.

**Comment by sratcliffe118** [comment]
HUGE milestone, congrats everyone!!!
