### ISSUE TITLE
Document a strategy for ingesting super-large (~100k+) data via ADI

### ISSUE THREAD

**Issue by axmb** [globaldothealth/list#1124]
**Is your feature request related to a problem? Please describe.**
Countries that have all case data in a single file, and also have a large number of cases, can take a while to upload. With the current size of our prod server, the time it takes to upsert all of this data can exceed the time limit for our AWS Lambda parsing functions (15 minutes). This makes regular automation unable to backfill this data.

This is an issue for Peru, for example, which has 600K+ cases in a single file. To give a converse example, it probably isn't an issue for India, which has more cases than Peru, but has separate files each with tens-of-thousands of cases.

**Describe the solution you'd like**
A way to get this type of data into the platform.

**Additional context**
The simplest solution, and a workaround that's technically usable now, is to use the source `dateFilter` to break the data up (for instance, running it on individual dates). Unfortunately, this is pretty laborious, since we can't select a time range with the current date filter set up.

This is mostly an issue for backfilling data. In a steady state, we probably just want to examine recent history (say, a couple weeks or months) for case updates. But, now that many countries have hundreds-of-thousands of documented cases, we need to get this historical data into the platform.

Since this backfilling should be a one-time event, the simplest solution might be to support date-range date filters, and to manually change that in the UI, then trigger retrieval, to get relevant chunks of data into the platform. Alternatively, parsers for large data could trigger an exo-Lambda function (in our server, or an AWS batch job) to do this.

**Comment by attwad** [comment]
I can think of a few things:

- parsers could store a hash of the file they retrieved and the last position they were at in the upload model, so that they can resume if needs be.
- date filters do not work for that problem currently as we can ingest stuff "up to a date" and "on a given date" but the "up to a date", we would require a from-to-date filter type which we do not have now to be able to ingest in chunks.
- parsers could be made to run locally as one-offs without any time-limit (should be very simple, we just need a main funtion that does more or less the same thing as what the lambda main does). That's not optimal in the sense that it requires manual intervention from a developer but if it's supposed to be a one-off until the date filters can be set on the source then it might be acceptable.

**Comment by attwad** [comment]
I played a bit with adding QPS info to the logs of the parsing functions so that we have an idea of how fast they can go, here's what I have locally I think it's pretty useful, I'll fix the tests and send it for proper review later today:

```
Raw file retrieved at /tmp/tmp0_0ahaur
Sending 250 cases, total so far: 0
	Current speed: 90 cases/sec
	Max estimate: 80710 in the remaining 894 sec
Sending 250 cases, total so far: 250
	Current speed: 100 cases/sec
	Max estimate: 89700 in the remaining 892 sec
Sending 250 cases, total so far: 500
	Current speed: 105 cases/sec
	Max estimate: 94200 in the remaining 890 sec
Sending 250 cases, total so far: 750
	Current speed: 108 cases/sec
	Max estimate: 96904 in the remaining 888 sec
Sending 250 cases, total so far: 1000
	Current speed: 108 cases/sec
	Max estimate: 96830 in the remaining 885 sec
Sending 250 cases, total so far: 1250
	Current speed: 110 cases/sec
	Max estimate: 98630 in the remaining 883 sec
Sending 250 cases, total so far: 1500
	Current speed: 112 cases/sec
	Max estimate: 100422 in the remaining 881 sec
Sending 250 cases, total so far: 1750
	Current speed: 114 cases/sec
	Max estimate: 102206 in the remaining 879 sec
Sending 250 cases, total so far: 2000
	Current speed: 116 cases/sec
	Max estimate: 103982 in the remaining 877 sec
Sending 250 cases, total so far: 2250
	Current speed: 117 cases/sec
	Max estimate: 104992 in the remaining 876 sec
Sending 250 cases, total so far: 2500
	Current speed: 118 cases/sec
	Max estimate: 105882 in the remaining 874 sec
Sending 250 cases, total so far: 2750
	Current speed: 118 cases/sec
	Max estimate: 105896 in the remaining 872 sec
Sending 250 cases, total so far: 3000
	Current speed: 118 cases/sec
	Max estimate: 105910 in the remaining 870 sec
Sending 196 cases, total so far: 3250
	Current speed: 119 cases/sec
	Max estimate: 106738 in the remaining 868 sec
sent 3446 cases in 28.87086510658264 seconds
Updating upload via http://localhost:3001/api/sources/5f646265cbdac60028b133b5/uploads/5f646778cbdac60028b133cb
END RequestId: 90cb5791-42e9-1375-c1bc-46b1914118af
REPORT RequestId: 90cb5791-42e9-1375-c1bc-46b1914118af	Init Duration: 789.12 ms	Duration: 30852.27 ms	Billed Duration: 30900 ms	Memory Size: 128 MB	Max Memory Used: 54 MB

{"count_created":3446,"count_updated":0}
```

**Comment by beoutbreakprepared** [comment]
We think Japan could also be seeing similar issues

**Comment by axmb** [comment]
Backfill feature is added, which should provide this capability.

I'll write up a bit of documentation so that process is clear/well trodden for the curation team, and close this afterwards.

(A related FR that we'll probably implement in the near term, for reference: #1191.)

**Comment by attwad** [comment]
FTR we're at about 100+ cases per second, looking at Peru's last ingestion run:

```
2020-09-24T01:33:08.661+02:00 | Current speed: 113 cases/sec
2020-09-24T01:33:08.661+02:00 | Max estimate: 100563 in the remaining 151 sec
2020-09-24T01:33:08.889+02:00 | Sending 250 cases, total so far: 83500
```

So for any source that's more than ~80K cases we should rely on this backfill feature first.

**Comment by axmb** [comment]
Updating here for posterity: backfill seems ready for primetime. We're planning to rely on it heavily for #1121, and the idea's to give it a full-scale test in dev before we drop existing prod data. I've tested it in dev, and it works as expected, but we can't give it a full-scale test until #1192 is approved/submitted.
