### ISSUE TITLE
Basic k8s cluster monitoring

### ISSUE THREAD

**Issue by axmb** [globaldothealth/list#1125]
**Is your feature request related to a problem? Please describe.**
With EKS, we don't really get any monitoring by default. We can use `kubectl` to get things like current resource usage and current logfile data, but we can't, for instance, look at when our servers stopped/started/CPU% over the past couple days.

**Describe the solution you'd like**
A way to view basic cluster metrics on a recent-historical (say, a week) basis.

**Additional context**
We'd discussed setting up Prometheus/Grafana in our cluster, which would do this. I'm not sure what the resource requirements for running those are, or if there are other material downsides.

**Comment by attwad** [comment]
I'd install the standard kubernetes dashboard first, we already have the metrics server installed to produce the cpu/mem metrics, the dashboard seems to give us a ncie graphical overview of what's going on:

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

I'll see if I can do that later today.

**Comment by axmb** [comment]
The FR here is complete, unless you'd like to expand this to cover alerting, @attwad ?

**Comment by attwad** [comment]
Well you only get 1H of data on the kubernetes dashboard (whatever the metrics server retains I think)

![image](https://user-images.githubusercontent.com/1255432/94031868-a2cac500-fdbf-11ea-9390-4846eb7b57be.png)

so it's not great... and doesn't provide any alerting either, I wouldn't close this FR just yet.

**Comment by axmb** [comment]
Cool, sounds good. I'll leave this open (with special attention @SpencerMarks-IDHA) at P2.
