### ISSUE TITLE
Colours out of synch in curator portal

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1127]
**Describe the bug**
Colours are not in synch between panels in Curator Portal

<img width="1196" alt="Screenshot 2020-09-17 at 21 18 17" src="https://user-images.githubusercontent.com/8478551/93517631-08d0cb80-f92c-11ea-8c21-3d0ea8b75dd1.png">

**Expected behavior**
Colors between bar plot and pie chart in synch.

**Comment by allysonjp715** [comment]
Fixed in mongo

![Screen Shot 2020-09-24 at 10 35 39 AM](https://user-images.githubusercontent.com/30459667/94128167-b3c41680-fe51-11ea-815c-14b89992ab09.png)
