### ISSUE TITLE
Add a landing page for logged out users

### ISSUE THREAD

**Issue by allysonjp715** [globaldothealth/list#1133]
Logged out users currently see the following in the Curator Portal, which I would think was broken as a first time user.

![image](https://user-images.githubusercontent.com/30459667/93582499-79163600-f99a-11ea-9c9f-f843e2665aa7.png)

Even a simple about page with instructions to log in would be good. @shroothless could you design and assign back to eng?

**Comment by sratcliffe118** [comment]
@shroothless ping

**Comment by shroothless** [comment]
See updated mock [here](https://www.figma.com/file/gIpIu2cyO3MWXQ86Npb0ab/G.h-Map?node-id=1157%3A4
)

![image](https://user-images.githubusercontent.com/67452108/93882796-b4707780-fcae-11ea-96fd-ee78f7299b78.png)
