### ISSUE TITLE
Copy title for website homepage mock

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1136]
Change the copy for the website title for g.h in the mock for the beta testing with researchers
![image](https://user-images.githubusercontent.com/63205311/93618645-76820380-f9cf-11ea-901b-0c74733ae882.png)

**New title:**  Our dataset contains detailed anonymized information on over **5 million Covid-19 cases** from around the globe.

Bold element make the light blue, rest of copy dark
Paragraph copy can remain as is

**Comment by sratcliffe118** [comment]
New copy
https://www.figma.com/file/tfBStxWn2bORj0RyJD0zaB/User-Study-Sept-21?node-id=0%3A1

**Comment by dakrownie** [comment]
Screenshot of the new copy from figma

![G h_Home_Add5M](https://user-images.githubusercontent.com/33044735/93780579-3d8c9d80-fc20-11ea-9788-a858374c2812.png)

**Comment by dakrownie** [comment]
Thanks @rkassa for getting to this so quickly.
