### ISSUE TITLE
Unclear error when bulk uploading csv without headers

### ISSUE THREAD

**Issue by allysonjp715** [globaldothealth/list#1144]
I accidentally tried to bulk upload a CSV without headers in the Curator Portal, and got the following error message:

![Screen Shot 2020-09-21 at 11 29 55 AM](https://user-images.githubusercontent.com/30459667/93757635-08bc1e80-fbff-11ea-9d1e-47bba965018f.png)

- `specified to be able to geocode:` looks like a cut off error message. Not sure if this would show up for actual geocode errors as well. 
- We should make an error message specifically about missing headers if they aren't there.

**Comment by attwad** [comment]
That's a good test to have in cypress... trying to reproduce there first.

**Comment by attwad** [comment]
I can reproduce this easily with this test data

```csv
def,Female,142,42,Canada,Alberta,,Banff,06/23/2020,true,,,,
def,Female,142,42,Canada,Alberta,,Banff,06/23/2020,true,,,,
```

the error returned seems good however:

```json
{"phase":"GEOCODE","numCreated":0,"numUpdated":0,"errors":[{"index":0,"message":"location.query must be specified to be able to geocode"}]}
```

so the error seems to be in the parsing logic in the UI.
