### ISSUE TITLE
Filtering by Country returning multiple country results

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1146]
**Describe the bug**
When filtering the line list by Country: Switzerland, cases with country = Japan are being returned in the results (see screenshot

**To Reproduce**
1. Go to line list
2. Search by country: Switzerland

**Expected behavior**
Only cases with country: Switzerland should be returned

**Screenshots**
![Screen Shot 2020-09-21 at 11 50 23 AM](https://user-images.githubusercontent.com/63205311/93758722-d90e1600-fc00-11ea-9304-d396706ea183.png)

**Comment by attwad** [comment]
Fixed by #1168
