### ISSUE TITLE
Searching / Filtering line list data: Data dictionary

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1148]
**Request**
Provide users with an easy way to access to the data dictionary from the filter / search functionality in line list

**Rationale**
Users will need to know the different values and entry options for the data dictionary to enable from to filter the line list down, providing them easy access to the dictionary will help them see the options they can filter by.

![Screen Shot 2020-09-21 at 12 03 31 PM](https://user-images.githubusercontent.com/63205311/93759649-7fa6e680-fc02-11ea-8e22-e1a1effea903.png)

**Comment by allysonjp715** [comment]
Will #1069 cover this use case?

**Comment by sratcliffe118** [comment]
Yes

Duplicate: #1069
