### ISSUE TITLE
Add location to Admin 1, 2 and 3 drop down options

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1153]
**Describe the bug**
Currently the filter drop down shows Admin 1,2 and 3. Add in location to make it clear to the user the fields are in reference to the location level of the case.
![Screen Shot 2020-09-21 at 12 32 08 PM](https://user-images.githubusercontent.com/63205311/93761955-9ea77780-fc06-11ea-91f0-4cc3a1e0b700.png)

**Comment by attwad** [comment]
Do you mean "location admin 1", "location admin 2" etc?

**Comment by sratcliffe118** [comment]
Yes correct, addition of location in front of each 'admin'
