### ISSUE TITLE
Add ability to ingest data sources stored in zip files

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1155]
The dataset for Mexico is stored as a zip file, as follows:
http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip

It would be great if it were possible for data ingestion to automatically handle data sources that are stored as zip files or other compressed file formats.

Alternatively, we could rehost data sources stored this way somehow, and link to an extracted version on our own servers, but that seems less than ideal.

**Comment by attwad** [comment]
The retrieval function could uncompress the data when it stores it, let me look at how we could do that.
