### ISSUE TITLE
Female results appear in male search

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#1156]
**Describe the bug**
https://curator.ghdsi.org/cases showed a completely white screen after running a search query

**To Reproduce**

1. Go to the line list view
2. Searched - gender: male
3. 2 results female results appear 
 

**Expected behavior**
Search male result displayed.

**Screenshots**
![Uploading bug.png…]()

**Environment (please complete the following information):**

**Comment by attwad** [comment]
It should be `gender:male` and not `gender: male` (note the space)
