### ISSUE TITLE
Sort sources list by name

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1176]
Sources are currently listed by oldest first and need to be most recent first.

**Comment by attwad** [comment]
@z023 please note that we don't store (nor show) the creation time of sources, we could add that but we could also sort by other existing means instead like source name for example, would that be better perhaps when looking for a specific source to be sorted alphabetically?

**Comment by z023** [comment]
By most recent would be easiest for editing sources.

**Comment by attwad** [comment]
Okay thanks, @allysonjp715 is adding some indexes to the curator service for uploads, we can pick that up after she finishes that task.

**Comment by allysonjp715** [comment]
Indexes have been added for existing needs now

**Comment by allysonjp715** [comment]
We could potentially use the $natural sort order to reverse the current ordering: https://docs.mongodb.com/manual/reference/method/cursor.sort/#return-in-natural-order

Not ideal to depend on but might be easier than starting to store a creation date this late in the game

**Comment by attwad** [comment]
From what I can see natural sort is based on the _id sort, here are the details of the items on the first sources page:

```
5f50eaa417e8e57eaf98dc21
5f5b5ae6def27b58cfb60471
5f5fd283d5b11ebf2fbae521
5f5fe00cd5b11e6064bae527
5f5ffa21d5b11e9edcbae582
...
```

So it isn't even true that sources are currently ordered by oldest first, it's just random...

**Comment by z023** [comment]
Sorting by source name might be better as quite a few countries will need multiple sources set up so it would keep them together.

**Comment by attwad** [comment]
Okay this we can do easily :) Will send a PR.

**Comment by attwad** [comment]
Needs to be pushed to prod before marking this as closed.
