### ISSUE TITLE
Website navigation is missing the get involved link

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1181]
Website navigation is missing the get involved link
![Screen Shot 2020-09-23 at 10 31 20 AM](https://user-images.githubusercontent.com/63205311/93994798-36809f00-fd88-11ea-9fb8-38372067787e.png)

**Comment by rkassa** [comment]
<img width="728" alt="Screen Shot 2020-09-29 at 11 02 47 PM" src="https://user-images.githubusercontent.com/201428/94638407-e6359f80-02a7-11eb-8b55-e0ba6ac19153.png">

The "Get Involved" link in the primary nav appears only when you scroll down and the sticky nav is enabled. This is by design.
