### ISSUE TITLE
Import Scotland data

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1184]
https://www.opendata.nhs.scot/dataset/covid-19-in-scotland/resource/a38a4c21-7c75-4ecd-a511-3f83e0e8f0c3?inner_span=True

API available too.

Age and sex stratified case data. Columns will need to be made long.

**Comment by attwad** [comment]
https://www.opendata.nhs.scot/dataset/covid-19-in-scotland/resource/9393bd66-5012-4f01-9bc5-e7a10accacf4?inner_span=True
Seems to have sex and age

**Comment by attwad** [comment]
Sorry can you explain what do you mean by "Columns will need to be made long"?

**Comment by Mougk** [comment]
There are numbers cases (per age and sex and day) so the cases will need to expand to match line list style (each case one line).

**Comment by attwad** [comment]
Ah ok yes of course, many parsers already do that 👍
