### ISSUE TITLE
Sources updates not all passing through

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1198]
When parser date filtering is set up for a source but this date filtering needs clearing, pressing clear and saving the changes instead sets the date filtering to 'parse all data up to 1 day ago'.

Pressing clear should leave the date filtering column blank.

**Comment by attwad** [comment]
Interesting, taking a look!

**Comment by attwad** [comment]
Must be something with how sources are updated in the backend because the UI sends the right info, but for example parsers cannot also not be cleared (modifications are ignored).

**Comment by attwad** [comment]
Okay this is now fixed in prod.

**Comment by z023** [comment]
I'm still getting the same problem @attwad ??

**Comment by attwad** [comment]
I checked in prod that I could clear the dates, did you save after clicking CLEAR ?
