### ISSUE TITLE
Finalized list of users for the Friends and Family launch

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1201]
Created a final list for users who will be given access to the global.health platform and website for the F&F launch

**Comment by sratcliffe118** [comment]
List of users proposed by Sam / Moritz

- Brandon Ogbunugafor, Yale, brandon.ogbunu@yale.edu
- Ana Bento, Indiana University, abento@iu.edu
- Dina Mistry, Institute for Disease Modeling, dina.c.mistry@gmail.com
- Michael Roytman, Kenna Security, michael@kennasecurity.com
- Dr. David Barros, IMSS, david.sierrac@imss.gob.mx
- Rafael Pereira, University of Sao Paolo, rafael.pereira@ipea.gov.br 
- Helen Johnson, ECDC, Helen.Johnson@ecdc.europa.eu
- Adam Kucharski, LSHTM, Adam.Kucharski@lshtm.ac.uk
- Sebastian Funk, LSHTM, sebastian.funk@lshtm.ac.uk
- Manuel Herranz, UNICEF, mgarciaherranz@unicef.org
- Isha Berry
- Ana Isabel Bento
- David Kennedy
- Ciro Cattuto 
- Daniela Paolotti
- Colin Carlson
-

**Comment by sratcliffe118** [comment]
@Mougk we need to make a call on how we want to communicate and give these users access to the tool

**Comment by Mougk** [comment]
Yes, I think it should be an email with a questionnaire attached for focussed feedback. @acansler can you help develop questionnaire (google form). Offer that we would love to talk as well in a week or two when they had time to play around with it. Mention that they should not share too widely ;)

**Comment by sratcliffe118** [comment]
List is finalized

**Comment by acansler** [comment]
Happy to help on this. Are there specific questions or topic areas you would like feedback on, @Mougk  ?

**Comment by Mougk** [comment]
See some posed here: https://docs.google.com/document/d/19DtkpwQy0K0TqSoi2y2qhCzi-grMbyCAcpx5d9SkG_8/edit?ts=5f746df5

**Comment by acansler** [comment]
Draft available here: https://docs.google.com/forms/d/1DD4mZX-BLuQROLXk2zl1zoGWtl3wM_OHPNHdsZud80o/edit?usp=sharing

**Comment by acansler** [comment]
I was mistaken about including the website and visualization in the survey. v2 available here: 

https://docs.google.com/forms/d/1lGrIn8A4U85lXIvem_7Suysel2RGKHA1fa09mYtzARM/edit?usp=sharing

**Comment by Mougk** [comment]
We should be all good. @sratcliffe118 please review and close.

**Comment by sratcliffe118** [comment]
lgtm
