### ISSUE TITLE
Design/format for Tool tip within form 

### ISSUE THREAD

**Issue by avanianchala** [globaldothealth/list#1214]
![Screen Shot 2020-09-24 at 4 45 22 PM](https://user-images.githubusercontent.com/71466164/94203647-66619c80-fe85-11ea-9600-7cd31ec9135e.png)

The box is 0E7569 at 100%
Text header is Mabry at 22pt
Body text is Mabry at 16pt

**Comment by calremmel** [comment]
@rkassa What do you think - possible candidate for HTD?

**Comment by zbigiman-htd** [comment]
@calremmel @rkassa @joe-brilliant 
I've styled the tooltip in the `verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx` file.
Is it enough to have the same looking tooltip in the whole app?
I'm not sure how to check all appearances of the tooltip in the app.

on `/cases/new` page it will look like this:
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/69294239/104325530-0270eb80-54e9-11eb-93bf-c02ddd8955d2.png">
