### ISSUE TITLE
Geocoder bug

### ISSUE THREAD

**Issue by allysonjp715** [globaldothealth/list#1227]
The geocoder takes a request with location field set to:
``` 
{
  country: 'United States',
  administrativeAreaLevel1: 'Ohio',
  administrativeAreaLevel2: 'Adams',
  query: 'Adams, Ohio, United States',
  limitToResolution: 'Admin2,Admin1,Country'
 }
```

and turns it into 
```
{
   query: 'Adams, Ohio, United States',
   geometry: { longitude: -82.7114488167578, latitude: 40.4174201146 },
   country: 'United States',
   place: '',
   name: 'Ohio, United States',
   geoResolution: 'Admin1',
   administrativeAreaLevel1: undefined,
   administrativeAreaLevel2: undefined,
   administrativeAreaLevel3: undefined
}
```

In #1226 I am removing the undefined's as they cause schema errors. But we appear to lose the admin levels after geocoding. This was found when running locally.

**Comment by attwad** [comment]
FYI admin levels are not available locally unless you import them into your local mongo DB as described here: https://github.com/globaldothealth/list/blob/main/data-serving/data-service/src/geocoding/README.md#fetch-of-administrative-areas

Confirmed I get the admins properly on my local instance, closing this as WAI.
