### ISSUE TITLE
Geocode travel history as well

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#1231]
**Is your feature request related to a problem? Please describe.**
trel history locations are not geocoded right now, one cannot set the location.query in them and have it geocoded.

**Describe the solution you'd like**
We should just geocode them as well.

**Comment by Mougk** [comment]
100% agree. I thought this was already implemented. 

Is this for launch or can we get this done for friends and family launch?

**Comment by attwad** [comment]
I'm doing this now 👍
