### ISSUE TITLE
Data missing from metric dashboards

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1242]
**Describe the bug**
Data missing from the metrics dashboards

![Screen Shot 2020-09-28 at 4 28 33 PM](https://user-images.githubusercontent.com/63205311/94452717-bef7a900-01a7-11eb-964b-e3790986c0ea.png)

**Comment by allysonjp715** [comment]
I'm hoping #1243 will fix this. We will have to drop the dataset and reimport, but we're planning to do that anyways.

**Comment by allysonjp715** [comment]
The charts are back up
