### ISSUE TITLE
Update ToS on portal

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1246]
ToS will need to be updated on portal to include text below:

Global.Health Terms of Use
1. The Global.health website and its contents herein, including all data and mapping are the copyright of Boston Children's Hospital, all rights reserved. When linking to the website, attribute the Website as www.global.health
2. The Global.health data is licensed under Creative Commons Attribution 4.0 International by the Boston Children's Hospital. Attribute any use of the data to: Global.health consortium, Detailed Epidemiological Data from the COVID-19 Outbreak, Accessed on yyyy-mm-dd from global.health and: Xu, B., Gutierrez, B., Mekaru, S. et al. Epidemiological data from the COVID-19 outbreak, real-time case information. Sci Data 7, 106 (2020). https://doi.org/10.1038/s41597-020-0448-0

**Comment by Mougk** [comment]
@rkassa @shroothless @allysonjp715 can you prioritise this one

**Comment by rkassa** [comment]
@Mougk 

ToS page on marketing website is here, so it can be linked to from portal: https://dev-globalhealth.pantheonsite.io/terms-of-use/

**Comment by Mougk** [comment]
@allysonjp715 has this been changed on curator portal? For me its still as below (https://curator.ghdsi.org/terms) and same in dev:
<img width="1006" alt="Screenshot 2020-10-01 at 10 20 31" src="https://user-images.githubusercontent.com/8478551/94791585-c6010000-03cf-11eb-9f52-882d6e49860e.png">

**Comment by allysonjp715** [comment]
We hadn't pushed, it is updated now.
