### ISSUE TITLE
logos misaligned

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1248]
Logos are misaligned when making browser window smaller. 

<img width="670" alt="Screenshot 2020-09-29 at 07 47 42" src="https://user-images.githubusercontent.com/8478551/94522812-26553d80-0228-11eb-8f26-894e1d08781e.png">

**Comment by sratcliffe118** [comment]
@Mougk what browser did you see this on?

**Comment by Mougk** [comment]
Does not appear to be an issue anymore. Thanks @rkassa
