### ISSUE TITLE
add and remove logos

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1249]
On curator login screen:

1. IHME logo should be replaced with University of Washington logo. 

![university-of-washington-uw-vector-logo](https://user-images.githubusercontent.com/8478551/94522954-60264400-0228-11eb-83fa-966fe08fe90c.png)

2. Add Oxford Martin School Logo: 

![oms-sq-rgb](https://user-images.githubusercontent.com/8478551/94523044-8350f380-0228-11eb-8124-35db07ebe964.jpg)

**Comment by allysonjp715** [comment]
Right now the logos are all in one image. Could someone make a new singular image or provide separate images for all the logos?

**Comment by Mougk** [comment]
Find remaining logos below.

![3u-georgetown-university-logo-600x200-1](https://user-images.githubusercontent.com/8478551/94661503-0ba1c800-02ff-11eb-8838-36613e6dfb5a.png)

![1c0c59bb823eb6a54723c54ad3e2408a](https://user-images.githubusercontent.com/8478551/94661511-0e042200-02ff-11eb-9651-968c2a3c8d58.jpg)

![northeastern-university-logo](https://user-images.githubusercontent.com/8478551/94661517-10ff1280-02ff-11eb-938c-af612ec57bc8.gif)

![university-of-oxford-logo-oxford-university-innovation-brand-png-favpng-FQMVJVtAGqZSxr6E4bvgJRnX7](https://user-images.githubusercontent.com/8478551/94661527-14929980-02ff-11eb-8fef-48d3fa1d97d7.jpg)

![AS_267479933227008@1440783593468_l](https://user-images.githubusercontent.com/8478551/94661536-178d8a00-02ff-11eb-99b5-e131d00a4590.png)

**Comment by allysonjp715** [comment]
Thank you! Do you have the Boston children's hospital logo with the words next to it? These all look quite wide... I wonder if they'll fit on the welcome screen. Will leave this with Robel and Katelynn.

**Comment by Mougk** [comment]
![childrens-logo](https://user-images.githubusercontent.com/8478551/94662690-a51da980-0300-11eb-87bb-4a4996959b4a.jpg)

Can always do two rows and in general make logos smaller. See an example below:

<img width="544" alt="Screenshot 2020-09-30 at 09 39 10" src="https://user-images.githubusercontent.com/8478551/94662846-dc8c5600-0300-11eb-8683-f434418ada85.png">

**Comment by rkassa** [comment]
@JaredHawkins @joe-brilliant 

Logos are all added, in two rows, on the marketing website: https://dev-globalhealth.pantheonsite.io/

**Comment by joe-brilliant** [comment]
Looks like logos appear on this login page as well that may need updating (i.e. IHME / UW) https://curator.ghdsi.org/

**Comment by joe-brilliant** [comment]
@rkassa some logos on home page look lower res than others. Would you mind taking a look? I can ask our partners for official hig res logos. Thanks!

**Comment by sergioloporto** [comment]
@joe-brilliant  I confirm that logos are low quality.
I see that the IHME logo has been already replaced with the Washington University logo.

Can someone please confirm what is left to be done.

From my understanding:

1. Wait to receive the high quality logos
2. Add Oxford Martin School Logo

Question 0)
Logos have to bee updated in these places:

- https://curator.ghdsi.org/
- https://dev-globalhealth.pantheonsite.io/about/

Anywhere else?

Question 1)
Please confirm the above

Question 2)
The logos provided by @Mougk are much wider than the actual ones which contain only the symbol. Do we want to have such new logo format (symbol + text next to it or below it)?

Question 3)
Should the new logos in the curator login page be in grayscale as it is now, or color?

Question 4)

> @JaredHawkins @joe-brilliant
> 
> Logos are all added, in two rows, on the marketing website: https://dev-globalhealth.pantheonsite.io/

@rkassa said that in this page, there are logos in two rows. But I see only 1 row. Did anything change in the meantime? If we have already all the logos in a double row structure, I can copy that image/s and use it in the curator login page

**Comment by joe-brilliant** [comment]
I'm in the process of requesting new hi res logos from all partners, will post them here in a new folder as I receive them!

**Comment by joe-brilliant** [comment]
@rkassa let's discuss on sync, may be best if you own all things logo for consistency
