### ISSUE TITLE
Add Privacy Policy to website

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1251]
If we use any tracking of data on website (google analytics or similar) we 100% need a privacy policy: https://seqlegal.com/free-legal-documents/privacy-policy.

**Comment by Mougk** [comment]
@attwad just in case: do you have a good resource for privacy policy?

**Comment by attwad** [comment]
You mean for generating a privacy policy? there are lots of online tools to do this yes (although I've never used them), but FTR the GDPR issue I filed earlier should cover this https://github.com/globaldothealth/list/issues/1119

**Comment by Mougk** [comment]
That's helpful. Good to see this is being tracked.

**Comment by sratcliffe118** [comment]
This item has been raised and is currently with BCH for a decision. Let's
loop in Emily to close this one out

**Comment by shroothless** [comment]
There is a Google Analytics account for the previous HealthMap site. Would be good to implement here, and not sure if we get anything from Wordpress. Robel can you help here?

**Comment by rkassa** [comment]
@joe-brilliant @scarpino 

ToS is done here: https://dev-globalhealth.pantheonsite.io/terms-of-use/

Need copy for PP, though.

**Comment by calremmel** [comment]
This is waiting on legal review. No action needed until further notice.
