### ISSUE TITLE
change of text on welcome screen

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1252]
Made made some adjustments to the text on: https://dev-globalhealth.pantheonsite.io/.

A first of its kind, easy to use global data repository and visualization platform that enables open access to real-time epidemiological anonymized line list data. **This platform was created by** university researchers from institutions around the world including Oxford, Harvard, Northeastern, **University of Washington** and John**s** Hopkins.

**Comment by rkassa** [comment]
Copy is updated accordingly on homepage

**Comment by sratcliffe118** [comment]
@rkassa I cannot see this change live on the website. do we need a push?

**Comment by rkassa** [comment]
![Screen Shot 2020-09-30 at 10 58 15 PM](https://user-images.githubusercontent.com/201428/94760412-6fb0a480-0370-11eb-9db7-32603bcfa725.png)

@sratcliffe118 might be a cache issue; verify in incognito?

**Comment by sratcliffe118** [comment]
LGTM, @rkassa thanks!!
