### ISSUE TITLE
privacy policy link on get involved page not working 

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1253]
1. Corrected some typos:

_Get **Involved**
Today, Global.health is being built via a network of hundreds of volunteers that could use your help in creating a revolutionary global source of information. Sounds exciting? Looking for ways to get involved?

Stay updated on what we’re doing **or** learn how you can get involved by filling out the form. If you’re already involved, feel free to refer someone that may be interested!

By completing this form, I agree to receive occasional emails per the terms of the Global.health’s **privacy policy.**_

2. Link to privacy policy not working.

General theme for discussion: How can we adapt text to sound more exciting for policy makers to get in contact?

**Comment by sratcliffe118** [comment]
@rkassa could you take a look at the content typos

@Mougk 
I would split out privacy policy and wording to a separate issue for the public launch

**Comment by rkassa** [comment]
@joe-brilliant @scarpino 

Thsi is resolved

Handing PP content in #1251
