### ISSUE TITLE
text edits in about section 

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1254]
Corrected some typos and edited text: 

_Our mission is to enable rapid sharing of trusted and open public health data to advance the response to infection diseases.

**We provide an** easy to use global data repository and visualization platform that enables open access to real-time epidemiological anonymized line list data. University researchers from academic institutions around the world like Oxford University, Harvard, Northeastern, **University of Washington** and Johns Hopkins are working together to build a trusted, detailed and accurate real time repository of infectious disease data in support of researchers, public health officials, and citizens to enhance preparedness and reduce the burden of infectious diseases._

**Comment by rkassa** [comment]
Copy is updated on "About" page accordingly

**Comment by Mougk** [comment]
Thanks. I've looked in the about section on this link which is still the same: https://dev-globalhealth.pantheonsite.io/about/

Am I looking in the wrong place?

**Comment by sratcliffe118** [comment]
@rkassa do we need to run a push to see these changes? I too cannot see from on the dev. instance of the site

**Comment by rkassa** [comment]
![Screen Shot 2020-09-30 at 10 56 21 PM](https://user-images.githubusercontent.com/201428/94760316-2c563600-0370-11eb-9006-2e2c454cf285.png)
@Mougk @sratcliffe118 — i've rebuilt the cache; please check again in incognito, perhaps? if not, let's take this to slack :)

**Comment by sratcliffe118** [comment]
LGTM, thanks @rkassa
