### ISSUE TITLE
A couple minor edits for website

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1256]
1. Remove section on resources and add Support (i.e., funding: which is Oxford Martin School and Google.org for now) on about subpage: https://dev-globalhealth.pantheonsite.io/about/ . They need to review before launch, so please do note.
2. Sponsor should be reframed to Partners. 
3. Team may only include one member per institution. I would prefer no pictures or names but institutions to have links to subpages of groups at different institutions. To be discussed? 
4. Logo from Oxford Martin School and University of Washington to be included in Partners section.

**Comment by rkassa** [comment]
This is resolved unless there are additional copy changes. Closing.

@joe-brilliant @scarpino
