### ISSUE TITLE
Projects subpage needs refining

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1257]
Projects subpage now showing some research that our **data has enabled**. 

Decisions to be made: 
1. Should we link to our own work (4 papers in Science, Nature Medicine, Nature Scientific Data, Lancet Infectious Diseases - see links below)
- https://science.sciencemag.org/content/368/6490/493
- https://www.nature.com/articles/s41597-020-0448-0
- https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30119-5/fulltext
- https://virological.org/t/epidemiological-data-from-the-ncov-2019-outbreak-early-descriptions-from-publicly-available-data/337

2. If links to other research, how do we make sure people see it as such? Can we still call it 'projects'?

**Comment by shroothless** [comment]
We could add these through the wordpress admin, I'm happy to hep. If not 'projects' is there another section name we can use for the section.

**Comment by Mougk** [comment]
agreed with 'Research' (@scarpino to confirm).

**Comment by rkassa** [comment]
@Mougk All 4 papers are added under "Research."

If the decision is to move forward with manually adding publications/articles in the short-term, I think we can go ahead and close this until we figure out an auto-update from a source/feed.

**Comment by Mougk** [comment]
Thanks. Please remove the other papers that were there before. They were "research pieces that this work has enabled" and will need a new category post launch.

**Comment by Mougk** [comment]
@rkassa added one more research paper coming out tomorrow: https://www.nature.com/articles/s41591-020-1104-0
