### ISSUE TITLE
Mismatch between URL and Subpage

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1258]
Mismatch between subpage 'projects' and URL ('news).

<img width="915" alt="Screenshot 2020-09-29 at 08 34 11" src="https://user-images.githubusercontent.com/8478551/94528336-248f7800-0230-11eb-9a23-1fc11e332eff.png">

**Comment by rkassa** [comment]
Resolved
<img width="1418" alt="Screen Shot 2020-09-29 at 7 37 09 PM" src="https://user-images.githubusercontent.com/201428/94627316-2c303a80-028b-11eb-8a72-0b1dcdbef298.png">
