### ISSUE TITLE
On curator portal add link to portal documentation

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1259]
I really like when websites or data portals put a link to the documentation of the platform. Perhaps this can be added to the section: "data dictionary', 'terms of use', 'documentation' with appropriate link to where we document the infrastructure for anyone to replicate and use.

@attwad @allysonjp715 what woudl be the best link to provide from our github?

**Comment by attwad** [comment]
Well, a lot of projects have a "fork me on github" kinda button somewhere, we could add something like that with our data dictionary/terms of use bottom links that points to https://github.com/globaldothealth/list#globalhealth-list, would that be reasonable?

**Comment by attwad** [comment]
Dev documentation is a bit below at https://github.com/globaldothealth/list#developer-documentation, we could also point to this instead if the link is explicitely about dev docs.

**Comment by Mougk** [comment]
Thanks Tim! 

Great, I will discuss with group on call later but for all these are two great options.

I tend to favour the 'fork me on github' buttom.

**Comment by shroothless** [comment]
Can we add these to the account menu along with some of the other links?

**Comment by attwad** [comment]
everything is possible ©

But do you mean to also move the dictionary and map link to the account menu?

**Comment by shroothless** [comment]
Lol. I'd leave Map and dictionary as is. And adding the Github fork the
menu. Sorry for being unclear.

**Comment by Mougk** [comment]
Works for me. @rkassa what do you think?
