### ISSUE TITLE
Local Dev Environment Documentation Updates

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1265]
There are a few points in the documentation of the local dev environment where I would find updates or further clarification very helpful for both new contributors and for me personally.

1. There are a couple of new secrets to include in the dev/.env file that it would be great to list with the others
2. For the dev/.env file, it would be great to list points of contact for getting secrets. I think this should probably be me, Spencer, and Gaurav for full coverage?
3. I find the process for adding and testing a new source a little difficult to follow, particularly given that it has changed a little from a couple of months ago. Perhaps we could clarify the steps to the point a total fool like me can follow them?

This could be a good opportunity to go through other documentation updates that might be helpful, so I've assigned anyone who might also regularly engage with the local dev documentation for writer parsers for their input as well.

**Comment by axmb** [comment]
I'll send a change for 1 and 2 now. I can take care of 3 tomorrow, unless someone is interested before I get to it.

**Comment by fojackson8** [comment]
This is a great idea. One thing I could add is that if you do have aws CLI set up, you can copy a source to aws and infer the details necessary for input_event.json without running the retrieval function, all you need is the sourceID from the UI. This helped me as retrieval function kept timing out and meant I could bypass this step.

**Comment by attwad** [comment]
Let me get a stab at 3. now

**Comment by attwad** [comment]
Okay hopefully https://github.com/globaldothealth/list/pull/1280 takes care of 3., let me know!
