### ISSUE TITLE
rotate screenshots on map

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1268]
Rotate screenshots so its clear that global dataset (or use a more global screenshot)

<img width="675" alt="Screenshot 2020-09-29 at 15 30 26" src="https://user-images.githubusercontent.com/8478551/94572296-c2069e00-0268-11eb-922a-6ca1df08237e.png">

**Comment by rkassa** [comment]
<img width="426" alt="Screen Shot 2020-09-29 at 11 00 11 PM" src="https://user-images.githubusercontent.com/201428/94638233-8939e980-02a7-11eb-8e08-5e923b489776.png">

Also resolved

**Comment by sratcliffe118** [comment]
@rkassa This update isn't showing for me, does it need a push?
