### ISSUE TITLE
Add more details in line list view

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1283]
Based on UX research more detail on line list cases was desired:

<img width="1057" alt="Screenshot 2020-09-30 at 11 49 11" src="https://user-images.githubusercontent.com/8478551/94676268-f898f300-0312-11eb-8998-5dd6728ecaf0.png">

Suggestion: add latitude and longitude, add detail on hospitalisation date, date of symptom onset.

**Comment by allysonjp715** [comment]
There was also a suggestion to give the user the ability to add/remove columns as they see fit. This will need UX guidance though.

**Comment by Mougk** [comment]
Great, @katelynnobrien may be able to help with UX post fellowship. For now, any comment from @acansler and @shroothless would be good!

**Comment by allysonjp715** [comment]
Comments from @acansler in #1290

**Comment by WeronikaMichaluk** [comment]
Information from Chris: 
We would like to add the following columns:

1. latitude location.geometry.latitude
2. longitude location.geometry.longitude
3. hospitalization date events
a. where name = hospitalAdmission
4. date of symptom onset events
a. where name = onsetSymptoms

The last two will not be present for every record. Some sort of N/A or blank may be displayed where those are not present.

**Placement of columns**
After **country** so it is grouped with other geographic info:

1.latitude location.geometry.latitude
2.longitude location.geometry.longitude

After **outcome**: (where are 2 empty columns)
They might be empty for some of the cases.
3. hospitalization date events
a. where name = hospitalAdmission
4. date of symptom onset events
a.where name = onsetSymptoms
