### ISSUE TITLE
G.h website: UX audit and fixes 

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#1294]
**Describe the bug**
UX audit and fixes to g.h website

Fixes: https://docs.google.com/presentation/d/1pO7VHHe6ZhdyhLBPacJjM5oRrhO8GXMUYfTb_mQCtv4/edit#slide=id.g9cbb561ab6_0_11

**Comment by rkassa** [comment]
Closing this as the changes from this deck on 09/29 were already implemented ✅
