### ISSUE TITLE
When searching by upload, sort cases by confirmation date (desc.)

### ISSUE THREAD

**Issue by axmb** [globaldothealth/list#1297]
**Is your feature request related to a problem? Please describe.**
Viewing the date range covered by an upload is a semi-common task. For instance, if I want to see what dates a given parser run was able to ingest -- either to understand what data was available, or if the parser run timed out, how far it got in the data. Right now, it's hard to do that.

**Describe the solution you'd like**
When searching by upload ID (or, optionally/by selection, any time) sort cases by confirmation date descending.

**Comment by abhidg** [comment]
So right now the UI allows searching by upload ID, but doesn't automatically set the sort option. The sort can be set after and works. As the functionality is there, albeit requires one more click, I'm reducing this to P2 and moving it to the next release.
