### ISSUE TITLE
To be able to see in the portal when auto-ingestions are currently in progress

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#1300]
**Is your feature request related to a problem? Please describe.**
It would be helpful to know when auto-ingestions are running as, particularly for the large datasets, it slows down backfilling and other upload attempts.

**Describe the solution you'd like**
A column in the sources list of auto-ingestions "IN_PROGRESS"

**Describe alternatives you've considered**
Or being able to set parsers to run at specified times of the day.

**Comment by attwad** [comment]
FYI The AWS schedule expression allows you to specify exactly at what time of the day you'd like a parser to run, right now most of them are `rate(1 day)` because that's simple but you can use the full `cron()` power if you'd like.

**Comment by z023** [comment]
Ah ok. When you use rate does it auto ingest at the time the source was set up?

**Comment by attwad** [comment]
No, my understanding is that AWS ensures it runs at the rate it was configured but if you set rate(1 day) it can be at any time during that day.

**Comment by abhidg** [comment]
This has been present for a while in prod.
