### ISSUE TITLE
Add country restrictions to geocode queries

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#1306]
**Is your feature request related to a problem? Please describe.**
Some geocoding queries unintuitively return results in a different country than the one expected.
For example "CABA, Argentina" returns a place in Mexico :-(

Example: https://curator.ghdsi.org/cases/view/5f75cb05cb263be4ff5a8892

**Describe the solution you'd like**
Mapbox supports country filtering in its requests so for parsers for which we know the cases are for a given country, we should be able to force the results to be in the given country in the form of cases output by parsers:

```
{
  ...
  location: {
    query: "CABA, Argentina",
    limitToCountry: "Argentina"
  }
}
```

** how to implement **
For people taking this one, what needs to be done is the same thing as what the `limitToResolution` does so looking at that it should be pretty straightforward. Basically setting NewCase in the curator service OpenAPI to be:

```
NewCase:
      description: >
        A "#/components/schemas/Case" with additional required fields for
        newly-created cases.
      allOf:
        - $ref: "#/components/schemas/Case"
      properties:
        caseReference:
          required:
            - sourceId
            - sourceUrl
        location:
          description: >
            Either `query` or all of `geometry`, `country`, and `geoResolution`
            is required. The former will trigger geocoding.
          properties:
            query:
              type: string
            limitToResolution:
              type: string
              description: >
                Comma-separated list of resolutions to restrict geocoding to.
                Allowed values are: Point, Admin3, Admin2, Admin1, Country.
            limitToCountry:
              type: string
              description: Country to restricts results to.
```

and then going on from there. I'm happy to be consulted/review PRs for this if needed.

**Comment by z023** [comment]
Another ~300 cases ingested this morning were geocoded as Mexico (upload ID 5f7fb615e78c681006f67b99).
Also still ~200k Argentina cases missing.

**Comment by fojackson8** [comment]
What were the locations of these cases as Mexico? Was it CABA/Buenos Aires again?

**Comment by z023** [comment]
There are 346 which I think are all in Buenos Aires and are being ingested with location name: Argentina, 77724 Playa del Carmen, Quintana Roo, Mexico.

**Comment by calremmel** [comment]
Possible candidate for HTD?

**Comment by WeronikaMichaluk** [comment]
@calremmel are you ok if we assign you to this one since its mainly backend work? We are happy to exchange this one for the frontend task. If ok with you

**Comment by fojackson8** [comment]
@calremmel are you working on this? Let me know if I can help
