### ISSUE TITLE
Harmonize all URLs across Map, List and Website

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1320]
Harmonise all URLs across Map, List and Website.

**Comment by gtuli** [comment]
Hi Moritz,
Can you please elaborate the issue a little bit? Thank you!

**Comment by JaredHawkins** [comment]
Just making sure that the main site (global.health), the curator portal, the map and the list all use global.health domain structure for launch.

**Comment by gtuli** [comment]
Thank you, Jared!
For that I would need to know how and where curator portal (https://curator.ghdsi.org/) is hosted. Can anyone here provide me the details where are we hosting the static website content for curation portal? Perhaps @rkassa??

We are using s3 buckets for covid-19.global.health and h1n1.global.health production. I don’t see a S3 bucket for curation tool under healthmap-collaborators AWS account. Are we using github pages here?

**Comment by gtuli** [comment]
Also, should we change https://curator.ghdsi.org to curator.global.health or covid-19-curator.global.health or anything else? One ore thing to notice here is global.health uses http and not https.

**Comment by Mougk** [comment]
Https ideally and why not global.health/list ?

**Comment by WeronikaMichaluk** [comment]
What service is used to manage domains? (AWS etc.?) → Christopher to check and confirm.

Will need access to these services.

What exactly do we want to do with that domain? Do we have 1 domain or multiple ones?

1 main domain and many subdomains. Chris to check and update us.

**Comment by calremmel** [comment]
@WeronikaMichaluk I believe I have the missing piece: ghdsi is an AWS EKS kubernetes cluster:

https://github.com/globaldothealth/list/tree/main/aws

I think you should have all of the necessary secrets to work with this, let me know if there are any missing pieces!
