### ISSUE TITLE
Sort out validation error in Japan parser

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1329]
I know we've already discussed this on slack but thought I'd open an issue for completeness sake after our meeting on Monday. As discussed let me know on here if the issue is on the parser side.

**Comment by calremmel** [comment]
Hi folks, in looking through this it looks like four cases are failing validation when they make it to MongoDB. It's not immediately obvious why!

For context, here's the link to the json schema, and here's one of the cases failing validation:

Schema: https://github.com/globaldothealth/list/blob/main/data-serving/data-service/schemas/cases.schema.json

Example Case:
```
{
    "revisionMetadata": {
        "revisionNumber": 0,
        "creationMetadata": {
            "curator": "ingestion@covid-19-map-277002.iam.gserviceaccount.com",
            "date": "2020-10-26T11:46:18.057Z"
        }
    },
    "demographics": {
        "nationalities": [],
        "ageRange": {
            "start": 80,
            "end": 89
        },
        "gender": "Male"
    },
    "events": [
        {
            "name": "confirmed",
            "dateRange": {
                "start": "2020-03-23T00:00:00.000Z",
                "end": "2020-03-23T00:00:00.000Z"
            }
        },
        {
            "name": "outcome",
            "dateRange": {
                "start": "2020-03-23T00:00:00.000Z",
                "end": "2020-03-23T00:00:00.000Z"
            },
            "value": "Death"
        }
    ],
    "location": {
        "query": "Okazaki, Aichi, Japan",
        "geometry": {
            "longitude": 137.16667,
            "latitude": 34.95
        },
        "country": "Japan",
        "place": "",
        "name": "Okazaki Shi, Aichi, Japan",
        "geoResolution": "Admin3",
        "administrativeAreaLevel1": "Aichi",
        "administrativeAreaLevel2": "Aichi",
        "administrativeAreaLevel3": "Okazaki-shi"
    },
    "caseReference": {
        "uploadIds": [
            "5f96b6b3b5daec96d75d2974"
        ],
        "verificationStatus": "UNVERIFIED",
        "sourceId": "5f61fa80361939e32e4c331d",
        "sourceEntryId": "1201",
        "sourceUrl": "https://data.covid19japan.com/patient_data/latest.json",
        "additionalSources": [
            {
                "sourceUrl": "https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"
            },
            {
                "sourceUrl": "https://www3.nhk.or.jp/news/html/20200323/k10012345631000.html"
            }
        ]
    }
}
```

I'll continue to look through this, but if anything jumps out at anyone as obviously something that would trip things up, please let me know!

**Comment by AnyaLindstromBattle** [comment]
The only thing that I can think of is that the additionalSources are both the same and this is confusing the validation somehow... Is this the same for the other three cases which are failing?

**Comment by iamleeg** [comment]
That is definitely a problem, the schema says that `additionalSources` has unique items. If you don't need to preserve the order of additional sources, a quick way to guarantee uniqueness is to turn the list into a set then back again:

```python
>>> list(set([1,1,2,3,1,2]))
[1, 2, 3]
```

**Comment by AnyaLindstromBattle** [comment]
Ok nice one, will tackle on Thursday when I'm doing G.h work if not already done
