### ISSUE TITLE
Backfill errors always reported as timeouts, never as errors

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#1332]
**Describe the bug**
I triggered a backfill for a small amount of data and looked in the aws logs. There was an error very quickly reported in the logs, but nothing on the UI for 20 minutes until the timeout message occurred.

**To Reproduce**
1. Navigate to curator.ghdsi.org
2. Use the + button to add a new source backfill
3. Set the URL and date range
4. Start the backfill

**Expected behavior**
If the backfill succeeds or fails with error then the UI should reflect this. The actual behaviour is that the UI shows that the backfill failed with timeout after 20 minutes. This timeout is computed in the UI, it isn't getting the actual status from the backend.

**Screenshots**
<img width="1376" alt="Screenshot 2020-10-22 at 15 12 23" src="https://user-images.githubusercontent.com/237254/96884122-13293c80-1479-11eb-984c-33fa7919a8ae.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 14

**Additional context**
N/A

**Comment by abhidg** [comment]
This might be fixed with the new curator UI <-> AWS Batch integration @jim-sheldon. As fewer sources have UUIDs, and we've decided not to backfilll non-UUID sources but reingest in full, moving this to P2.

**Comment by jim-sheldon** [comment]
It's not fixed, but captured in https://github.com/globaldothealth/list/issues/1909
