### ISSUE TITLE
Change Mexico and RGDS date filter ranges to 3 days

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1333]
The Mexico and RGDS parsers are both timing out, I believe simply due to size.

`2020-10-26T19:07:58.653Z 06989007-99e9-4afa-bb3d-ce6c801750ca Task timed out after 900.10 seconds`

Currently, the date filter for Mexico is set to 7 days, and the date filter for RGDS does not appear to be set.

Mexico:
`Filtering cases using date filter {'numDaysBeforeToday': 7, 'op': 'GT'}`
RGDS:
```Extracting fields from event {'env': 'prod', 's3Bucket': 'epid-sources-raw', 'sourceId': '5f723099ffcf9704e4b76036', 's3Key': '5f723099ffcf9704e4b76036/2020/10/26/1852/content.csv', 'sourceUrl': 'https://ti.saude.rs.gov.br/covid19/download', 'uploadId': '5f971afab5daec1f935d2999', 'dateFilter': {}, 'dateRange': None}```

Perhaps changing both to date ranges of 3 days would help?

**Comment by z023** [comment]
I have changed Mexico and RGDS to parse data after 3 days ago so I'll see if that works.

**Comment by calremmel** [comment]
This appears to have solved things! Thanks, Zoe.
