### ISSUE TITLE
Issue with Acre data source

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1338]
Acre parser is read to roll (with de-duplicated data) but now the source seems to be down with http://covid19.ac.gov.br/monitoramento/notificacoes/csv returning Internal Server Error. I have some datasets that I downloaded before the website stopped working, I don't know if it might be worth getting the parser up and running using this dataset first (i.e. just one ingestion event as opposed to having it be automated), just to get some more cases into the portal and get the de-duplication workflow working? @Mougk @z023 @iamleeg what do you think?

**Comment by z023** [comment]
If we get the backfill system sorted I could set this up as a backfill. Otherwise, I think we should continue getting the current sources working first before setting up more.

**Comment by AnyaLindstromBattle** [comment]
Link works again
