### ISSUE TITLE
Some Japan cases ingested as Indonesia

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1345]
Some cases (approx 750) in Japan data geocoded to Japan, 61361, Sooko, Mojokerto, East Java, Indonesia

From looking at the data it seems all of the cases which are geocoded as Indonesia are 'Port Quarantine' cases and so do not have any other location information other than 'Japan' e.g. 
  {
    "patientId": "11098",
    "dateAnnounced": "2020-07-12",
    "ageBracket": 20,
    "gender": "F",
    "residence": "Gifu",
    "detectedPrefecture": "Port Quarantine",
    "notes": "Returning from Pakistan",
    "prefecturePatientNumber": "Port#386",
    "prefectureSourceURL": "https://www.mhlw.go.jp/stf/newpage_12379.html",
    "sourceURL": "https://www3.nhk.or.jp/news/html/20200712/k10012511461000.html",
    "confirmedPatient": true
  }

So what I assume is happening is that in the absence of any other location information the geocoder looks up Japan and returns Japan, 61361, Sooko, Mojokerto, East Java, Indonesia. What I am not too sure about, however, is why it doesn't look up Japan as a country and return only 'Japan' but instead goes down the administrative levels? As I am not too familiar with how the geocoder works would be good to get confirmation from someone who knows - @calremmel @iamleeg @fojackson8 ?

In a separate but related question, do we still want to ingest these cases @Mougk ? How useful is it to have cases with only the country level geocoding? And is this even possible or will they fail validation? There is some location information in the "residence" field but whether this is prefecture or city information is inconsistent so not sure how useful it is.

**Comment by Mougk** [comment]
I think we want to keep even country level if demographic data is provided.

**Comment by AnyaLindstromBattle** [comment]
My understanding is that in the `detectedPrefecture == Port Quarantine` case the below function will return `,Port Quarantine, Japan`. However what I don't understand is why that is then converted to `Japan, 61361, Sooko, Mojokerto, East Java, Indonesia`. I guess this must have something to do with how the geocoding works, perhaps partly because it doesnt recognize Port Quarantine as a location - @calremmel @iamleeg any ideas?


```
def convert_location(raw_entry):
    query_terms = [
        term for term in [
            raw_entry.get("detectedCityTown", ""),
            raw_entry.get("detectedPrefecture", ""),
            "Japan"]
        if term and term != "Unspecified"]
    return {"query": ", ".join(query_terms)}
```

**Comment by iamleeg** [comment]
When I try the map box geocoding playground, a search for "Japan" yields the country first, and that district in East Java second. It's probable that adding "Port Quarantine" changes the way it fuzzy-matches, and swaps the order of the results. The easiest thing to try is to omit "Port Quarantine" if that's found in the input, and see if that corrects the returned result.

If it doesn't, then we can look at trying something else, like supporting the Mapbox API's filters.
