### ISSUE TITLE
Add new blog post to marketing website

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1361]
We have a new blog post which can be added to the media links.

https://blogs.lse.ac.uk/impactofsocialsciences/2020/11/17/the-need-for-open-data-sharing-in-the-era-of-global-pandemics/

**Comment by joe-brilliant** [comment]
@rkassa if we can add this to the new press carousel we can close this out cc @Mougk

**Comment by rkassa** [comment]
This is done, @joe-brilliant ✅

**Comment by joe-brilliant** [comment]
Thanks! I'll close this out
