### ISSUE TITLE
JSONDecodeError for Japan

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1365]
The error message reads [ERROR] JSONDecodeError: Unterminated string starting at: line 1453811 column 18 (char 48718748)

However if I go to the specific download which triggers the error, there is no unterminated string (line in question in bold).

  {
    "patientId": -1,
    "dateAnnounced": "2020-11-17",
    "ageBracket": 70,
    "gender": "M",
    "detectedPrefecture": "Tokyo",
    "patientStatus": "Deceased",
    **"sourceURL": "https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona1041.html",**
    "confirmedPatient": false,
    "deceasedDate": "2020-11-17"
  }

Might this be an issue with the size of the file, so reading the file somehow cuts off the file such that we don't have a valid JSON? see https://stackoverflow.com/questions/26541280/python-json-valueerror-unterminated-string-starting-at

**Comment by calremmel** [comment]
Hmm interesting, I'll give this a closer look tomorrow. Thanks, Anya!

**Comment by AnyaLindstromBattle** [comment]
Latest ingestion events seem to have worked! Could this have been a one-off thing?
