### ISSUE TITLE
Implement an endpoint for re-including the cases

### ISSUE THREAD

**Issue by WeronikaMichaluk** [globaldothealth/list#1373]
As a part of #1013, the following actions would be needed:

- Introduce a new endpoint to re-include the cases.
- The new endpoint should be implemented in both: curator-service (as a proxy) and data-service.
- The new endpoint should take a collection of cases to re-include:
  - DELETE: `/api/excludedCaseIds`
  - JSON: `{ "cases": [ "mongo uuiid" ] }`
- Change the status of the existing cases in the "cases" table to unverified/verified (TBD)

**Comment by WeronikaMichaluk** [comment]
https://github.com/globaldothealth/list/issues/1013

**Comment by calremmel** [comment]
As with its partner, makes sense to me! Please let me know if you need more mongodb access.
