### ISSUE TITLE
Exclude selected cases from the parsing process

### ISSUE THREAD

**Issue by WeronikaMichaluk** [globaldothealth/list#1374]
As a final part of #1013, the following actions would be needed:

- Find a proper place on the "parse_lib" library level to ignore the excluded cases
- Fetch the excluded cases from the data-service new endpoint
- Match and exclude cases from the parsing process.

TBD: add more details.

**Comment by WeronikaMichaluk** [comment]
https://github.com/globaldothealth/list/issues/1013

**Comment by rpoltorak** [comment]
@WeronikaMichaluk Changed the title and description, so we could work on #1013 simultaneously.
