### ISSUE TITLE
Implement an endpoint for excluding the cases (and changing other statuses)

### ISSUE THREAD

**Issue by WeronikaMichaluk** [globaldothealth/list#1375]
As a part of #1013, the following actions would be needed:

- Introduce a new endpoint to change status of multiple cases (including excluding them).
- The new endpoint should be implemented in both: curator-service (as a proxy) and data-service.
- The new endpoint should take a collection of case IDs to change status of, along with note (applicable only for exclusion):
  - POST: `/api/cases/batchStatusChange`
  - JSON: `{
  "caseIds": [ "mongodb uuid", ... ],
  "note": "string"
}`
- Store the new status in the `caseReference` subdocument of a case in `cases` table.
- Extend the existing case model by allowing a note, exclusionDate, and additional "excluded" status (along with unverified/verified).
- Extend current /cases endpoint with the exclusion details:
`{ "cases": [ ..., { "exclusionData": { "date": "standard format", "note": "string" }, ... } ] }`

**Comment by WeronikaMichaluk** [comment]
https://github.com/globaldothealth/list/issues/1013

**Comment by rpoltorak** [comment]
@WeronikaMichaluk Changed the issue description, so we could work on #1013 simultaneously.

**Comment by calremmel** [comment]
Makes sense, thanks! Please let me know if you need more direct mongodb access than you have currently.
