### ISSUE TITLE
Handle excluded cases in curator portal (UI)

### ISSUE THREAD

**Issue by WeronikaMichaluk** [globaldothealth/list#1376]
**Note:**
This is a front-end part of #1013.

**User stories:**
- As a user, I want to exclude a selected one or more cases from the list, so they can be ignored in the parsing process. 
- As a user, I want to re-include a selected one or more cases from the list, so they can be re-included again in the parsing process.
- As a user, I want to write a note about the excluded cases, so I can later check what was the reason for the exclusion.
- As a user, I want to have a separate status indicator for excluded cases on the list, so they can be easily recognizable.

**Actions needed:**
- For a standard case, introduce additional action to the existing context menu (three dots). That action should open the modal/dialog after the click event.
- The modal/dialog should contain input for the note and the confirmation button.
- After clicking on the confirmation button, send the information about the excluded case (or cases) to the curator-service endpoint
- For an excluded case, introduce additional action to the context menu. That action should send the information about the case that should be re-included again
- Introduce the same exclude and re-include actions for multiple cases. We could introduce that functionality by adding a new icon to the context menu on the top of the list displayed when multiple cases are selected. In that case, the same note would be applied to each of the selected cases.
- Introduce a new status and indicator state for the excluded cases (first column in the list). So there would be 3 statuses instead of 2: 
  - U: Unverified
  - V: Verified
  - E: Excluded. It could be red(ish) to increase readability.
- Excluded cases displayed on the list could be greyed out (opacity: 0.8?)

**Comment by WeronikaMichaluk** [comment]
https://github.com/globaldothealth/list/issues/1013

**Comment by rpoltorak** [comment]
@WeronikaMichaluk Changed the issue description, so we could work on #1013 simultaneously.

**Comment by calremmel** [comment]
I think this is very thorough, looks great!

For the TBDs:

> TBD: Introduce the same exclude and re-include actions for multiple cases. We could introduce that functionality by adding a new icon to the context menu on the top of the list displayed when multiple cases are selected. In that case, the same note would be applied to each of the selected cases.

I think this is a great idea. If it's not a ton of extra work, I can see this being very useful to curators.

> TBD: Excluded cases displayed on the list could be greyed out (opacity: 0.8?)

This also makes good sense to me. Thank you!
