### ISSUE TITLE
Create G.h homepage hero section to embed forthcoming explainer video

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1381]

**Comment by joe-brilliant** [comment]
https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAKrLjw0Y

**Comment by rkassa** [comment]
homepage is updated with placeholder video, @joe-brilliant
