### ISSUE TITLE
Create press section to house current and future articles

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1382]
A possible design approach discussed with @rkassa could be a rotating carousel starting with the NYT quote/link.

Gdoc copy deck discussion and links to all current press
https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAHVK46ZE

**Comment by rkassa** [comment]
carousel of press quotes and links (4) are now set up on the About page:
https://dev-globalhealth.pantheonsite.io/about/

**Comment by joe-brilliant** [comment]
Looking good @rkassa ! Maybe good to add quotation marks around the quotes and logos for each news source cc: @Mougk

**Comment by joe-brilliant** [comment]
I think we can close this issue out after we add quotation marks, thanks @rkassa !

**Comment by joe-brilliant** [comment]
One more to add for launch, from Google official Keyword blog (SEO jackpot : ) @rkassa cc: @Mougk https://blog.google/outreach-initiatives/google-org/google-supports-covid-19-ai-and-data-analytics-projects

**Comment by joe-brilliant** [comment]
@rkassa when you get a chance, can you add the article above to the press section? then we can close this ticket. Suggested quote:

"Understanding the spread of COVID-19 is critical to informing public health decisions and lessening its impact on communities. We’re supporting the development of data platforms to help model disease and projects that explore the use of diverse public datasets to more accurately predict the spread of the virus."

**Comment by joe-brilliant** [comment]
@rkassa can we add the google blog quote and push to prod? Then we can close this issue (until we get more press : ). Thanks!

**Comment by rkassa** [comment]
@joe-brilliant can you take a look at the dev site here: https://dev-globalhealth.pantheonsite.io/about/

if this is all good to go, ready to deploy to prod and close out quite a few of these tickets 👍

**Comment by joe-brilliant** [comment]
Looks great thanks @rkassa ! Lets push this and any other revisions on dev to production.

**Comment by joe-brilliant** [comment]
Looks great thanks @rkassa ! I'll close this out
