### ISSUE TITLE
Update Team page with modular and modifiable sections, including volunteers (section headers and members TBD)

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1383]
Link to Gdoc copydeck discussions:

https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAHVK46bU

https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAHVK46bc

**Comment by joe-brilliant** [comment]
WIP list of volunteers per @Mougk https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAK3E7Uiw

**Comment by rkassa** [comment]
Grid is setup, @joe-brilliant 

Quick request — original images of volunteer headshots, and not compressed/resized versions from the gdoc. It looks horrible when I use those 😬

**Comment by joe-brilliant** [comment]
This looks great thanks @rkassa, will close this issue and we can keep up to date on the copy deck and Pantheon moving forward.
