### ISSUE TITLE
Create persistent website footer with the following elements + links

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1384]
[Footer]

[G.h | a Data Science Initiative]

Terms of Use
Privacy Policy
FAQ
Contact Us
[Twitter logo]
[LinkedIn logo]
[[GitHub logo](https://github.com/globaldothealth)]

Copyright 2020, Global.health

**Comment by rkassa** [comment]
@joe-brilliant 

marketing website now has global footer.  let me know when content for the "privacy policy," "contact us" and "FAQs" sections are ready though. i think those can be in their respective issue tickets?

**Comment by joe-brilliant** [comment]
G.h | a Data Science Initiative

- [ ] Terms of Use

- [ ] Privacy Policy

- [ ] FAQ

- [ ] Contact us

- [ ] Twitter 

- [ ] GitHub

- [ ] LinkedIn

- [ ] 

Copyright 2020, Global.health

**Comment by joe-brilliant** [comment]
Added a punch list for footer elements to be added @rkassa. Will add links to as they become avail (FAQs are still WIP)

**Comment by joe-brilliant** [comment]
@rkassa @calremmel would it be possible/recommended to keep these footer elements persistent on Data and List? That would be ideal IMO

**Comment by joe-brilliant** [comment]
Just FAQ to do!
