### ISSUE TITLE
Rename "List" to "Data" throughout site navigation and URLs

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1386]
Per discussions/decisions via @Mougk et al, changing this naming convention to make it more intuitive and self-explanatory. Several areas of the site need may be updated:

- [x] Marketing website header navigation and in-page links: https://dev-globalhealth.pantheonsite.io/
- [x] Currently titled "/List" logged in user page and URLs https://curator.ghdsi.org/cases
- [x] Curator portal https://curator.ghdsi.org/# 
- [x] Map page cross-link http://covid-19.global.health/#cases (currently no cross-links from map->list/data)
-Others?

**Comment by zbigiman-htd** [comment]
@joe-brilliant Is it about changing the names of the following labels from "Linie list" to "Line data"?

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/69294239/105181527-31f8a700-5b2c-11eb-9152-204e3e6c468e.png">

I don't understand this part, could precise it?
```
Map page cross-link http://covid-19.global.health/#cases (currently no cross-links from map->list/data)
```

**Comment by joe-brilliant** [comment]
Thanks for flagging, @rkassa might have some thoughts on this. I think it should be "Line list" throughout, and probably is redundant here?
