### ISSUE TITLE
Website visual design fine tuning

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1390]
Running punch list of smaller website design elements not captured in other issues

- [x] Increase subheader text font size throughout (e.g. "Get Involved"; "Explore the data"; "Top Stories")
https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAKrLjwzA

- [x] Increase size of G.h logo and nav bar icon https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAKrLjw0k

- [x] Ensure case counts for /map and /data on homepage are accurate and include commas https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAKrLjwvE

- [x] Fix links to source articles on research article detail pages https://docs.google.com/document/d/1sZklXiZosHgvnsflz7ZlPNv0Tvx0kdeeD2UBlXtoQ7U/edit?disco=AAAAHVK46YU

- [x] Adjust homepage text wrapping so "5 million anonymised cases" stay on same line by default
https://www.dropbox.com/s/7hivwku9lhuszss/Screen%20Shot%202020-12-16%20at%205.14.26%20PM.png?dl=0

- [x] Align research page articles/images on homepage
https://www.dropbox.com/s/pl1ktzhllink086/Screen%20Shot%202020-12-16%20at%205.14.01%20PM.png?dl=0

- [x] Ensure consistency of text colors (black/gray)

**Comment by rkassa** [comment]
3/4 complete @joe-brilliant

**Comment by joe-brilliant** [comment]
Thanks @rkassa! FYI we have homepage case count discrepancy issue logged here @scarpino @Mougk

**Comment by joe-brilliant** [comment]
@rkassa just noticed that the "Get Involved" button only appears on homepage when scrolling below the fold. Can we make that persistent and consistent, as well as the logo size? I think the size that shows when scrolling below the fold looks great (feels a tad large on the default homepage above the fold view) thanks!

**Comment by joe-brilliant** [comment]
@rkassa looks like some article detail pages have greek text or placeholder in the URLs. e.g. and some formatting is inconsistent

https://global.health/2020/04/24/sed-et-purus-porta-euismod-ipsum-vel-pellentesque-risus/

https://global.health/2020/06/16/neque-porro-quisquam-est-qui-dolorem-ipsum-quia-dolor-sit-amet/

https://global.health/2020/02/11/hello-world/

**Comment by joe-brilliant** [comment]
@rkassa I added a few other fine-tuning items to check boxes above. Great to see the current case count on the home page! Is that a static quick fix or now a dynamic feed?

**Comment by joe-brilliant** [comment]
@rkassa I added the gray/black issue to the check box above. Would you mind checking in and update these once they are fixed on production and we can close this out? Thank you!

**Comment by joe-brilliant** [comment]
@rkassa everything looks great! I do think in light of our new direction to reference only line list data we should remove "Aggregated case data". Maybe we can have a live counter of # of countries or another meaningful stat? Or we just remove it for now if easier. A related question for @calremmel @Mougk @iamleeg: we currently say "over 5 million cases from over 150 countries" on the homepage and in the video Google is producing. Are these totals reflective of what we'll eventually have for launch?

**Comment by iamleeg** [comment]
Not quite sure. 5M cases seems achievable, we have 4.6M now and if we sort out the problems with backfill from North America then definitely. 150 countries seems…optimistic. We have sources from 18 different countries ingesting, and spreadsheet data with 123 distinct values in the "country" field (some of which I don't think are countries, like "Washington" and "Wakayama Prefecture", and presumably there's a lot of overlap there. We'd have to add another 25-ish country-level sources between now and launch, and I don't think that's likely.

**Comment by joe-brilliant** [comment]
Thanks @iamleeg very helpful. I think we should remove "Aggregated case data" since we are no longer going to be referencing it, and then periodically update the individual counter. Maybe we can increase the size or add a visual thumbnail like we have for Map on the hopepage. 

We do currently say over 5m cases and over 150 countries on both the homepage and in the video script and motion graphics, that latter of which is time-sensitive and about to be finalized. @Mougk any thoughts on this?

**Comment by joe-brilliant** [comment]
@rkassa let's remove the aggregated case count for now, I'll close this ticket and we can address and country count in #1397

**Comment by Mougk** [comment]
>5m is good to mention. How about +100 countries? That's similarly good than 150
