### ISSUE TITLE
Ensure case counts on website, /data and /list are accurate, consistent, and up to date

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1397]
Currently, there are at least three instances of dynamic "case counts". These totals should match and be formatted consistently with commas

Marketing website
![image](https://user-images.githubusercontent.com/74671973/101221244-1f89e300-363c-11eb-80b8-fb225fbb88a9.png)

/Data (formerly "/List")
![image](https://user-images.githubusercontent.com/74671973/101221311-4ba56400-363c-11eb-9114-51da5fc21324.png)

/Map 
![image](https://user-images.githubusercontent.com/74671973/101221412-7ee7f300-363c-11eb-8ede-28936bd4cb03.png)

**Comment by joe-brilliant** [comment]
@rkassa @iamleeg @Mougk moving the case and country count discussion thread here:

" I do think in light of our new direction to reference only line list data we should remove "Aggregated case data". Maybe we can have a live counter of # of countries or another meaningful stat? Or we just remove it for now if easier. A related question for @calremmel @Mougk @iamleeg: we currently say "over 5 million cases from over 150 countries" on the homepage and in the video Google is producing. Are these totals reflective of what we'll eventually have for launch?

@iamleeg
 
Member
iamleeg commented 8 hours ago
Not quite sure. 5M cases seems achievable, we have 4.6M now and if we sort out the problems with backfill from North America then definitely. 150 countries seems…optimistic. We have sources from 18 different countries ingesting, and spreadsheet data with 123 distinct values in the "country" field (some of which I don't think are countries, like "Washington" and "Wakayama Prefecture", and presumably there's a lot of overlap there. We'd have to add another 25-ish country-level sources between now and launch, and I don't think that's likely.

@joe-brilliant
 
Member
Author
joe-brilliant commented 2 hours ago
Thanks @iamleeg very helpful. I think we should remove "Aggregated case data" since we are no longer going to be referencing it, and then periodically update the individual counter. Maybe we can increase the size or add a visual thumbnail like we have for Map on the hopepage.

We do currently say over 5m cases and over 150 countries on both the homepage and in the video script and motion graphics, that latter of which is time-sensitive and about to be finalized. @Mougk any thoughts on this?

**Comment by calremmel** [comment]
Next step:

- [ ] Generate json with latest case count at 12am UTC nightly
- [ ] Save json to common place on S3

**Comment by calremmel** [comment]
The json file is generated, now it's just a matter of switching all displays to pull from it.

@rkassa I think that you have mostly completed this, if not entirely. Are there more to switch? Feel free to ping me or close this whenever!
