### ISSUE TITLE
Create consistent and persistent links between Marketing Website, /Data, and /Map.

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1398]
Currently there are links from marketing website to /Data and /Map, and a link from /Data to /Map, but no links from /Map to either /Data or website, or from /Map to website. (On /Data and /Map I would expect clicking on the corner G.h logo to take me "home", in this case probably the marketing website)

https://dev-globalhealth.pantheonsite.io/

https://curator.ghdsi.org/cases

http://covid-19.global.health/#cases

**Comment by calremmel** [comment]
I think this is basically done. Is there more to do here or may I close this? @rkassa

**Comment by joe-brilliant** [comment]
@calremmel can you post that URL spreadsheet here when you get a chance? Would be helpful for us to review and agree on before we close this out (for test, dev, and production)
