### ISSUE TITLE
Geocoding issues with DistritoFederal parser

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1407]
There are some geocoding issues with the Distrito Federal parser which mean that certain cases are being geocoded to other Brazilian states (specifically with the most recent upload it is Parana and Espirito Santo). As you can see in the below screenshot it seems in both cases it is geocoding it to 'Rua Distrito Federal', so using Distrito Federal as a street name rather than the state (ignore the weird symbols this is because of Windows encoding).

![image](https://user-images.githubusercontent.com/62887048/101765198-e8528080-3ad8-11eb-8cfa-87dd6824bc56.png)

The parser is set up to only ingest cases where state == ESPIRITO SANTO so this is not the issue. I have also looked at all the individual cases where the geocoding is failing to see if I can spot a pattern but so far I haven't found anything. For instance, for the second to last Parana case in the above screenshot, if the data is filtered by the case information it could correspond to any of the 4 following cases

![image](https://user-images.githubusercontent.com/62887048/101765454-3c5d6500-3ad9-11eb-84fd-e8b3ae12bbdc.png)

As you can see there is no common feature, I thought it may occur because RA (municipality) was unpopulated but this is not the case.

As I was going through this I remembered a conversation I had with AB and Tim a while back about this which I think is related; essentially it seems some (or most, in fact) municipalities in Distrito Federal are not in Mapbox, see for instance Lago Sul. For these locations, there is only a match up until Distrito Federal (this may have something to do with the unique administrative organization of the DF state see https://en.wikipedia.org/wiki/Administrative_regions_of_the_Federal_District_(Brazil)). So I'm wondering if the unrecognized municipalities are confusing Mapbox, making it take Distrito Federal as a street name in some cases, and therefore returning the locations in the other states. 

I think the only solution to this is that we basically set the query as 'Distrito Federal, Brazil' for all cases, and include the provided municipality info in the notes. Do you agree?

**Comment by Mougk** [comment]
Do we have a function yet in which we can specify the latitude and longitude for selected locations in the parser?

@outbreakprepared would be good to loop in. 

We could also store a separate CSV in the github that looks up these new locations.

Thoughts?

**Comment by calremmel** [comment]
@Mougk @AnyaLindstromBattle Yes we can currently specify latitudes and longitudes for cases within the parser.

Each case requires either a query string, in which case it is geocoded, or name+geoResolution+latitude+longitude, in which case those values are accepted and no geocoding is performed.

So, these edge cases can certainly be handled at the parser level. Depending on how many locations are being misinterpreted, that could be an excellent solution.

**Comment by AnyaLindstromBattle** [comment]
@calremmel, can I use the name+geoResolution+latitude+longitude method instead of geocoding for all the cases or is geocoding always preferable? There are too many cases to cherry pick the method I think, so I can either use the name+geoResolution+latitude+longitude method for all or set the query to Distrito Federal, Brazil for all cases.

**Comment by calremmel** [comment]
@AnyaLindstromBattle If it's possible to use the name+geoResolution+latitude+longitude method without a lot of hardship, I think that's the preferable solution. Geocoding is definitely not always better if there is reliable information from elsewhere.

**Comment by AnyaLindstromBattle** [comment]
Great, will sort this ASAP! Thanks
