### ISSUE TITLE
Support data import from Tableau

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1415]
The data for Paraguay is stored in a Tableau, see https://public.tableau.com/profile/mspbs#!/vizhome/COVID19PY-Registros/Descargardatos. Data can be downloaded as a CSV from the download button at the bottom (not the top Download button) of the screen > Data > Full Data > Download all rows as a text file. I managed to get a URL which worked for end-to-end testing by right clicking on 'Download all rows as a text file' but this URL now no longer works so it seems it is not stable. Anyone know how I might go about getting a URL for automated ingestion for a Tableau file?

Any help much appreciated as Paraguay is all ready to go once this issue is sorted.

**Comment by iamleeg** [comment]
We'd have to use the Tableau API.

**Comment by calremmel** [comment]
I'll have a look at what it would take to use this as a source. There are a few sources with special requirements for ingestion, and I want to avoid muddying the code with stuff like "if source is X do special bespoke thing here." If anyone has any thoughts for an elegant way to handle these kinds of exceptions while I'm brainstorming, please do let me know.

**Comment by AnyaLindstromBattle** [comment]
@iamleeg and I are having a meeting tomorrow to try and sort this, will let you know if we come up with any solutions.

**Comment by iamleeg** [comment]
@AnyaLindstromBattle looked into the options, and Tableau Public (where this data is hosted) doesn't have a hands-free way to get a CSV download link. We think we're going to have to add Tableau as a data source type in the curator portal, then use the python API or the REST API in the retrieval function to fetch the data. cc @calremmel

**Comment by AnyaLindstromBattle** [comment]
@iamleeg If you have any spare time (which I doubt you do lol), would be great to get this sorted as well.

**Comment by iamleeg** [comment]
OK will do soon

**Comment by joe-brilliant** [comment]
Moved this to Proxy for evaluation / re-prioritization for next release. I have a contact at Tableau we can engage

**Comment by iamleeg** [comment]
Didn't do it that soon…but the link on public.tableau.com is now 404 so I don't know where to get the data from.

**Comment by iamleeg** [comment]
It appears that the python tableau client API doesn't work against tableau public, but [I've asked for more information in this bug report](https://github.com/tableau/server-client-python/issues/874).
