### ISSUE TITLE
Solve timeouts during backfilling

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1434]
One of the main issues with backfilling is that you can't just set up backfilling for, say, 2 months as this will time out. The curators instead have to trial and error date chunks such that they can backfill successfully. It would be great if we could sort this out, e.g. by 'chunking' the data up as its being retrieved automatically or by automatically dividing the date range provided by the curator into smaller ranges. 

This will require some UI tweaking as well so not a quick fix, but something to tackle as a priority in the new year. It will be a big improvement on the whole platform. 

FYI @Mougk @z023 @SandraAdele

**Comment by calremmel** [comment]
I've been looking a little closer at the ingestion function and parsing_lib, and it looks like it should be possible to just split the input file into chunks and then run the parsing function asynchronously on each chunk. We'd just need some logic to handle the different file types. I don't know that it would be necessary to change much else in the code.

If I had some UI help, it might be possible to add chunk size as a settable parameter, as some parsing processes might be more intensive than others.

Any problems with this solution you can think of before I jump into prototyping it, @iamleeg ?

**Comment by iamleeg** [comment]
Good suggestion, it'd solve many situations where the input is too big for the parser to handle in reasonable time/memory. My questions:

 - do we need to do it on the input file, or can we load the input into an intermediate format (e.g. CSV or JSON) then send that to the parsers in batches? Advantages of that approach would be simplifying the parsers as they only have to support one format, and not needing to work out how to write out the split files in multiple formats. Disadvantage is that it might not solve the problem, if loading the whole dataset into memory already causes timeouts or memory problems. My guess is that it's OK, but I'd want to look into the failures more than I have :). Also means a light rewrite of the parsers that don't currently use whichever format we decide on, but not much of one.
 - can we do this without UI support? It seems like the curators want to say "here's some data, show me the cases" and we're asking lots of questions about which dates to include, how small to split the files which are more about the software architecture than the problem being solved, so I wonder if this can be automatic. The parser lib could have a timer set for something less than the AWS timeout and if that timer fires, reduce the batch size for the next try.

If we go ahead with UI changes I can help out there.

**Comment by calremmel** [comment]
Hi @iamleeg ! Thanks a ton for this.

You're totally right that we can do this without the UI changes, and I think your suggestion for automatically trying smaller batch sizes is really great.

As for loading the parsers in an intermediate format, is the following something like what you're thinking?:

1. Load input file into memory
2. Convert into either flattened rows or k:v records, whichever format we decide (probably records?)
3. Have the function itself send it in batches to the parser function, without ever saving the individual chunks on S3

I definitely see the advantages to that. I think the one source for which we might have a problem is USA, as that is the single source which is too large to load into memory. The retrieval function even dies on it in the process of attempting to store it on S3 - it never makes it to the point where it could even try to trigger the parser.

**Comment by calremmel** [comment]
A quick update to the above: it looks like the problem for USA is that the retrieval function is uploading data to AWS Lambda's ephemeral disk space first, which has a limit of 512MB, which clearly can't work for a 1.5GB file.

A comment in the code suggests streaming the data using https://docs.python.org/3/library/io.html#io.StringIO in such cases, but I think this is possibly an issue separate from chunking for the parsers.

**Comment by iamleeg** [comment]
Indeed what you said. At step 3: "without ever saving to S3" is optional. We may want to save as we go anyway, to make it quicker/safer/easier to resume a batched upload if something goes wrong (a botched batched upload, if you will).

Is the total limit for a lambda run 512MB, or is that a per-file limit? If the former, then we could consider some other storage medium, but that's probably both slower and costlier than the ephemeral storage.

**Comment by calremmel** [comment]
I laughed at botched batched, that's where I am mentally right now.

Makes sense! Given that the current process is: retrieve -> save to s3 -> call parser, all within the retrieval function, it should actually be so bad to instead say: retrieve -> split into chunks -> save copies of chunks to s3 -> call parsers on chunks.

Unfortunately, 512MB is a total limit. I looked closer, and it looks like it is the in-memory limit that is stopping USA currently, which makes sense as well. It never makes it to even trying to save to the function /tmp folder, which of course would also fail.

Someone (Tim?) left a comment in the code suggesting using the much higher memory limit (3008MB max) to use StringIO to operate on the file in memory. For USA, assuming a run every day, I estimate that would up the costs to $10 per year. It would make the other parsers pricier to some extent as well, but given I'm not sure what the budget constraints are, I don't know if that is prohibitive? (imagining for 42-ish parsers, a cost of $420 a year maximum, and that's assuming each uses the full 15 minute run, which most will not get remotely close to).

The other option appears to be spinning up an EFS instance for the data sources that require more space, and batching the files in order to keep memory requirements low.

**Comment by abhidg** [comment]
Anyone working on this? Here's a plan according to the suggestions above:

1. Split `retrieve_content()` into filetypes `retrieve_content_csv`, `retrieve_content_json`, `retrieve_content_xlsx`. This will allow us to modify chunking for these easily.
2. Modify `retrieve_content()` to call filetype functions and return a list of (filename, s3_object_key) corresponding to the different chunks.
3. Call `invoke_parser()` in a loop. As I understand, this is asynchronous, so should return immediately.
4. Modify return type of `lambda_handler()` to have a list of keys. Not sure where this return type is used.

**Comment by calremmel** [comment]
@abhidg No one is working on this yet! This plan looks great. Thanks a ton for this.

You're totally right that's misspelled -- oops.

For the larger than 512MB sources, we should think through a solution and see who has the capacity to tackle it. There's the in-memory solution referenced above, and @iamleeg also suggested perhaps an on-demand EC2 instance. It could also potentially be a batch job?

Any volunteers? If not, I could potentially look at this late next week, particularly with some help thinking through the best way to handle.
