### ISSUE TITLE
Metadata file that shows the fields available for each country

### ISSUE THREAD

**Issue by fojackson8** [globaldothealth/list#1440]
As we start using country datasets for research, we need a way to quickly find suitable countries for a particular question. 

We need to know which fields/columns are contained in each country, so we can pick suitable countries that contain all the relevant data for a particular question. This could be contained in a csv where each row is a country and contains boolean values for each column, such as 'Contains Age of Case', 'Contains Date of Symptom Onset'.

For example, say I needed countries which contain each case's Age, Travel History and Municipality for a particular analysis, I could quickly filter countries in this csv to find suitable candidates.

A simple boolean dataset could be created/updated automatically by inspecting the fields present in the parsed JSON files.

Would be good to also keep track of country-specific data idiosyncrasies, which we currently write as comments in the parse_cases function of the parser.

**Comment by calremmel** [comment]
Hi @fojackson8! I was looking through some of the issues for launch, and it looks like something like this is imagined to be available through the map visualizations. I don't know what the priority is on it, but I pinged the product team on it to ask and tagged you as well. Thanks for bringing this up!

**Comment by joe-brilliant** [comment]
Re: #1074

**Comment by abhidg** [comment]
@fojackson8 A simple way to do this would be to call `parse_cases()` on the sample data file that is included with every parser, and look at the result list of dicts to see which attributes are present. As for comments, we could include a COMMENT variable in each parser to make it visible via imports.

**Comment by iamleeg** [comment]
@fojackson8 now that we have your CSV file, can you upload the code that generated this? With that done, can this be closed?

**Comment by abhidg** [comment]
There is now a completeness visualisation in the Map coverage view, which makes it easy to check if a particular field is available for a country.
