### ISSUE TITLE
For non-curator users, left sidebars on Data should be hidden, default view should show expanded data fields, and "Linelist" should be renamed to "COVID-19 Linelist"

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1441]
Current view for curators shows two left sidebar navigations, which at present doesn't offer any functionality to non-curators

![image](https://user-images.githubusercontent.com/74671973/103027226-4ab07580-450a-11eb-941b-bcb55161cfa5.png)

For launch, we should obscure both of the left side "hamburger" navigation icons for non-curators and make the default view display more of the data fields, expanded to the width of the browser window (like screenshot below but also removing upper left corner hamburger icon and renaming "Linelist" to "COVID-19 Linelist"):

![image](https://user-images.githubusercontent.com/74671973/103027332-81868b80-450a-11eb-9763-f583d5b2e1ab.png)

**Comment by rkassa** [comment]
Actually, I think we should just leverage MUI's built in drawer show/hide functionality, and hide this by default.

It's fairly common UI that the hamburger menu implies "open menu," so any user (curator or a viewer) can toggle the menu to show at any point.

Icing on cake: more real estate for both the list and curator views!

**Comment by joe-brilliant** [comment]
Great quick fix thanks Robel!


________________________________

**Comment by joe-brilliant** [comment]
@rkassa @calremmel is this essentially fixed via #1442? Should I close it out?
