### ISSUE TITLE
Include case UUID in AWS error log message

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1452]
Change the AWS error log messages to include the UUID (if it exists) of the case on which it is failing. It would sometimes be very useful when debugging parser errors, especially where errors aren't obvious and datasets are large.

**Comment by AnyaLindstromBattle** [comment]
hey @calremmel! have you had a chance to look at this at all?

**Comment by calremmel** [comment]
Hi @AnyaLindstromBattle! I've given it a short initial glance.

It looks like cases aren't inserted individually, but are instead inserted in batches. When it says in the logs `Sending 250 cases, total so far: 5250` for example, it's literally sending those 250 cases all at once. So there is not a single UUID to return.

I could see about returning the UUID for the first ID in the batch in which it fails? Or perhaps first and last? What do you think?

**Comment by AnyaLindstromBattle** [comment]
Ah OK I see. Would returning first and last be an easy fix do you think? 

It's only really been for this most recent Japan error that I've struggled finding where the error is and I was going to have another look at it this weekend. So perhaps, if it isn't an easy fix, hold off on doing anything until then, and I'll let you know how I get on.

**Comment by calremmel** [comment]
Ah got it! Thanks for that context. I think I may be able to help a little with Japan.

The logs say there is a keyError within `convert_age` when looking for "ageBracket". A quick parse through the .json file shows that there are indeed many entries without that key.

I notice that there's not currently a way to handle that missing key. The fix might be as simple as adding at the top of the function something like:
```
if "ageBracket" not in raw_age.keys():
    return None
```

Let me know if that is on the right track at all?

**Comment by AnyaLindstromBattle** [comment]
Hey, yes that was what I thought it was initially as well, but there have been cases with missing ageBracket information in the data for quite a bit before that error started appearing, so I thought it couldn't be that. 

But indeed that was one of the things I was going to try this weekend, so we'll see how it goes!

**Comment by AnyaLindstromBattle** [comment]
Just looking at this again now, the first date of that error message was Dec 24th but there are cases with no ageBracket entries e.g. on Dec 6th

![image](https://user-images.githubusercontent.com/62887048/104374311-9fe41380-5519-11eb-9703-c08800ed4ce1.png)

**Comment by AnyaLindstromBattle** [comment]
@calremmel looks like it was just that! Classic me, overcomplicating things. Will close this now.
