### ISSUE TITLE
Configure Google email accounts for global.health domain

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1461]
We'll need a handful of email accounts for user or legal inquiries, e.g. "info@global.health". I can help with credit card info and taking on the admin role when needed

**Comment by WeronikaMichaluk** [comment]
@joe-brilliant 
Could you please advise if we should set up an email on AWS? OR maybe you have something else in mind?
Will go with info@global.health right?
Thanks

**Comment by WeronikaMichaluk** [comment]
HTD to set up email on **AWS**

**Comment by joe-brilliant** [comment]
Yes thanks that’s the main email! Let me know how best to get you payment/cc info


________________________________

**Comment by WeronikaMichaluk** [comment]
@joe-brilliant is Email ok to send us payment/cc info or you would rather do a quick call and say that instead of sending it over?

**Comment by joe-brilliant** [comment]
thanks @WeronikaMichaluk per our sync today since we have GA access via BCH now we'll move this to post launch and use ghdsi.info@gmail.com as our contact alias for now. I'll move this to P2 / post launch

**Comment by joe-brilliant** [comment]
@WeronikaMichaluk can you please remove this from the HTD Kanban board? I can seem to. Thanks!

**Comment by joe-brilliant** [comment]
@WeronikaMichaluk NM I got it !

**Comment by joe-brilliant** [comment]
Closing in lieu of duplicate issue
