### ISSUE TITLE
Handle routes for URLs with filter parameters

### ISSUE THREAD

**Issue by rkassa** [globaldothealth/list#1462]
**Current Behavior:**
Currently there is no route handling for filter parameters getting added/removed/updated. Regardless of any filter changes, the URL stays put as `https://dev-curator.ghdsi.org/cases`
**Worth noting:** routes do get handled for the sidebar drawer menu items (where available), and when viewing an individual line list item: `https://dev-curator.ghdsi.org/cases/view/5f833661533b6f7fa8249552`

**Feature Request:**
- Additional route handling for filters, so that URL gets updated along with filter param changes:
`https://dev-curator.ghdsi.org/cases?gender=male`, for example.
- Similarly, if a URL like this is attempted to be accessed, it should go through our expected auth verification first, before being taken directly to the requested URL
- The filter bar should also reflect the filter query paramaters dictated in the URL:
- ![Screen Shot 2021-01-08 at 3 06 20 PM](https://user-images.githubusercontent.com/201428/104059284-1522b200-51c3-11eb-9d7c-ad45d7cb8fbf.png)
- It should allow for multiple filter paramaters: `?gender=male&admin3=warsaw&date=20210101`
- The linelist table should reflect the outcomes of said filters, as well, of course.

**Comment by rkassa** [comment]
@maciekz1996 @WeronikaMichaluk 

One thing I noticed — the second point in the acceptance criteria is not working for me at all on the dev-curator site:

> Similarly, if a URL like this is attempted to be accessed, it should go through our expected auth verification first, before being taken directly to the requested URL

If you're not logged in, going to https://dev-curator.ghdsi.org/cases?country=%22India%22 will correctly prompt you to login, but once logged in, it doesn't take you to the requested filtered URL. It just lands you on the curator homepage instead. Should we move this ticket back to in progress or create a separate ticket for this feature?

**Comment by maciekz1996** [comment]
@rkassa The issue that you mentioned is resolved in this PR (https://github.com/globaldothealth/list/pull/1491). Everything should work fine now
