### ISSUE TITLE
Map UI Improvement Punchlist

### ISSUE THREAD

**Issue by rkassa** [globaldothealth/list#1467]
- [x] Update primary nav to use only Regional, Country, and Coverage Views 
- [x] Remove/deregister extraneous views
- [x] Clean up popup styles in all map views
- [x] Add "progress bar" to coverage map popups
- [x] Add "explore data" button to all map view popups

**Comment by rkassa** [comment]
PR for this issue:
https://github.com/globaldothealth/viz/pull/92

**Comment by rkassa** [comment]
FYI: @joe-brilliant @calremmel @WeronikaMichaluk 
This is the retroactive issue ticket for the map UI improvements

**Comment by WeronikaMichaluk** [comment]
@rkassa would you like us to work on that?

**Comment by rkassa** [comment]
@WeronikaMichaluk 
Oh no, the work is for this ticket is already done here: https://github.com/globaldothealth/viz/pull/92. 
I just wanted to keep everybody looped in on the issue ticket for it, that's all.
