### ISSUE TITLE
HTD_ splitted issue On Data page, change default "Download" function to export CSV of daily cached full data set #1436

### ISSUE THREAD

**Issue by WeronikaMichaluk** [globaldothealth/list#1468]
For MVP instead of initiating DL of data set based on applied filters, initiate a download of full daily cached data set and rename button "Download full data set". This will ensure a consistent and stable experience and allow users to sort, filter, and manipulate data via local applications while we further define and refine the Data page UX post-launch. This will entail:

- Designing new "Download full data set" button
-  Create interstitial modal explaining data set being downloaded is daily cached full G.h data set and may not exactly match record count in UI, total or filtered. (exact language TBD)

**Comment by WeronikaMichaluk** [comment]
@joe-brilliant @calremmel 
I have splitted issue 1436 into Front and Backend - > this one is about Frontend. 

As for Designing button -> should we use UI UX library or you have any specific design for that?

**Comment by WeronikaMichaluk** [comment]
@joe-brilliant @calremmel 
Could you please provide us with more details like some screenshots where does this task apply to? Could you please attach here some screenshots with some more description, please?
Where should changes be made?
We are not sure where is that mentioned button?
Could you please advise where should we create/design: **interstitial modal explaining data set being downloaded is daily cached full G.h data set and may not exactly match record count in UI, total or filtered. (exact language TBD)**

**Comment by calremmel** [comment]
@WeronikaMichaluk Of course! The button is here:

![image](https://user-images.githubusercontent.com/40274075/104615083-df644a00-5656-11eb-8b4b-424a5322a39b.png)

@rkassa may have already created this button. @rkassa is that right? If not, it would be great for you to design.

The modal should appear when you click that button. The modal should have the following components:

1. Text along the lines of the following (will change but this is good for now).

> This download link provides access to the full Global.health line list dataset, cached daily at 12:00am UTC. Any cases added past that time will not be in the current download, but will be available the next day.

2. Link to download latestdata.tar.gz on S3 (not generated yet, link to be provided probably next week)

@joe-brilliant If you have any more directions for the modal text, please feel free to share here.

**Comment by joe-brilliant** [comment]
Thanks all, text looks good!

**Comment by zbigiman-htd** [comment]
I've made the dialog modal:

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/69294239/105143860-b59a9f80-5afc-11eb-931e-1c386c8a0f9f.png">

@joe-brilliant is it OK?
