### ISSUE TITLE
Handle ingestion for data sources larger than 512MB

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1488]
AWS Lambda has a maximum ephemeral storage of 512MB. For data sources that yield files that are larger than 512MB in size, there needs to be a way to handle this limitation.

Suggested methods include:

1. Use StringIO to load the input file into memory rather than storage. AWS Lambda can handle up to ~3GB this way.
2. Use an on-demand EC2 instance for large sources.
3. Trigger a batch job for large sources.

If you have thoughts on the best route, and/or the capacity to take this on, please let me know! We will be unable to load USA data until this is implemented, so it is a launch blocker.

**Comment by iamleeg** [comment]
Capacity? ROTFL. Another approach is to create an event-driven parser, so that the parser only stores as much of the file in memory as it needs to interpret the field/record currently being read. For example, here's a (JS) [event-driven CSV interpreter](https://github.com/mafintosh/csv-parser). This approach vastly reduces the memory requirement, but is certainly more complex than just running the existing code somewhere with higher storage quotas.

**Comment by abhidg** [comment]
@calremmel Happy to help on this as I am working on the retrieval code for #1434 anyway

**Comment by calremmel** [comment]
@abhidg Here is the info needed to move forward with this! Please let me know if you have questions, or if you would like to split this up somehow.

**Docs:** https://docs.aws.amazon.com/lambda/latest/dg/configuration-filesystem.html

**Summary**

In order for the parser lambdas to use EFS, they need to have a few things, all of which can be defined in `template.yaml'

1. Permissions to access VPC resources and EFS, which may be granted with the `AWSLambdaVPCAccessExecutionRole` and `AmazonElasticFileSystemClientReadWriteAccess`
2. Information on which EFS to mount and where to mount it, which are defined under `FileSystemConfigs`. Here you should be able to call the local mount point whatever you like.

There are example functions available in the following repositories:

https://github.com/aws-samples/aws-lambda-efs-samples
https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/efs-nodejs

I've created `covid19DataIngestionEFS` for use with the ingestion functions, but you should have full access to edit and create if needed.

Let me know if this seems manageable! Thanks a ton again for tackling.

**Comment by calremmel** [comment]
@abhidg Just checking in to see if this is doable? I think we are hoping to have USA and Canada ingested by Feb 18. Let me know if there is any part of it where it would be helpful to have some support.

**Comment by abhidg** [comment]
@calremmel Just finished fixing the tests for the backfill issue #1498, I'll start work on this as soon as that is merged. This should be simple to setup, I will have a look tomorrow!

**Comment by calremmel** [comment]
@abhidg This is great, thanks a ton! Just let me know if you find you need anything, more access etc. as you go along. Big thanks.
