### ISSUE TITLE
Create a variant of concern tracking webpage for curators

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1495]
Currently, there is no established process for keeping track of new variants of concern (VoC, https://cov-lineages.org/global_report.html). At the moment, there are no widely available line lists for VoCs, so we can't use our usual ingestion workflow. Google alerts and news APIs can give us reports of individual or collective cases, but they need to be kept track of, reviewed by a curator and added to a spreadsheet.

It would be good to have a simple website that can keep track of some state associated with each URL or sequencing data from GISAID. Suggested fields are
* assigned curator (string)
* relevant? (bool) Usually this means the URL contains unique individual or localised case information relating to one or more VoC
* processed (bool) Whether this URL has been looked at by a curator and added to spreadsheet.

At the moment, there is no unified way of keeping track of these cases. I will set up automated uploading to Google sheets from Google alerts, but it would be good to have a proper website that can be used by curators.

**Comment by Mougk** [comment]
@abhidg can you add the queries for B.1.1.7, B.1.351 and P1 here too.

**Comment by abhidg** [comment]
* B 1.351 case (covid OR coronavirus) https://www.google.com/alerts/feeds/07571940931476605893/2885779052793466526
* B 117 case (covid OR coronavirus) https://www.google.com/alerts/feeds/07571940931476605893/9305357296511739967
* P.1 case (covid OR coronavirus) https://www.google.com/alerts/feeds/07571940931476605893/16862758354496195281
