### ISSUE TITLE
Filter Data using Variant of Concern

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1502]
Users should be able to filter cases in Data by Variant of Concern.

- [x] Users should be able to filter for specific Variants
- [x] Users should be able to filter for any Variants (i.e. not null or equiv)

**Comment by iamleeg** [comment]
Can we move the third point to #1501 @calremmel @rkassa @joe-brilliant? Otherwise there's a cyclic dependency where we can't build the map until filtering is done, but we need to have the map feature before we can do filtering.

**Comment by calremmel** [comment]
@iamleeg Of course you're right, that makes no sense there. I'll move it now!
