### ISSUE TITLE
Data Acknowledgement section

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1510]
Importantly data contributors need to be acknowledged on the website. This ultimately increases trust.

Other platforms have done this successfully by having a designated 'Data Acknowledgement' section (see for example bottom page here: https://cov-lineages.org/contributors.html).

My suggestion is to add a 'Data Acknowledgement' button on the about page directly below the mission statement (see screenshot below)

![Screenshot 2021-02-04 at 10 16 27](https://user-images.githubusercontent.com/8478551/106878616-0d770000-66d2-11eb-87af-133c4d1848e0.png)

Then have a section which has three columns (maybe more/less?) similar to below (sorry this is improvised and most relevant would be the orange which I added; also see the new subpage URL)

The link to the information is constantly updated and can be accessed from here: https://docs.google.com/spreadsheets/d/1xN7aRqiw8vcXw8EnDm5Dyy2-Lc4SThVi69GdexxYcEc/edit 

![Screenshot 2021-02-04 at 10 17 46](https://user-images.githubusercontent.com/8478551/106878754-3c8d7180-66d2-11eb-98e0-da865de2ecce.png)

We can then specifically click on Data Acknowledgements for GISAID which needs specific attention. That subpage could then look like using this link: https://docs.google.com/spreadsheets/d/1fanQtM7vTt3fN3Z-QqAilVEAxm7iu4Yo7Uw4UTNiDdY/edit)

![Screenshot 2021-02-04 at 10 19 29](https://user-images.githubusercontent.com/8478551/106878962-79f1ff00-66d2-11eb-9b58-038e8fa6a27f.png)

### 

DATA for the sections above can be provided in CSV format and stored/updated as we ingest more data streams. For now I am suggesting to only use those that have an automated ingestion set up.

Thoughts?

**Comment by WeronikaMichaluk** [comment]
@joe-brilliant @Mougk 

Would you like us to take care of that issue and add it to our kanban board?

**Comment by Mougk** [comment]
For GISAID Acks table @fojackson8 can help point you to the right file.

**Comment by Mougk** [comment]
Nice work @rkassa. Couple of comments:

1. remove License column

2. Below suggested text that can go on the top:

_"We acknowledge the hard work and open-science of the individual research labs and public health bodies that have made epidemiological data available. A detailed table of acknowledgements for the data used on this platform is below."_

3. Add another one that is dedicated to the GISAID Acknowledgements (https://docs.google.com/spreadsheets/d/1fanQtM7vTt3fN3Z-QqAilVEAxm7iu4Yo7Uw4UTNiDdY/edit).
_"We acknowledge the hard work and open-science of the individual research labs and public health bodies that have made epidemiological data available through GISAID. A detailed table of acknowledgements for the data used on this platform is below. Please note that data coming from GISAID (https://www.gisaid.org/) cannot be downloaded through this platform."_

**Comment by rkassa** [comment]
@Mougk @joe-brilliant 
This is ready here:
https://dev-globalhealth.pantheonsite.io/ackowledgement/

**Comment by AnyaLindstromBattle** [comment]
@rkassa that table (acknowledgments) wasn't quite done yet, finishing it off now. Is that OK?

**Comment by Mougk** [comment]
Thanks @rkassa. Just remove the " " from the the text.

**Comment by AnyaLindstromBattle** [comment]
@rkassa table all done, thanks!

**Comment by rkassa** [comment]
@Mougk @AnyaLindstromBattle @joe-brilliant 
All set here:
https://test-globalhealth.pantheonsite.io/ackowledgement/

**Comment by AnyaLindstromBattle** [comment]
@rkassa I think that's still the old table? i.e. not the one I updated yday, which should also have entries after Germany
