### ISSUE TITLE
Exclude certain sources from the case list and data download

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#1520]
**Is your feature request related to a problem? Please describe.**
We use certain data sources where our license/terms of use permit sharing aggregate data, but not individual records. Those sources should be excluded from the case counts, the line list in the portal and the curator-service API, but should still be used in calculating top-level metrics for the map visualisation.

There should be some explanatory text somewhere (@mougk to provide) explaining the situation and any disparity in numbers seen across the site.

We think the filtering should probably be based on source ID or URL so that we know any records from a specific source won't be included.

**Comment by fojackson8** [comment]
Given that each case has an associated source_URL, presumably providing a list of source_URLs to be excluded would be a sufficient input here?

**Comment by iamleeg** [comment]
Yes, indeed.

**Comment by Mougk** [comment]
Suggested Text to be added: 

"Metadata from GISAID (https://www.gisaid.org/) are not available for download through this website and only aggregated counts are included in the visualisations. See data acknowledgements here: LINK TO DATA ACKS SECTION (https://dev-globalhealth.pantheonsite.io/ackowledgement/)"

Sound good?

**Comment by iamleeg** [comment]
thinking of adding a toggle to the sources editor in the curator UI for "include cases from this source in the line list" and then working out everything else that needs to respect that toggle; will work on that until someone tells me why it's a bad idea :)

**Comment by iamleeg** [comment]
This has been merged and deployed.
