### ISSUE TITLE
Create help text button and modal for Map

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1526]
Similar to the ? button on Data, this should serve as a "legend" to explain each of the top nav views (Country, Region, Coverage, Variants), data sources (links to data sources/acknowledgments, GISAID, JHU, etc), and left nav, and a link to FAQs

**Comment by joe-brilliant** [comment]
Here's a first draft, @Mougk @calremmel @rkassa can you take a look and weigh in? Thanks!

**Welcome to Global.health Map!** 

These geospatial data visualizations allow you to explore our line-list data set through a few different views:

**Country View:** Click on a country to see available COVID-19 line-list data in that country, and click through to see corresponding filtered results on G.h Data. You can also use the left-hand navigation to search or select a country, and view available data for Variants of Concern. Darker colors indicate more available data. (Please note: not all variant data may be available to view or download. Please see our [FAQs](url) and [Data Acknowledgments](url) for more info.)

**Regional View:** Click on extrusion to see available data in that region, and click through to see corresponding filtered results on G.h Data. Taller extrusions indicate more available data. Records that do not include regional metadata are labeled and indicated as "Country, Country" (e.g. "India, India"). Please see our [FAQs](url) for more info. 

Coverage Map: This view illustrates available _line-list_ COVID-19 case data in the Global. health database in a given coutnry as a percentage of total _aggregate_ case data as indicated by the [Johns Hopkins University COVID Resource Center](https://coronavirus.jhu.edu/map.html). Totals are updated daily.

**Comment by Mougk** [comment]
Made minor edits in the above. Looks good

**Comment by scarpino** [comment]
This looks good to me

**Comment by joe-brilliant** [comment]
Thanks @Mougk @scarpino. @rkassa / @WeronikaMichaluk this is good to start implementing. I think the icon to trigger it should be a prominent "?" tile to the left of "Country View" or may just next to "G.h Map" logo in the corner?

**Comment by joe-brilliant** [comment]
Hi @rkassa @maciekz1996 @sergioloporto @WeronikaMichaluk @calremmel can we please make this a top priority for our final pre-launch relesease? I know it's been approved/discussed a bit but unclear on the status for implementation

**Comment by sergioloporto** [comment]
@joe-brilliant the task is ready from my side and is on review: https://github.com/globaldothealth/viz/pull/97

**Comment by joe-brilliant** [comment]
Fantastic, thanks @sergioloporto! @calremmel @rkassa can you review as needed?

**Comment by joe-brilliant** [comment]
@maciekz1996 @rkassa @sergioloporto @WeronikaMichaluk the links to FAQ and Data Aks on the Map help modal were going to broken links on Github since we didn't have live links, I just fixed them above. Can you update please update the copy and links? Thanks!

**Comment by sergioloporto** [comment]
> @maciekz1996 @rkassa @sergioloporto @WeronikaMichaluk the links to FAQ and Data Aks on the Map help modal were going to broken links on Github since we didn't have live links, I just fixed them above. Can you please update the copy and links? Thanks!

@joe-brilliant  Done. PR waiting for approval => https://github.com/globaldothealth/viz/pull/99

**Comment by joe-brilliant** [comment]
Thanks!!


________________________________
