### ISSUE TITLE
Create custom welcome emails for new users 

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1527]
(placeholder for now, @joe-brilliant to draft copy)

**Comment by WeronikaMichaluk** [comment]
HI @joe-brilliant could you elaborate on that task please?
How long should email be? Should it be very formal/informal?
What kind of users do we have in mind here?

**Comment by joe-brilliant** [comment]
I'll draft up some text thanks!

**Comment by joe-brilliant** [comment]
Here's a first pass at copy for welcome emails. @Mougk @rkassa @calremmel @scarpino would love your eyes/feedback/edits. Once we get copy finalized and approved I can add links to our eventual production site. 

@sergioloporto @maciekz1996 @calremmel can you confirm we can send out both of these emails? 

**For NON Google Emails,**

From: Global.health <ghdsi.info@gmail.com>
Subject: Your secret Global.health login code 
To: <email address>

Hello <email address>,

Thank you for signing up with Global.health! To securely verify your registration, please enter this secret login code:

<insert login code>

If you encounter any issues, don't hesitate to email us back.

Thank you!

The G.h Team


**For ALL emails (Google AND non Google) after confirmation of registration, only to be sent _once_**

From: Global.health <ghdsi.info@gmail.com>
Subject: Welcome to Global.health!
To: <email address>

Hello <email address>

Thank you for registering with Global.health! We're thrilled to have you join our community and mission to advance the global response to infectious diseases through the sharing of trusted and open public health data.

Here are a few things you can do:

-Filter and export **G.h Data** containing detailed information on over five million anonymized COVID-19 cases from over 100 countries.

-Explore the **G.h Map** to see available case data visualized by country, region, and coverage. You can also find up-to-date line-list data on variants of concern which will be updated and expanded regularly. 

-Check out our **FAQs** for more information on our platform, process, team, sources, citation guidelines, and plans for the future! 

-Get involved! G.h is being built via a network of hundreds of volunteers that could use your help in creating a revolutionary global source of information. If you're interested in volunteering, please fill out this **form**.

-Connect with @globaldothealth on **Twitter**, **LinkedIn**, and **GitHub** for the latest news and updates.

If you have any questions, suggestions, or connections don't hesitate to email us and a member of our team will be sure to follow up.

Thank you for your interest and support! We hope G.h proves valuable to your work and look forward to hearing from you.

The G.h Team

**Comment by Mougk** [comment]
I think this email sounds great. No further comments.

**Comment by joe-brilliant** [comment]
@rkassa can you let us know what the customization options are for substack welcome emails? maybe we can add the logo and add some text/links etc along the lines of the above

**Comment by joe-brilliant** [comment]
@maciekz1996 @calremmel @sergioloporto @WeronikaMichaluk hi all, just created an account on production using a non Google account but didn't get the welcome email. Can we please make this a priority fix? Thanks!

**Comment by joe-brilliant** [comment]
I added links to the email copy as well @maciekz1996 @calremmel @sergioloporto @WeronikaMichaluk @rkassa ^

**Comment by maciekz1996** [comment]
@calremmel Did you menage to change `EMAIL_USER_ADDRESS` environment variable to `ghdsi.info@gmail.com`? This can be the reason the welcome emails are not being sent.

**Comment by joe-brilliant** [comment]
Hi all, I just enabled this for that gmail account, maybe that will help
can you try again?
https://support.google.com/accounts?p=lsa_blocked&hl=en&authuser=1

**Comment by joe-brilliant** [comment]
@maciekz1996 and @calremmel I think we can close this until we move to a proper G.h email domain config?
