### ISSUE TITLE
Filtering by country doesn't always work

### ISSUE THREAD

**Issue by scarpino** [globaldothealth/list#1528]
**Describe the bug**
If you filter G.h Data by certain countries, the list is empty, but downloading the data, there are clearly cases from those countries. Double checked that is wasn't an obvious spelling issue. Doesn't effect all countries, i.e., some country filtering working.

**To Reproduce**
1. Go to https://dev-curator.ghdsi.org/cases?country=%22Turkey%22
2. See that there are 0 records returned (downloading the data and according to G.h Map there are 159779
3. Go to https://dev-curator.ghdsi.org/cases?country=%22Brazil%22
4. See that there are cases

**Expected behavior**
I would expect that all countries with cases in the data base would be filterable and that clicking on the map results on G.h data showing the number of cases reported in the map, as opposed to zero. 

**Screenshots**
<img width="1370" alt="Screen Shot 2021-02-06 at 3 47 06 PM" src="https://user-images.githubusercontent.com/1714728/107129322-989ef400-6892-11eb-98d4-d21bf05986f8.png">

<img width="1030" alt="Screen Shot 2021-02-06 at 3 47 35 PM" src="https://user-images.githubusercontent.com/1714728/107129328-a3f21f80-6892-11eb-93f2-1717d59bbc83.png">

<img width="438" alt="Screen Shot 2021-02-06 at 3 47 46 PM" src="https://user-images.githubusercontent.com/1714728/107129330-aa809700-6892-11eb-9865-31107461fe43.png">

**Environment (please complete the following information):**
 - OS: 10.15.7
 - Browser Chrome

**Additional context**
I tried under both my curator account and a new account.

**Comment by joe-brilliant** [comment]
Thanks for flagging @scarpino! I've also added this as a sub task under #1508. Let's prioritize and triage on Monday

**Comment by WeronikaMichaluk** [comment]
@joe-brilliant should HTD take a look at this?

**Comment by joe-brilliant** [comment]
Let's discuss and delegate all larger issues tomorrow, thanks! If you guys
can tackle as many of the bugs in the bug bash for now that would be great.
