### ISSUE TITLE
Unstructured queries on Data do not always show relevant results

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1529]
E.g when searching for "Turkey" (with no filter paramaters) the search returns 11 results, none of which are relevant to Turkey.

AAU, I would it expect this search to at least return all cases with Turkey in the country field (according to Map: 59,779 cases)

https://dev-curator.ghdsi.org/cases?q=turkey

https://www.dropbox.com/s/vzo84p4ahf7s0fc/Screen%20Shot%202021-02-06%20at%201.57.04%20PM.png?dl=0

**Comment by elvey** [comment]
Umm... this isn't fixed.  E.g when searching for "Turkey" (with no filter paramaters) the search STILL returns 11 results, none of which are relevant to Turkey.  Same at https://data.covid-19.global.health/cases?q=turkey

**Comment by elvey** [comment]
I understand why you opened #1836 (and that the 11 that I do see come up because "Turkey" is within the Notes field).  But is joe-brilliant not right that it should at least return all cases with Turkey in the country field (according to Map: 59,779 cases)?
<edit - yay - fixed>
