### ISSUE TITLE
Add help text and instructions for data filters

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1540]
Multiple beta tester responses reported that the filters are difficult to interpret and use. We would like the following outcomes for users:

- Users should be able to easily understand how they can filter results
- Users should be able to easily learn the filter syntax
- Users should be able to see what they have filtered for after executing a search

Here is a proposed solution:

- [ ] The "?" tooltip has more intuitive examples
- [ ] The "?" tooltip explains that matches must be exact
- [x] On hover, the column headers display the filter keyword that enables filtering by that column
- [x] Clicking on a column header inserts the appropriate filter keyword into the search bar
- [x] After searching, there are breadcrumbs underneath the search bar displaying the current filter key/values

Alternatives welcomed! Please share thoughts below.

**Comment by calremmel** [comment]
Improved copy needed for the "?" tooltip. Any takers? :)

**Comment by joe-brilliant** [comment]
Thanks @calremmel ! I think this looks great. @WeronikaMichaluk is this something HTD can take on? I'll add to your kanban board for triage for the time being

**Comment by WeronikaMichaluk** [comment]
@maciekz1996 @sergioloporto lets take a look at this task please

**Comment by maciekz1996** [comment]
@joe-brilliant sure, we can start working on this issue !

**Comment by WeronikaMichaluk** [comment]
@maciekz1996 is taking care of that! :)
