### ISSUE TITLE
"null" values in "regional data" causing misleading/confusing data visualizations on Map

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1545]
E.g. "null, India" is resulting in a rendering on the map that appears to illustrate a million-plus cases in one "region" called "null". Instead these data should include a real region in India, or no values at all so the map doesn't attempt to innaccuratley render them in Regional View

https://www.dropbox.com/s/g5kk6k6ivh2cll8/Screen%20Shot%202021-02-06%20at%202.04.48%20PM.png?dl=0

**Comment by calremmel** [comment]
I changed it so that regions without specific information now default to the country.

This results in "India, India" rather than "NULL, India." Does this work, or would we prefer just "India?" @Mougk @joe-brilliant @rkassa
