### ISSUE TITLE
Completeness and Freshness charts don't load

### ISSUE THREAD

**Issue by allysonjp715** [globaldothealth/list#1603]
The charts on the completeness and freshness tabs load for a long time, and then say "unable to retrieve data". The charts on the initial cumulative tab load fine. 

**To Reproduce**
1. Go to curator.ghdsi.org
2. Click on completeness tab
3. View long loading and failures
4. Same for freshness tabs

**Comment by calremmel** [comment]
I think it would be useful to think through what kinds of metrics it would be useful for curators to see, and then see what we can deliver that will load quickly.

Curators: what ideally would you like to see in place of the slow-loading mongo charts, if anything? Are there metrics that would be useful to have at a glance, or would it be better to simply remove the whole thing?

If there are metrics that it would be useful to have at a glance, it would be great to know if they need to be up to the second, hour, day, etc.

**Comment by Mougk** [comment]
I think we understand that the mongodb has a hard time loading and tbh we don't really look at these charts. Maybe we can close this? @calremmel

**Comment by calremmel** [comment]
@WeronikaMichaluk Current desired solution is to simply remove this component!

**Comment by WeronikaMichaluk** [comment]
@calremmel thank you for update!

**Comment by rkassa** [comment]
Based on past discussions and @calremmel's message above, the completeness and freshness charts are disabled.

@joe-brilliant I'm closing this for now, since there's no bug, no fix, and no next steps necessary.
