### ISSUE TITLE
Enable users to download filtered results

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1608]
A critical next feature is to allow Data users to download the filtered results of their queries, rather than only the entire dataset. Currently, the download API endpoint times out on larger queries, and the download format it returns is out of date.

An ideal solution has the following requirements:

- [x] Users can download the results of small queries immediately.
- [x] Users can select from several different download formats.
- [x] Users can receive a link by email to download the results of larger queries.

There are multiple pieces to implementing such a solution. Here is an initial proposal for the work involved:

**UI**

- [x] Download modal presents 3 delivery options:
  1. Download up to {limit} rows immediately
  2. Download more than {link} rows through link delivered by email
  3. Download entire dataset immediately
- [x] Download modal allows choice of csv, tsv, and json formats
- [x] Large query users should be instructed to add info@global.health or appropriate to their contacts list or check spam so that they don't miss their download link

**Backend**

- [x] /download API endpoint is updated to return current data format
- [x] /download API endpoint returns a maximum of {limit} records, where limit is defined by max that can be returned quickly
- [x] /downloadLarge API endpoint submits query to be run in queue using AWS Batch
- [x] AWS Batch job should export and parse results in fashion identical to total data export job
- [x] Parsed results of large query should be saved compressed as temporary s3 object
- [x] Link to temporary s3 object should be sent to query user by email
- [x] Query results should expire and be cleaned up after 3-7 days

**Comment by iamleeg** [comment]
> "/download API endpoint is updated to return current data format"

Is there documentation on the expected data format anywhere? The download endpoint gets its configuration from data-serving/scripts/export-data/case_fields.yaml so simple to update.

**Comment by iamleeg** [comment]
OK I've thought through and designed the large-download-via-Batch API, and ended up not needing Batch :). I'd love some feedback on this idea @calremmel @abhidg @rkassa @sergioloporto @maciekz1996 to make sure I didn't overlook something.

## Strawman data flow

Let's follow the design where we use Batch, and see the implications.

### 1. curator places request for large download

This is done via the curator-service API at `/cases/downloadLarge?q=blah`.

### 2. this batch job triggered

curator-service submits a job to the batch queue. Now here's a problem: the batch queue is going to run _outside_ the authenticated user's context in curator-service, but on behalf of them. How do we ensure that the user is actually permitted to see the query results, and that someone isn't submitting jobs to spam someone's inbox with multi-gigabyte CSV files? Read on!

curator-service _doesn't_ send the query details to the batch job, and the batch job _doesn't_ have access to any information about the user, and doesn't use the cases collection. Instead, curator-service writes a document to the `downloadQueries` collection in mongo, describing the query and the user, and then the parameter that the batch job receives is the ObjectID of that query.

What happens now?

### 3a. the batch job reads the query from MongoDB, does the search, and stores the results in S3

OK, but now we need to duplicate all the filtering code into the batch job from the curator or data service, or break it out into a private npm module and share it or something, and make sure they're always in sync (despite the deployment models for the batch task and the curator-service being different). We also have an extra service user on mongoDB to manage.

### 3b. the batch job reads the query from MongoDB, and calls the API to do the search, and stores the results in S3

OK great, now we have one place where the API is implemented, and the batch task is just doing workflow management. We still have that extra mongo user. So my question is…why?

## Alternative design

### 1. curator places request for large download

This is done via the curator-service API at `/cases/downloadLarge?q=blah`.

### 2. curator-service replies 204 and asynchronously starts the download

no Batch management, no service task doing work on behalf of users without authenticating them, this seems easier: curator-service gets on with the fetch in the download and does the writing to S3/emailing when it's done.

Is there anything I've missed that makes this unworkable?

**Comment by calremmel** [comment]
@iamleeg I can't think of anything you've missed, and this makes total sense!

curator-service is already set up such that it should scale out horizontally far beyond what we would ever need, and plenty of folks use EKS for exactly this use case. I think the AWS Batch design was more of the classic "I have this hammer so let's go find some nails" thinking on my part.

Looks great to me!

**Comment by iamleeg** [comment]
Thanks, @calremmel! Happy that neither of us can see any problems before I code it up and discover what they are :D
