### ISSUE TITLE
Explore additional file formats for data exports

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1609]
Placeholder with feature suggestion via user below. Maybe this can be folded into filtered data query exports? 

---------- Forwarded message ---------
From: David Hanauer <hanauer@umich.edu>
Date: Wed, Feb 24, 2021 at 2:48 PM
Subject: Dataset format
To: <ghdsi.info@gmail.com>

Hi.  This dataset looks very interesting.  Is there anyway to download it in another format like a TSV?  It can be challenging to parse out the columns when the separator (commas) are also within some of the text.  it would be ideal if the column separators were not present anywhere else in the dataset, such as tabs or pipes (|),  Thanks for considering.

David Hanauer
University of Michigan

--

**Comment by abhidg** [comment]
This is part of the filtered data downloads work, which has been merged into main
