### ISSUE TITLE
Expanded / more detailed data dictionary and FAQ on sources/methods

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1610]
From: David Hanauer <hanauer@umich.edu>
Date: Thursday, February 25, 2021 at 1:56 PM
To: "Brilliant, Joe" <Joe.Brilliant@childrens.harvard.edu>
Subject: Re: Dataset format [EXTERNAL]

Hi Joe,
 
Thanks for responding.  I haven’t looked into things too much since I kind of got stuck parsing out the data with the “simple” tools I often use (hence my request for a delimiter that doesn’t appear in the data itself).
 
In terms of other “features”, I would say that the data dictionary seems to be somewhat thin in terms of details.  It would be nice to know things like (a) what column number each represents so I don’t have to count to know what each refers to.  (b) more details about each column.  For examples, "List of symptoms”: Are these free text?  Coded?  How is that information collected?  From a chart review?  Self reported?  Collected by a health agency?
 
In general I’m a bit unclear on what the origins/sources of the data are, how they are collected, how they are curated/verified, etc.  
 
And, how is this dataset different from other large datasets already out there (like N3C, for example).  I do see that this has international data, which N3C does not.
 
Best,
 
David

**Comment by elvey** [comment]
Umm... What data dictionary? The link to the data dictionary is broken. "Data dictionary" in the lower left corner of the main page (appears after clicking on the hamburger) links to a 404 URL here: https://github.com/globaldothealth/list/blob/main/data-serving/scripts/export-data/case_fields.yaml
What are the 40 fields?  If I open a single case, e.g. https://data.covid-19.global.health/cases/view/5f73b327cb263be4fff8533e am I seeing all the fields?  I was hoping to see fields indicating treatments given, or at least Rx given.

**Comment by abhidg** [comment]
See #1658 for missing data dictionary.

**Comment by abhidg** [comment]
Related #1736

**Comment by abhidg** [comment]
Some of the requested info has been added in 9a21e7df47f127d5c06e0176693461e55859b622 @joe-brilliant could you review and close if this is done?

**Comment by joe-brilliant** [comment]
@abhidg @jim-sheldon just saw this last comment, apologies. I'll take a look on Monday

**Comment by joe-brilliant** [comment]
This looks good to me thanks @abhidg. @Mougk any final comments on the updated Data Dictionary? Let's close this out this week.
