### ISSUE TITLE
Set up dedicated global.health emails + Gsuite + Slack org 

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1611]
TBC

**Comment by joe-brilliant** [comment]
@jim-sheldon the folks at Google.org are looking into credits but if you can connect with Sudheer to get the ball rolling that would be great. If we need to pay we can do so via BCH. thx!

**Comment by jim-sheldon** [comment]
I got the admin account set up, now I just need to know who (and/or what) needs an account and email.

**Comment by joe-brilliant** [comment]
@jim-sheldon @abhidg I think we can close this out now, I'll make a new issue to track swapping it out across the site / codebase
