### ISSUE TITLE
Colombia, Peru, Czechia cases not visible in country view

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#1614]
No cases for Peru, Colombia and Czechia visible in country view, but cases shown in regional view. 
![image](https://user-images.githubusercontent.com/62887048/109308209-a0223f00-7839-11eb-8fd4-1a3d7a71f545.png)
![image](https://user-images.githubusercontent.com/62887048/109308258-ad3f2e00-7839-11eb-814a-a7a6fd4b0d49.png)

**Comment by calremmel** [comment]
This is fixed as of yesterday with standardized lat/lng coordinates at Country level for aggregation pipeline.
