### ISSUE TITLE
Make a Comprehensive Case Schema

### ISSUE THREAD

**Issue by fojackson8** [globaldothealth/list#1622]
Cases are ingested into the database as JSON objects, which have a set of fields (keys) populated relating to case demographics, location, dates etc. The specific fields that are accepted as input are defined with a schema. We need a comprehensive documentation of this schema. 

We need a list of all accepted fields pertaining to a case. Each field has a key and a value. We need the precise spelling of the key, a description of what this field should contain, and the form of the expected value. Some fields are expecting a list, others a boolean, others accept any string. It would be great to have this explicitly stated. An example of a case with all fields correctly populated would be a big help.

We almost have this on [these API schema docs](https://curator.ghdsi.org/api-docs/#/Case). **This just needs to be updated and moved somewhere else**.

This may also be useful for responding to user questions.

**Comment by iamleeg** [comment]
The canonical URL for the swagger doc is https://data.covid-19.global.health/api-docs/ though currently I'm having bad times trying to access it. Looking at the doc it pulls from I see that the variant info isn't there so I've [added that](https://github.com/globaldothealth/list/pull/1627), please comment on the PR if there's any other useful info missing :+1:

**Comment by calremmel** [comment]
@fojackson8 @iamleeg Does this still need to be moved somewhere else, or are the updated Swagger docs sufficient?

If this needs to be accessible elsewhere, perhaps it could be matched with the data dictionary somehow. That might be confusing for folks who don't understand the difference between the MongoDB schema and the exported .csv format, but if it is of interest, perhaps you can discuss whether it ought to be a component in the UI, simply another file included with downloads, etc.
