### ISSUE TITLE
Staging area to better test parsers locally

### ISSUE THREAD

**Issue by fojackson8** [globaldothealth/list#1624]
We write [parsers](https://github.com/globaldothealth/list/tree/main/ingestion/functions/parsing) to translate source datasets to fit our database schema. We test these by spinning up a replica of the software stack locally in a docker container, then invoking the retrieval and parsing lambda functions (process described [here](https://github.com/globaldothealth/list/tree/main/ingestion/functions)). Currently the only parser feedback we get are error messages if it doesn't send the correct info. Anything that doesn't break the schema will pass this check, even if the data makes no sense.

Crucially, mapbox geocoding is done after we send off parsed cases, so we have no way of knowing if case geocoding is working until we deploy the parser (and see all COVID-19 in Colombia is geocoded to one street in Spain).

It would be great to have a staging area, where we can run a parser on a country dataset, and see how the resulting parsed cases look on a local replica of the front-end. If this is too hard, some kind of map which shows how these cases land after geocoding would be good. This is most useful to see how cases are geocoded, but the distribution of other case details would also be useful to see, for sensechecking purposes.

**Comment by jim-sheldon** [comment]
Related to #1932

**Comment by jim-sheldon** [comment]
We could also use the local end to end testing environment to see if/when mongo fails to import parsed data, on top of geocoding errors.

**Comment by jim-sheldon** [comment]
Blocked by: https://github.com/globaldothealth/list/issues/2279

**Comment by jim-sheldon** [comment]
Going to close this one, as it appears to be treatable as two separate issues. We do have a local testing area for parsers now, so we can run parsers against a replica of our stack deployed locally, but we do not have the map as a part of that.
I created https://github.com/globaldothealth/list/issues/2279 to capture this work.
