### ISSUE TITLE
Update Documentation for Transition

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1654]
Over the next week, I would like to make sure that anything that I have worked on that isn't documented becomes so!

In the interests of making sure that I do not miss anything important, I would like to solicit input on anything that needs to be covered.

**Current List:**

- AWS Practices
- Possible improvements to AWS Practices
- Export Scripts for Map and Downloads
- Logging and troubleshooting roadmaps

**Comment by iamleeg** [comment]
Anything we need to know about managing GitHub secrets?
