### ISSUE TITLE
Empty / corrupted file in data download

### ISSUE THREAD

**Issue by beoutbreakprepared** [globaldothealth/list#1734]
I downloaded the "Download Full Dataset" global.health dataset today from https://data.covid-19.global.health/cases onto my Windows system. Using 7Zip I was only able to extract an empty csv called "globaldothealth_2021-03-22.csv"

Is anyone else able to download the correct file and reduce the possible problems to just me!

**Comment by iamleeg** [comment]
Don't know whether just you, temporary problem, or something else but I just tried the same and got 8.87GB of CSV, alongside the data dictionary and terms.

**Comment by beoutbreakprepared** [comment]
Ok i'll try again - but good to confirm that it isn't globally blank
