### ISSUE TITLE
Variable demographic.ethnicity not formatted correctly

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1739]
In downloaded file:

Variable 'demographics.ethnicity' doesn't contain the ethnicity but rather values related to the gender ('female,' 'male'); that seems to be a data cleaning issue.

**Comment by joe-brilliant** [comment]
per our call @iamleeg to follow up with @Mougk for details when we revisit this issue

**Comment by Mougk** [comment]
If there are no cases of this in our data we can consider this case closed.
