### ISSUE TITLE
10MB attachment limit in SES

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#1762]
**Describe the bug**
When #1760 is deployed we will have asynchronous fetch-and-email of large filtered downloads. This uses Amazon SES, which has a 10MB limit on message size.

@jim-sheldon suggested storing large downloads on S3 and sending a pre-signed link via email, instead of sending a CSV attachment, to work around this issue. It's probably also worth careful thought to consider whether the worker should be making such large requests, as they put memory pressure on mongodb, the data service, and the curator service.

**Comment by abhidg** [comment]
Should be fixed on merging #1625 which adds temporary file storage in S3.
