### ISSUE TITLE
variantOfConcern field is completely null when downloading full dataset from website

### ISSUE THREAD

**Issue by kylewest520** [globaldothealth/list#1844]
Is there some other way of pulling the data that will result in populated data for the variantOfConcern field?

**Comment by iamleeg** [comment]
Did we have any non-GISAID data with VoC field populated at the time of the report? If not, this is expected behaviour.

**Comment by iamleeg** [comment]
```
MongoDB Enterprise covid19-map-cluster01-shard-0:PRIMARY> db.cases.findOne({variant:{name:{ $exists: true, $ne: null}}})
null
```

There are no records with the variant field in the database even now, this is expected behaviour.
