### ISSUE TITLE
Fix Lambda timeout on dataset compression in data export

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1846]
Data export is broken due to `sam deploy` failing

**Comment by abhidg** [comment]
We have now hit AWS Lambda 15 min limit, so have to move this to Batch as well :/

**Comment by abhidg** [comment]
OK, so I've come across a solution, which will address the issue of large data files as well (the current unzipped dataset is 10 GB!). Thoughts @iamleeg @jim-sheldon @Mougk @joe-brilliant?

Previously we had this structure:
```
latestdata.tar.gz/
├── citation_data.rtf
├── data_dictionary.rtf
└── latestdata.csv
```

I'm proposing to move to this:

```
latestdata.tar/  # no gzip, files are compressed inside
├── citation_data.rtf
├── data_dictionary.rtf
└── cases-1-of-N.csv.gz
└── cases-2-of-N.csv.gz
.
.
└── cases-N-of-N.csv.gz
```

This has the advantage of being
* Easy to implement (just modify 03-parse to write a csv.gz, and 04-combine to output a tar)
* Should scale much better due to concurrency
* Individual files are smaller making them easy to open

**Comment by jim-sheldon** [comment]
Short-term, I agree.

Longer-term, moving to Batch and keeping the original format seems preferable; decompressing and opening many files seems onerous for a user.

**Comment by abhidg** [comment]
Agree on this being more onerous, though we would have to split CSVs anyway due to the large file size. I just did a `gzip --best` on a 60 MB cases-X-of-Y CSV which turned it into 2.5 MB, given that the main bottleneck after this change is downloading files to EFS (as we won't be compressing in combine), and 10 GB files took 4 minutes, that would give us 25 GB for 10 minutes (keeping 5 min for tarring it). This corresponds to ~10240 chunks, so more than a billion records!

**Comment by iamleeg** [comment]
The only major question I have about splitting is whether to split by number (easy enough) or some other dimension like country. That could actually end up increasing the running time significantly.

Minor question is whether we can nudge people toward trying to do anything more sensible than opening tens of GBs in Excel. Could we host a mybinder and let people play with the data in pandas/R as an alternative or complement to downloading?

**Comment by Mougk** [comment]
+1 on mybinder. Exploring data in R/pandas in a simple way would be great for users.

splitting by country or splitting by date both good. if so, names of files should either show country name or/and start/end dates.

**Comment by abhidg** [comment]
So using this method the tarball is being generated as `latestdata.tar` with 297 files, each corresponding to a chunk of 100000. Is there a easy to filter on date limits, as the date is not a single field but contained within a list? I can do the country breakdown, might have to special case USA as that itself will be 5 GB uncompressed.
