### ISSUE TITLE
Allow ADI retrieval from a source on S3

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#1851]
**Is your feature request related to a problem? Please describe.**
We have secret squirrel data sources that we're not allowed to share publicly like GISAID. But to ingest from them, they currently have to be visible at a publicly-available HTTP[S] URI, which means we have to share them publicly. 

**Describe the solution you'd like**
We should be able to point to an S3 resource as a source and have the retrieval function fetch data from there to trigger the parser.

**Describe alternatives you've considered**
Anything that is access-controlled where we can store the authentication secrets secretly(!) would work, and S3 is probably the easiest because we already use it in the ADI workflow so the access issue has already been solved.

**Comment by abhidg** [comment]
Works great! Tested on dev, but should work on prod as well as ingestion code is always pulled from main.
