### ISSUE TITLE
Add terraform scripts

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#1870]
We should add terraform scripts to our system to create a new QA environment, modify existing environments (including local /w localstack), and allow for others to stand up their own application instances.

TBD:
do we couple terraform with ansible?
how to support multiple cloud platforms?
how to support local deployment?

**Comment by iamleeg** [comment]
Let's do this as part of #2186

**Comment by jim-sheldon** [comment]
TF state files now live in their own repo

**Comment by jim-sheldon** [comment]
Partner infra spun off into https://github.com/globaldothealth/list/issues/2412
