### ISSUE TITLE
Username and password authentication

### ISSUE THREAD

**Issue by maciekz1996** [globaldothealth/list#1876]
Replace current authentication system with standard username / password flow.

**UI**
- [x] Create login form on landing page with error alerts (email, password, forgot password button, sign in button, signup button)
- [x] Create signup form with error alerts (email, password, repeat password, ...)

**API**
- [x] Create login logic using Passport
- [x] Create sign up logic using Passport
- [x] Add "Forgot password" functionality

**TESTS**
- [x] Fix failing tests
- [x] Create new tests (integration and E2E) for auth system

**Comment by maciekz1996** [comment]
Hi @joe-brilliant This feature is almost ready, we would need some content for the emails that are being sent to the users:

- Email that contains link for resetting the password. Current content: `Here is your password reset link: link goes here`
- Email after successful password change. Current content: `Your password was changed successfully`
- Welcome email after signing up (This email is the same as the one used with previous auth system, so I believe no changes are required here)

Just for reference, content of the welcome email:

```
Hello maciej.zarzeczny@htdevelopers.com,

Thank you for registering with Global.health! We're thrilled to have you join our international community and mission to advance the global response to infectious diseases through the sharing of trusted and open public health data.

Here are a few things you can do:

Filter and export G.h Data containing detailed information on over five million anonymized COVID-19 cases from over 100 countries.
Explore the G.h Map to see available case data visualized by country, region, and coverage. You can also find currently available line-list data on variants of concern which will be updated regularly.
Check out our FAQs for more information on our platform, process, team, data sources, citation guidelines, and plans for the future.
Get involved! G.h is being built via a network of hundreds of volunteers that could use your help. If you're interested in joining us, please fill out this form.
Connect with us on Twitter, LinkedIn, and GitHub for the latest news and updates.
If you have any questions, suggestions, or connections don't hesitate to email us and a member of our team will be sure to follow up.

Thank you again for your interest and support! We hope G.h proves valuable to your work and look forward to hearing from you.

The G.h Team
```

**Comment by joe-brilliant** [comment]
Hi @maciekz1996 @marlenachroscicka 

For password reset: 

From: Global.health Team (info@global.health)
To: (user email)
Subject: Password Reset Request
Body: 

Hello (user email),

Here is a [link](url) to reset your password on Global.health. If you did not initiate this request, please disregard this message.

Thanks, 

The Global.health Team

--

For Password confirmation:

From: Global.health Team (info@global.health)
To: (user email)
Subject: Password Change Confirmation
Body: 

Hello (user email),

Your Global.health password has been changed. If you did not initiate this request or are unable to access your account, please respond to this email and we'll be happy to assist.

Thanks, 

The Global.health Team

**Comment by maciekz1996** [comment]
Thank you @joe-brilliant  for the content above, it is already updated and PR was created to merge those changes. 

There is just one more email that was created recently after suggestion from Graham which is being sent to users who are registered using Google and try to reset their password as if they were registered with standard email/password auth. Current content of this email:

`We were asked to reset your password on Global.health, but you are registered with your Google account. 
If you requested the password reset, then please try again, this time using the "Sign in with Google" button on the global.health portal.  Otherwise, no further action is needed.`

Please let me know if I should somehow update this content as well

**Comment by joe-brilliant** [comment]
@maciekz1996 @iamleeg looks good, let's just add the standard email lang:

From: Global.health Team (info@global.health)
To: (user email)
Subject: Password Change Request

Hello (user email),

You requested to reset your password on Global.health, but you are registered with your Google account. If you requested the password reset, please try logging in using the "Sign in with Google" button and resetting your password via your Google account if necessary. If not, no further action is needed.

Thanks,

The G.h Team
