### ISSUE TITLE
Location autocomplete doesn't work in case details

### ISSUE THREAD

**Issue by marlenachroscicka** [globaldothealth/list#1877]
Autocomplete feature in data portal when adding new line list case (Location section) is not working. In the console I see that each request ends up with 500 status, it seems that the error cause is located in geocoding service and more precisely `list/geocoding/location-service/src/app/geocoder_suggester.py`. The request that is being sent looks like this: `GET http://localhost:3002/api/geocode/suggest?q=united` for example. Below is the stack trace containing error:

<img width="1285" alt="Screen Shot 2021-05-27 at 11 29 57" src="https://user-images.githubusercontent.com/44740625/122431498-cf012400-cf94-11eb-9f78-1eb32b7bd8fa.png">

**Comment by iamleeg** [comment]
This is working now, closing the issue
<img width="792" alt="Screenshot 2021-12-16 at 16 04 14" src="https://user-images.githubusercontent.com/237254/146406355-8ff8b837-b334-47e3-bc4f-c0769a81608b.png">
.
