### ISSUE TITLE
MongoDB schema migrations

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#1880]
We need to add schema migrations to our data and curator services to adapt to changing requirements.

This should include moving the database scripts from the data service folder to a shared, common one and coordinating migrations for the data and curator services. It may include replacing the `setup-db` script with an initial schema migration.

Doing this should allow for fixing [1875](https://github.com/globaldothealth/list/issues/1875).

**Comment by iamleeg** [comment]
[node-migrate](https://github.com/tj/node-migrate) looks like a good option.
