### ISSUE TITLE
Bump k8s version

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#1889]
We should run 1.20 in EKS as 1.16 support ends July 25
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar

**Comment by iamleeg** [comment]
Amazon are ending support on Sept 27th, we should do this as a matter of priority now.

**Comment by iamleeg** [comment]
You can only bump one version at a time, so I've moved to 1.17 and created #2153 to track the next one (I think if we do one at a time every 6-8 weeks we'll move safely _and_ catch up with Amazon's schedule, we're not desperate to use any new features in k8s we just need to not fall off the back of their support cycle). I also created #2154 and commented on #1872 to provoke discussion on other Kubernetes-related infra issues.
