### ISSUE TITLE
Wordpress webpage(s) for Data deep dive

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1896]
Per @Mougk:

"We have been working on a data deep dive section to support interpretation of our line list data from specific countries. The main aim is to make it more intuitive for the user of our data and those who come to our website to understand the depth of the platforms information. We have started with Peru which is now working well coming into the DEV environment (see description of dataset here: https://docs.google.com/document/d/1Gq78lo7SZzflIKpTtmvovGuAie2roCEQnT7m5RaX0RU/edit; finalising this today). We will go and add more as we go along. Design and Website team: We need to find the best way to float this information to the users coming to our website. My idea was to have a designated 'Data Deep Dive' section which is accessible via the main website and via the 'data' tab. Looking forward to discussing this later on our product call"

<img width="641" alt="screenshot_2021-05-27_at_10 15 44" src="https://user-images.githubusercontent.com/74671973/120565901-eb149b00-c3c2-11eb-9608-f0ed52c8af61.png">

**Comment by rkassa** [comment]
Ready for review here:
https://dev-globalhealth.pantheonsite.io/peru/

(@joe-brilliant @Mougk )

**Comment by Mougk** [comment]
1. Map v nice and moving the table to be horizontal too.  
2. Link to 'go to peru data' does not work.
3. Links in text (for example 'Open Data Commons Attribution License' in the 01 section not visible enough. Perhaps change colour to blue?
4. Authors look nice. Add remaining ones pls
5. Add Go to Peru Map on 05.
6. Add link behind map (top) to direct to peru viz?

Other than that. Super!

**Comment by Mougk** [comment]
Align directly below.

Perhaps adjust colour and increase level of transparency


<img width="290" alt="Screenshot 2021-06-08 at 10 35 25" src="https://user-images.githubusercontent.com/8478551/121161811-43292280-c845-11eb-8216-e18a6ba0ddaf.png">

**Comment by abhidg** [comment]
This is now live 🎉
