### ISSUE TITLE
Create info@global.health email address and add DKIM signature to automated emails.

### ISSUE THREAD

**Issue by maciekz1996** [globaldothealth/list#1897]
Some users have trouble receiving automated emails containing verifications codes for authentication. The reason for this is that currently used gmail address doesn't have DKIM set up.

- [x] Create info@global.health email address
- [x] Substitute currently used email with the new one in AWS SES
- [x] Add DKIM signature to the new email

**Comment by jim-sheldon** [comment]
The BCH team added DNS entries to the domain as requested. I think we can close this.
