### ISSUE TITLE
Automate ingestion for relative date ranges

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#1898]
Allow for restricting automated ingestion to specific date ranges. We can currently do it manually via `-s` and `-e` flags in `aws.py submit`, but this provides absolute (we want relative) date ranges, and we can only run it from a local machine.

This is to avoid cases like this where the data set is large and we don't want to ingest all the data every day. It will also become essential when we come to setting up sources with no UUIDs as we will want to restrict ingestion to specific dates to avoid duplication.

**Comment by abhidg** [comment]
This is already present, ingestion should pick up the date range set in the curator UI. If the date range field is unset, the ingestor will try to get the entire data.
