### ISSUE TITLE
Swap out info@global.health for ghdsi.info@gmail.com across site / code base / social accounts

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1933]
Running list of instances:

- [x] Contact us footer
- [x] FAQ
- [x] TOU / Privacy Policy
- [x] Get Involved webform submission
- [x] User registration / 
- [x] Social media accounts
- [x] GitHub

**Comment by rkassa** [comment]
@joe-brilliant 
Everything that's checked off on that list is done on dev.  The remaining items are ones I don't either have access to, or would concede to @maciekz1996 to implement (the user registration emails)

**Comment by joe-brilliant** [comment]
@rkassa is this hooked up to Get Involved yet?

**Comment by rkassa** [comment]
@joe-brilliant it is, and we've confirmed, right?

**Comment by joe-brilliant** [comment]
I'll check these and all the dev ready issues, thanks @rkassa

**Comment by joe-brilliant** [comment]
@jim-sheldon suggest we move to Proxy if this is pending filtered Data DL via email

**Comment by jim-sheldon** [comment]
We do not use emails for filtered downloads anymore. I think we can close this.
