### ISSUE TITLE
Improved SEO for "global.health"

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1935]
When "global.health" is entered into a seachbar vs. an address bar (often merged UI on mobile browsers), with or without quotation marks, it does not appear anywhere in first page of results (or the first few hundred)

For regular users or return visitors this issue may be obscured due to the domain being cached, but for new users, "global.health" is almost impossible to find if entered as a search query. 

Ideally we can find opportunities to improve our SEO with website metadata and/ or through strategies with the Google team to get above the fold initially and the top result eventually.

Some underlying issues may be related to the relative newness of the .health domain, and possibly search engines interpreting "global.health" as a typo for "global health"

A few examples:

https://www.google.com/search?q=global.health&rlz=1C5CHFA_enUS886US886&sxsrf=ALeKk00[…]KEpIBBzAuNS41LjGYAQCgAQGqAQdnd3Mtd2l6yAEKwAEB&sclient=gws-wiz

https://duckduckgo.com/?q=global.health&t=hd&va=u&ia=web

**Comment by joe-brilliant** [comment]
Initial list of tags to add to header metadata:

"globalhealth"
"global health" 
"globaldothealth"
"global.health"
"G.h"
"global."
".health"
"global"
"health"
"dot"
"public health"
"data science"

**Comment by rkassa** [comment]
Re-indexing .... 

<img width="1247" alt="Screen Shot 2021-06-19 at 1 10 17 AM" src="https://user-images.githubusercontent.com/201428/122631650-24275d80-d09b-11eb-89ba-e0b8da0be1a3.png">

**Comment by joe-brilliant** [comment]
Quantum leap improvement already, nice work @rkassa and team! Moved this to Proxy milestone so we can continue to track and optimize 

https://www.google.com/search?q=global.health&sxsrf=ALeKk02SayODbLZLIW8CN8MUqChRrZ3pgQ%3A1625169251348&ei=Yx3eYOPfFMyt0PEP4qeGwAw&oq=global.health&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBggAEAcQHjICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAOgcIABBHELADOgQIABAeSgQIQRgAUMk2WM8-YJRBaAFwAngAgAFKiAHAAZIBATOYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=gws-wiz&ved=0ahUKEwijnbSf08LxAhXMFjQIHeKTAcgQ4dUDCA4&uact=5
