### ISSUE TITLE
Make parallel ingestions possible

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1937]
We can make batchUpsert more resilient by adding more instances or lowering memory usage.

An alternative is to use mongoimport to insert/upsert cases from JSON. 
Ingestors can convert to our schema, write to JSON and upload to S3. This will enable parallel runs, with the actual ingestion being done in a separate process.

This functionality would depend on validation locally so that mongoimport doesn't give validation errors.

**Comment by jim-sheldon** [comment]
This would also improve ingestion speed by 10x
