### ISSUE TITLE
Add substack link to persistent homepage top nav

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1944]
Link: https://globaldothealth.substack.com/ 

Location: could go next to (or replace) "Get Involved" in upper right corner

Title: "Blog" or "Newsletter"?

**Comment by rkassa** [comment]
@joe-brilliant @Mougk 
Ready on dev as "Blog":
https://dev-globalhealth.pantheonsite.io/

**Comment by joe-brilliant** [comment]
@rkassa looks great! We can push to prod and close

**Comment by rkassa** [comment]
On prod ✅
