### ISSUE TITLE
Add "Featured on Product Hunt" tile to website footer

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1945]
Code for darker version: 

<a href="https://www.producthunt.com/posts/global-health?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-global-health" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=286224&theme=dark" alt="Global.health - Access data about 10M+ anonymized COVID-19 cases | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>

`<a href="https://www.producthunt.com/posts/global-health?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-global-health" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=286224&theme=dark" alt="Global.health - Access data about 10M+ anonymized COVID-19 cases | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>`

**Comment by rkassa** [comment]
@joe-brilliant 

Ready in footer here:
https://dev-globalhealth.pantheonsite.io/

**Comment by joe-brilliant** [comment]
@rkassa looks great! Lets push to prod with the Blog link and any SEO tags and close this out

**Comment by rkassa** [comment]
On prod ✅
