### ISSUE TITLE
Automatic scheduling of ingestion

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#1951]
Currently we have a UI for curators to decide the frequency of scheduled updates to ingestion data, which is pretty weird because it exposes details of how you configure jobs in AWS Batch. It also has email notifications to the source editor which have been broken for a long time.

Thing is, we don't need any of that, because we have a simple policy based on the size of the source and whether the upstream data has stable identifiers. We could make the whole thing easier to use by automating the choice of schedule.

**Comment by jim-sheldon** [comment]
Relates to https://github.com/globaldothealth/list/issues/1927
