### ISSUE TITLE
Table of Data and Map URLs for each country for HDX integration

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1953]
HDX / Humdata has agreed to a dynamic integration linking to our dataset (vs. hosting static datasets on their platform). One way they and their users typically organize/explore their data is by country, so one solution could be to create pages/sections for each country we cover on our HDX org page  https://data.humdata.org/organization/globaldothealth

This could be a simple as a CSV/XLS file (org GitHub page) of Map and Data URLs for each country (perhaps with periodically updated stats on cases, coverage, last update, and, data deep dives, where available) that we either provide to them or set up ourselves, possibly starting with a targeted list of countries where we a) have meaningful data/coverage and/or b) are of most interest and value to HDX and their community

E.g.

**Peru**
https://data.covid-19.global.health/cases?country=Peru
https://map.covid-19.global.health/#country/PE
https://global.health/deepdive/peru
1,726,000 cases
Coverage 85%
(1,726,000 out of 2,019,716)

**Comment by joe-brilliant** [comment]
[Global.health - Humanitarian Data Exchange.pdf](https://github.com/globaldothealth/list/files/6678373/Global.health.-.Humanitarian.Data.Exchange.pdf)

PDF of the fields for data submission ^

**Comment by joe-brilliant** [comment]
[Contribute Metadata - Humanitarian Data Exchange.pdf](https://github.com/globaldothealth/list/files/6678471/Contribute.Metadata.-.Humanitarian.Data.Exchange.pdf)

PDF of fields for metadata submission (alternate option) ^

**Comment by joe-brilliant** [comment]
@abhidg @iamleeg @abhidg @Mougk wondering if maybe we already have a dynamic page on GitHub with this info per country, or maybe worth putting together if it's a light lift for this? Could be of use for future inquiries/partnerships/intergrations and to include in our FAQs etc

**Comment by abhidg** [comment]
Other than the deepdives (which aren't there for every country yet), the info is in the covid-19-aggregates bucket. We can export that to a CSV or make a nice UI on the website.

**Comment by joe-brilliant** [comment]
Sounds perfect thanks @abhidg !

**Comment by abhidg** [comment]
@joe-brilliant a CSV is being generated at https://covid-19-aggregates.s3.amazonaws.com/country/latest.csv daily. It has information on all countries in our dataset with URLs. The deepdives are not present, but we could send that manually.

**Comment by joe-brilliant** [comment]
Thanks @abhidg !
