### ISSUE TITLE
Admin level 2 and 3 boundaries on regional map

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#1956]
Currently, when zooming into the regional view (for example: https://map.covid-19.global.health/#region/MX) it is very hard to identify the area (boundary, polygon area) where the cases have been reported. Adding admin level 2 and potentially 3 boundaries could help that (we only show state boundaries at the moment).

- [x] Configure Mapbox boundaries

**Comment by joe-brilliant** [comment]
+ @sergioloporto and @maciekz1996 in case they might be able to help out
