### ISSUE TITLE
Filtered Data DL's should include data dictionary, citation guidelines, and results/DOI metadata

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1987]
When DL'ing smaller data sets (e.g. Zambia as CSV, example attached), the DL'd file is not zipped with other files in full data set DL. Suggest all data DL's are zipped with data dictionary, citation guidelines, and some descriptive metadata (either in filename or in enclosed file) with information on the applied filters, enclosed results, and most recent database DOI information 

[gh_2021-07-06.csv](https://github.com/globaldothealth/list/files/6778701/gh_2021-07-06.csv)

**Comment by jim-sheldon** [comment]
Blocked on having a proper data dictionary.
Can use citation file [here](https://github.com/globaldothealth/list/blob/main/data-serving/scripts/export-data/functions/04-combine/citation_data.rtf).

**Comment by joe-brilliant** [comment]
Thanks @jim-sheldon looping in @abhidg and @iamleeg

**Comment by abhidg** [comment]
Depends on #1610

**Comment by joe-brilliant** [comment]
per @jim-sheldon we may need to break this out into 2 issues

**Comment by jim-sheldon** [comment]
Closing this after breaking out into two issues for cached and non-cached downloads.
