### ISSUE TITLE
Encountering 504 timeout error when attempting to DL Brazil data on dev

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1988]
When attempting to DL filtered results for Brazil as a country on Dev (either using Filter UI or Map), I did not receive an email link and when I requested to DL 100k rows received a 504 error message

https://www.dropbox.com/s/u45l2l0nq6zutu6/Screen%20Shot%202021-07-06%20at%2012.54.02%20PM.png?dl=0

**Comment by iamleeg** [comment]
This is something that can be mitigated by scaling the mongoDB cluster: manually scaled it to M60 tier ($4/hr) and this problem went away. I think this is only a short term fix because as the data quantity increases we will have to pay even more. I'll write up the actual fix in a different issue.

**Comment by abhidg** [comment]
Not getting 504 timeouts anymore, but filtered downloads fails.
