### ISSUE TITLE
Website fine tuning

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1990]
- [x] Remove Product Hunt tile in footer
- [x] Revert social icons to prior design
- [x] Align text below Substack sign up form in footer
- [x] Re-optimize and test formatting on mobile browsers
- [x] Increase res of G.h logo in footer and align social icons

**Comment by rkassa** [comment]
All set on dev
https://dev-globalhealth.pantheonsite.io/

closing this, @joe-brilliant  ✅
