### ISSUE TITLE
Argentina deep dive should be linked to /deepdive/argentina

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1999]
https://global.health/deepdive/argentina redirects to https://global.health/argentina

**Comment by joe-brilliant** [comment]
@rkassa please close when ready

**Comment by rkassa** [comment]
Done on dev 
https://dev-globalhealth.pantheonsite.io/deepdive/argentina

Please test after flushing all local caches or in incognito

Closing this @joe-brilliant
