### ISSUE TITLE
Links to filtered Data results when clicking on http://dev-map.covid-19.global.health/ should to to respective countries / regions on Dev

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2012]
Currently clicking "see more data" on "http://dev-map.covid-19.global.health/#country/CZ for example currently goes to "https://data.covid-19.global.health/cases?country=%22Czech%20Republic%22. It should go to https://dev-data.covid-19.global.health/cases?country=%22Czech+Republic%22

Link to "G.h data" in upper right corner should also go to https://dev-data.covid-19.global.health/cases

**Comment by abhidg** [comment]
related: #1631
