### ISSUE TITLE
Environments variables in data and map applications (placeholder)

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2013]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abhidg** [comment]
Environment variables for data are set in SERVICE_ENV. The current map is built statically, and the environment can be specified at build time using the deploy script. Is there anything needed for the current static map build? @sergioloporto @maciekz1996 @rkassa

**Comment by joe-brilliant** [comment]
Closing with @abhidg's blessing
