### ISSUE TITLE
@global.health emails and signatures for the team! 

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2017]
will create and add a Gsheet with folks preferred handles and backup emails to get set up

Two subtasks

- [ ] Emails configured based on forthcoming Gsheet @jim-sheldon 

- [ ] Stylized email signatures @rkassa

**Comment by joe-brilliant** [comment]
Proposed naming convention firstname.lastname@global.health

**Comment by Mougk** [comment]
Either 'firstname.lastname@global.health' or just 'firstname@global.health'. I let you masters decide.

**Comment by joe-brilliant** [comment]
Our account has been provisioned by Google. We have up to 100 free accounts. Will work with @jim-sheldon on getting accounts set up next week

**Comment by joe-brilliant** [comment]
closing and moving this to smartsheet
