### ISSUE TITLE
Define validation error threshold for upload to be SUCCESS or ERROR

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2018]
Any batch having a validation error causes the entire upload to have status ERROR. With the new prune-uploads functionality, we don't ingest any upload that has status other than SUCCESS. We should decide on a validation error threshold for the entire upload (such as 10%), below which, the upload will be considered a SUCCESS. Note that under the previous approach, we considered any amount of upload as valid, since there was no intermediary marking / pruning before the data was visible in the line list.

Alternatively, we could define another state called MOSTLY_SUCCESS which would indicate validation errors below a certain threshold, making it visible in the uploads list, but which will be treated the same as SUCCESS by prune-uploads.

Thoughts @MougK @AnyaLindstromBattle @fojackson8 @joe-brilliant  @jim-sheldon @iamleeg?

**Comment by iamleeg** [comment]
I think you're right that we need to move away from having a binary success/failure state, as we're deliberately being as tolerant of errors as possible in the upload/upsert stage. I would favour reserving ERROR for catastrophes like the source data was missing or completely uninterpretable. In other cases, the upload should report SUCCESS and include the total number of cases, #updated, #inserted, #error and then for non-UUID sources the pruning/cleanup script gets to decide, maybe based on some configuration, whether the success was successful enough to replace the existing data.

This also points to having some warning emanating from the non-UUID cleanup script if it has run for N days and not found an upload it considered successful enough to use.
