### ISSUE TITLE
map: Some countries appear on sidebar multiple times

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#2028]
Some countries appear on the sidebar multiple times.

A previous version of the data did have multiple entries for countries due to a bug of mine. However, in the most recent version it is fixed - not sure if there is something residual.

![image](https://user-images.githubusercontent.com/40274075/109046147-6e2aa480-76a2-11eb-9630-a144bfa925ef.png)

**Comment by abhidg** [comment]
Fixed in prod
