### ISSUE TITLE
Strongcat initial release

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2039]
- [x] Disable automated ingestion
- [x] Set list: true for production database
- [x] Test prune uploads on dev
- [x] Create 1.7-stable branch and push
- [x] Tag 1.7.0 and deploy
- [x] Set hasStableIdentifiers for UUID sources
- [x] Deploy export service
- [x] Move notes to restrictedNotes for Brazil
- [x] Turn on prune uploads via GitHub Actions
- [x] Enable automated ingestion

**Comment by joe-brilliant** [comment]
Thanks for documenting this @abhidg! Maybe this can be a simple format for our release notes/verification moving forward? cc: @jim-sheldon
