### ISSUE TITLE
Track data downloads

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2042]
We should keep a count of filtered downloads, and track them by user.
This will help us with analytics and setting up a cache.

**Comment by joe-brilliant** [comment]
Thanks for getting this started @jim-sheldon ! cc @iamleeg @abhidg @Mougk

**Comment by joe-brilliant** [comment]
@jim-sheldon @abhidg @iamleeg @Mougk I moved this into Strongcat for now just to ensure we have this tracking up when we launch and promote the feature. Happy to discuss further

**Comment by jim-sheldon** [comment]
More precisely, we should add tracking of queries used in filtered downloads, e.g. `{country:France}`.
We already keep count of downloads by each user.

**Comment by jim-sheldon** [comment]
Filtered data downloads now stored in the database
