### ISSUE TITLE
Password reset request email sent from ghdsi.info@gmail.com instead of info@global.health

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2048]
https://www.dropbox.com/s/0gyk0ylkzbr5p1n/Screen%20Shot%202021-07-29%20at%201.34.30%20PM.png?dl=0

**Comment by maciekz1996** [comment]
@joe-brilliant I checked this issue and it seems that there is wrong value set in environment variables on dev. When I run the app locally and request password reset email then it is being sent from new email address, but on dev website it still uses old email. So my guess is that there has to be old email provided during deployment process, however I don't know where this should be changed. Locally this variable is located in `list/dev/.env` file and is called `EMAIL_USER_ADDRESS`. 

@abhidg Could you advise where this variables should be changed on dev and production?
