### ISSUE TITLE
Minor formatting issues on Data registration page

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2049]
- [ ] "SignUp form" should be "Sign up form" 

- [ ] there is an extra blue border around the Google logo in "Sign up with Google" 

https://www.dropbox.com/s/ghyxx23312sm1j8/Screen%20Shot%202021-07-30%20at%204.34.23%20AM.png?dl=0

**Comment by sergioloporto** [comment]
@joe-brilliant  you mean this border?

![image](https://user-images.githubusercontent.com/51946947/127650379-0e1172ff-8aeb-4eaf-9b22-be13938a008d.png)

**Comment by joe-brilliant** [comment]
@sergioloporto yes, here's how it looks on Sign Up, missing a few borders

https://www.dropbox.com/s/vihydgid2i3kzo0/Screen%20Shot%202021-07-30%20at%207.03.11%20AM.png?dl=0

It should like the same as it does on Sign in

https://www.dropbox.com/s/ufsiescei3mtks1/Screen%20Shot%202021-07-30%20at%207.02.58%20AM.png?dl=0
