### ISSUE TITLE
Data Deep Dives: Add Brazil and fix Argentina URL

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2079]
- [x] Brazil Gdoc https://docs.google.com/document/d/1NKwWUJpbo7Lxxdd3nOxG9W1dlBj0SWsggJVFDVGm_6U/edit?usp=sharing  > New URL: https://www.global.health/deepdive/brazil
 
- [x] Argentina URL should also resolve to https://www.global.health/deepdive/argentina (currently resolves to https://www.global.health/argentina/ from homepage nav

**Comment by abhidg** [comment]
Argentina issue is being tracked at #1999

**Comment by rkassa** [comment]
That's correct @abhidg 
And Argentina is all set on dev: https://dev-globalhealth.pantheonsite.io/deepdive/argentina

**Comment by rkassa** [comment]
Content for Brazil is added on dev:
https://dev-globalhealth.pantheonsite.io/deepdive/brazil/

**Comment by abhidg** [comment]
@rkassa thanks! could you push all the dev changes to prod?

**Comment by joe-brilliant** [comment]
@rkassa these can be pushed to prod with this change from @AnyaLindstromBattle on Brazil DDD 

'lookup table' carries the link in one instance but only 'lookup' in another (see Q2)

**Comment by rkassa** [comment]
on prod. closing
