### ISSUE TITLE
Find out if MongoDB SERVER-58936 affects us

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2095]
From https://jira.mongodb.org/browse/SERVER-58936?utm_campaign=Int_EM_Unique+index+constraints_WW_08_21&utm_medium=email&utm_source=eloqua&utm_term=MongoDB+Advisory%3A+Unique+index+constraints+may+not+be+enforced+in+MongoDB+4.4.7%2C+5.0.0+and+5.0.1:

For collections that have additional unique indexes apart from the default _id index, SERVER-56509 introduced a regression which may result in documents being inserted that violate those unique indexes’ uniqueness constraint. These documents will be replicated successfully from the primary to the secondaries.

If this bug is exercised and multiple documents exist in a collection violating a unique index constraint, subsequent delete operations using the affected unique index will only modify half (rounding up) of the affected documents being targeted per execution. This is a result of internal optimizations that rely on uniqueness. Query and update operations are not affected and will return all targeted documents.

**Comment by joe-brilliant** [comment]
per our call today @iamleeg let's follow up with @abhidg after he gets back

**Comment by iamleeg** [comment]
This doesn't affect us. It's only versions 4.4.7, 5.0.0 and 5.0.1. Our production cluster is on 4.2.17 (before the bug was introduced) and dev is on 4.4.10 (after it was fixed). There's a separate convo about updating the prod DB, but we dodged this issue.
