### ISSUE TITLE
Hide VoC data on Map application for time being

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2102]
While we await API access and more direction on deeper integrations with GISAID, let's disable p1 and b1351 views from G.h Map for now:

![image](https://user-images.githubusercontent.com/74671973/129623743-8b135ea7-5a33-441b-bf3e-e8b44217b5a7.png)

**Comment by Mougk** [comment]
Agree, let's make that a priority.

**Comment by joe-brilliant** [comment]
@rkassa lets get this into the next map deploy if possible, thx!

**Comment by rkassa** [comment]
All set on dev, @joe-brilliant :
http://dev-map.covid-19.global.health/#country

All good to ship to prod?

**Comment by joe-brilliant** [comment]
@rkassa lets ship it!
