### ISSUE TITLE
A json file that contains the list of countries in the DB

### ISSUE THREAD

**Issue by sergioloporto** [globaldothealth/list#2106]
Needed a json file that contains the list of of countries in MongoDB.

The file would have to be updated on a daily basis automatically.

This file will be used in https://github.com/globaldothealth/list/issues/2083 in order to populate the select menu.

Once ready, please provide ways to access this file.

**Comment by abhidg** [comment]
@sergioloporto realised that the map app already has a list of countries from https://covid-19-aggregates.s3.amazonaws.com/country/latest.json -- would that work for you?

**Comment by sergioloporto** [comment]
@abhidg it seems to have already a clean list. I.e. USA appears only once as "United States".
If we put this list of countries in the Select Menu in the data site, wouldn't we miss some cases if someone will pick "United States" from the list?

**Comment by abhidg** [comment]
@sergioloporto that's generated from the DB, so at least with respect to `location.country` we have no instances of alternative names

**Comment by sergioloporto** [comment]
thanks, then I think this issue can be closed
