### ISSUE TITLE
Consolidate the countries names in the DB

### ISSUE THREAD

**Issue by sergioloporto** [globaldothealth/list#2107]
To fix/consolidate the countries names in the DB.

This is also a blocker to https://github.com/globaldothealth/list/issues/2083

The same country can be referred to by multiple names e.g. 'US', 'USA', 'United States' and 'United States of America'.
One country should be visible/searchable with only one  standardised name.

**Comment by abhidg** [comment]
It seems `location.country` is already standardised in the database, as discussed in #2106
