### ISSUE TITLE
Cache /cases and/or counts for filters to speed up queries

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2114]
(Placeholder issue to mitigate 504 errors)

**Comment by joe-brilliant** [comment]
Ideally we can pursue this a short term solution to speed up loading time for larger data sets, specifically the countries featured in the Data Deep Dives that we plan to promote on social media and our news letters soon (cc @Mougk)

**Comment by joe-brilliant** [comment]
@maciekz1996 @marlenachroscicka @sergioloporto lets discuss this next week would be great if HTD can help with a solution here, thanks!

**Comment by abhidg** [comment]
Using the nginx content cache with a few days / one week expiry date should help as well for the */cases* endpoint: https://medium.com/@vdboor/using-nginx-ingress-as-a-static-cache-91bc27be04a1

This would require modifying
* the ingress controller
* setting Cache metadata in headers for */cases* endpoints in the curator service

**Comment by joe-brilliant** [comment]
Thanks @abhidg , looks like #1804 (504 errors) may also be related ?

**Comment by abhidg** [comment]
Fixed via #1804, no more 504
