### ISSUE TITLE
Add Vaccination Status to Schema

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/list#2120]
As we enter a new phase of the pandemic in spring 2021; namely that people have been vaccinated, we would like to add vaccination status to the schema.

**Proposal**: 

Add a new section to the schema called: "Vaccination"

1. Vaccination dose 1
Answers: yes/no

2. Vaccine Name dose 1 
Answer: list of WHO licensed vaccines (https://www.who.int/news-room/q-a-detail/coronavirus-disease-(covid-19)-vaccines?topicsurvey=v8kj13)&gclid=Cj0KCQjwjo2JBhCRARIsAFG667VxncQUvTueaWqoZkFz6KAyRL9juTKY4H83r61p8x6ygq-gYt1k_WEaAk99EALw_wcB) or other (free text)

3. Vaccination dose 1 date
Answer: 'date'

4. Side effects dose 1
Answer: Symptom ontology

5. Vaccination dose 2
Answers: yes/no

6. Vaccine Name dose 2
Answer: list of WHO licensed vaccines (https://www.who.int/news-room/q-a-detail/coronavirus-disease-(covid-19)-vaccines?topicsurvey=v8kj13)&gclid=Cj0KCQjwjo2JBhCRARIsAFG667VxncQUvTueaWqoZkFz6KAyRL9juTKY4H83r61p8x6ygq-gYt1k_WEaAk99EALw_wcB) or other (free text)

7. Vaccination dose 2 date
Answer: 'date'

8. Side effects dose 2
Answer: Symptom ontology

9. Vaccination dose booster
Answers: yes/no

10. Vaccine Name dose 3
Answer: list of WHO licensed vaccines (https://www.who.int/news-room/q-a-detail/coronavirus-disease-(covid-19)-vaccines?topicsurvey=v8kj13)&gclid=Cj0KCQjwjo2JBhCRARIsAFG667VxncQUvTueaWqoZkFz6KAyRL9juTKY4H83r61p8x6ygq-gYt1k_WEaAk99EALw_wcB) or other (free text)

11. Vaccination dose 3 date
Answer: 'date'

12. Side effects dose 3
Answer: Symptom ontology

13. Previous COVID-19 infection
Answer:  yes, no, NA

14.  Previous COVID-19 infection detection method
Answer: Clinical symptoms, antibody test, PCR test, Antigen test

**Comment by abhidg** [comment]
Vaccinations should probably be an array, as we start to have six-monthly/annual boosters. Having them separate does help in indexing/filtering though.

**Comment by AnyaLindstromBattle** [comment]
@Mougk nice work. Would it be worth having a 'batch' field? The SRAG data reports this. It also reports the name of the lab which produced the vaccine, as well as whether the patient has recently received a flu jab (in the last vaccination campaign) and, if so, the date this was given.

**Comment by Mougk** [comment]
'batch' yes. 

Flu vax perhaps something that can go into nodes field? I don't see immediate connection to why that may be relevant to covid vaccination or epidemiology?

**Comment by AnyaLindstromBattle** [comment]
Also - you may want to make field 14 in line with the allowable entries for 'Method of Confirmation' field? These are PCR test, serological test, clinical diagnosis, other

**Comment by Mougk** [comment]
While we are doing a schema overhaul, can we expand to also include antigen test in both? @iamleeg

**Comment by iamleeg** [comment]
How big is a vaxx batch? Might we run into deanonymisation problems?

**Comment by iamleeg** [comment]
Which if any of these fields should appear in the CSV export?

**Comment by Mougk** [comment]
All of them.

**Comment by iamleeg** [comment]
@mougk should I assume statically a certain number of vaccine entries to populate in the CSV for each case, and a certain number of side-effects for each vaccine? If I do, then there's a lot of wasted space for the majority of data that has 0 vaccines, and a slight chance that an individual case will have more vaccines/side-effects than I allowed space for.

If I don't, then it's slower to prepare and the structure of the CSV file is variable, because we have to count what the highest # of vaccines per case or side-effects per vaccine is before we can prepare the CSV.

**Comment by Mougk** [comment]
most users will want a file that is the same across downloads so they could merge them for example or run them through a script which may or may not specify the position based on column number. i'd say we allow up to 3 side effects and 4 vaccines for now? 

what do you think?

**Comment by iamleeg** [comment]
OK makes sense, thanks :+1:

**Comment by iamleeg** [comment]
@mougk update on this: it's in the backend for the strong cat release, so parsers can use the vaccine fields and they'll appear in the daily/filtered downloads. There's no UI in either the line list or the new case form though, I'll do the line list next if you think any of the vaccine fields should be shown there?

**Comment by Mougk** [comment]
Thanks. I'd say prioritise in the following order enable that it can be downloaded, entered via the curator form. No need to surface in data portal view.

Cc @AnyaLindstromBattle for update on parser for SRAG Brazil to include vaccination.
