### ISSUE TITLE
Variance in Scotland data from official stats

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2138]
Last ingestion reported more than 800,000 cases, but according to
https://www.gov.scot/publications/coronavirus-covid-19-daily-data-for-scotland/:

a total of 2,770,674 people in Scotland have been tested at least once. Of these people:
**436,688** have tested positive
2,333,986 were confirmed negative

This probably means data for the same person is being repeated; in which case 800,000 is the number of positive tests, or it could be a bug in the parser.

Source URL for Scotland is https://www.opendata.nhs.scot/dataset/b318bddf-a4dc-4262-971f-0ba329e09b87/resource/9393bd66-5012-4f01-9bc5-e7a10accacf4/download/trend_agesex_YYYYMMDD.csv

**Comment by jim-sheldon** [comment]
Once I finish https://github.com/globaldothealth/list/issues/1939 this will become easier to test.

**Comment by joe-brilliant** [comment]
thanks @jim-sheldon !

**Comment by joe-brilliant** [comment]
@jim looks like #1939 is in Proxy so might move this there, unless there's any reason to keep in Strongcat?

**Comment by iamleeg** [comment]
This is straightforward double-counting. The source data includes counts for age ranges 0-14, 15-29, ..., 85+ but it _also_ includes counts for 0-59, 60+. If you look on any day, the sum of the counts for _each_ of those groups of age range adds up to the total cases for that day. We're ingesting both, and getting two lines for every case (i.e. a 0-14 year old appears in the line list as one case age 0-14 and one case age 0-59).

@Mougk guessing the preference is to change the parser to only count the more specific age ranges and to drop existing cases for 0-59 and 60+ age brackets, is that correct?
