### ISSUE TITLE
Downloads not counted

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2162]
Users can download the full data set, but this does not result in their download being counted in the database.

**Comment by joe-brilliant** [comment]
Thanks @jim-sheldon do we know when this stopped tracking?

**Comment by jim-sheldon** [comment]
It looks like it stopped on August 10.

**Comment by jim-sheldon** [comment]
Fixed in https://github.com/globaldothealth/list/pull/2170/
