### ISSUE TITLE
Add Beilstein G.h poster to website

### ISSUE THREAD

**Issue by fojackson8** [globaldothealth/list#2178]
We'd like to add the poster we created for the [Beilstein Open Science Symposium 2021](https://www.beilstein-institut.de/en/symposia/open-science/) to the G.h website.

Here's a link to the poster + presentation abstract:
https://docs.google.com/document/d/1I5kFovfZ4fJ7eWOpVjnoW-8Wv6dsvyio-CH2AZ7hTvY/edit?usp=sharing

Contact Felix for poster in original PPT format.

**Comment by sergioloporto** [comment]
@joe-brilliant @fojackson8 can you please send me a good quality .jpg for the website?
If possible 1000px width or bigger.

**Comment by joe-brilliant** [comment]
Thanks @sergioloporto agreed we need a better image. Could we just use one of the Beilstien logos? https://www.google.com/search?q=Beilstein-Institut+logo&oq=Beilstein-Institut+logo&aqs=chrome..69i57j33i160.1076j0j7&sourceid=chrome&ie=UTF-8

**Comment by sergioloporto** [comment]
@joe-brilliant 
Done
Link: https://test-globalhealth.pantheonsite.io/2022/01/07/transparent-data-for-effective-research-beilstein-open-science-symposium-2021/
Homepage preview: https://test-globalhealth.pantheonsite.io/

**Comment by Mougk** [comment]
Link on page does not link to the actual poster. anyway we can have two links? one to the beilstein open science symposium and one to a PDF of our poster?

**Comment by sergioloporto** [comment]
@Mougk sure we can add links here (marked in red): 
![image](https://user-images.githubusercontent.com/51946947/150117388-cd2145cc-dd2c-4d53-8e8b-43e76356ab97.png)

Please provide me with:
Link and anchor for each one of these links

**Comment by Mougk** [comment]
the article link is already in the 'read article' @fojackson8 will send PDF to poster via slack.

**Comment by joe-brilliant** [comment]
Thanks @Mougk @fojackson8. @sergioloporto please let us know when the update page is ready for final review with the poster included

**Comment by sergioloporto** [comment]
@joe-brilliant from my side it is ready. 
Waiting for final confirmation

**Comment by joe-brilliant** [comment]
Thanks @sergioloporto can we make the "Download the poster" text bolder, and style it like the "Read Article" button?

**Comment by joe-brilliant** [comment]
@sergioloporto if we could include a small thumbnail preview of the poster too that would be nice

**Comment by sergioloporto** [comment]
@joe-brilliant ready to test: https://test-globalhealth.pantheonsite.io/

**Comment by joe-brilliant** [comment]
This looks great to me thanks @sergioloporto ! @Mougk @fojackson8 let us know if this is good to go and we can push to production in our next release

**Comment by fojackson8** [comment]
Looks great, thanks a lot Sergio and Joe!
