### ISSUE TITLE
Data storage and processing need to move to Germany

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2186]
**Describe the bug**
Coming from the data privacy impact assessment: it's _way_ hard to comply with GDPR and also store data outside Europe (it used to be easy because of Safe Harbour, but that's not been valid for years now). To demonstrate compliance, we need to migrate data hosting (i.e. mongodb atlas, S3) and processing (k8s, batch) to the Frankfurt region. Not sure yet of the urgency but definitely best case is "soon", rather than "when we get around to it".

**To Reproduce**
1. Go to the United States
2. Open the door to a data centre
3. Look at the computer

**Expected behavior**
The computer does not store any global.health data

**Environment (please complete the following information):**
 - regulatory

**Comment by joe-brilliant** [comment]
@Mougk : @iamleeg raised the important consideration on prod sync today this may be less urgent if RF/PPI is going to be come the data controller, esp if their legal team has a different POV on GDPR as a US based entity. Since it's a significant LOE, let's flag this for them to consider and offer their guidance on.

**Comment by joe-brilliant** [comment]
@iamleeg @Mougk  if we will need to migrate to a RF / PPI managed AWS instance anyway, are there any efficiencies gained by doing both of these exercises simultaneously vs. sequentially?

**Comment by joe-brilliant** [comment]
Or phrased another way, maybe we can look at the overall migration efforts holistically and determine the most efficient approach and timing

**Comment by iamleeg** [comment]
@joe-brilliant we (by which I really mean @jim-sheldon) are going to put in place some of the pieces for turnkey deployment before migrating either way so it should be lower effort either way. As I understand it the plan is to move billing for our existing service accounts over to PPI rather than to create new accounts and "migrate" everything over to them, if that's the case then there's no engineering effort to support that part of the migration.
