### ISSUE TITLE
Add Lancet article to /research

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2200]
https://www.thelancet.com/journals/lanepe/article/PIIS2666-7762(21)00192-7/fulltext

**Comment by joe-brilliant** [comment]
@rkassa reminder to add this to /research with the next website update, thanks! cc: @Mougk

**Comment by joe-brilliant** [comment]
Hi @rkassa any updates / ETA for this issue?

**Comment by rkassa** [comment]
Added and deployed to both `dev` and `prod`
