### ISSUE TITLE
Issues with dots on the map

### ISSUE THREAD

**Issue by marlenachroscicka** [globaldothealth/list#2201]
- When zooming in to regional views, the dots are not responsive to clicking and the pop ups now appear out of view
- The sizes and borders around the dots are not always clear which areas they apply to

**Comment by maciekz1996** [comment]
Hi @rkassa are you working on this issue? Or should HTD take care of that?

**Comment by joe-brilliant** [comment]
@maciekz1996 @rkassa what's the status for this issue? Are we still blocked? If HTD can take this on let's please do that and close this out ASAP

**Comment by maciekz1996** [comment]
@joe-brilliant I will handle this issue tomorrow first thing in the morning

**Comment by joe-brilliant** [comment]
Thanks @maciekz1996

**Comment by joe-brilliant** [comment]
@maciekz1996 @marlenachroscicka @sergioloporto I am still seeing issues with the regional view. If I zoom in at any level and click on dots, the dialogue box is not visible. Important we fix this before we have Applause start testing filtered data downloads. Lets please make this a priority to resolve, thanks
