### ISSUE TITLE
Move the prune-uploads script to AWS Batch

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2216]
It currently takes 6h to run the prune script for the US data set which is right on the runtime limit for GitHub actions.

While here, we also need better sequencing via hooks or queueing for ingestion, pruning, exporting, and aggregation to ensure that downloads and reports are consistent with a stable view of the data.

**Comment by abhidg** [comment]
Bumping to P1 as non-US ingestions are timing out as well
