### ISSUE TITLE
Algiers is not a country, but is in country field in line list

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2221]
**Describe the bug**
Algiers is not a country, but is in country field in line list

**To Reproduce**
1. Go to https://data.covid-19.global.health
2. Click on Filter
3. Select country dropdown
3. Check that Algiers is in list

Algiers also has cases, which it shouldn't

**Expected behavior**
Cases assigned to Algiers should be assigned to Algeria, with appropriate Admin1

**Additional context**
Seems to be a known issue as seen in https://github.com/globaldothealth/list/blob/be70bddf1bcc0b58363b7cc84cb512999b655410/data-serving/scripts/aggregate/aggregate/app.py#L17

**Comment by iamleeg** [comment]
I would advocate for the difficult but consistent solution to this: transform the data to store ISO 3166-1 country codes and translate those codes to names (and vice versa) in the UI layer. That approach also closes out some other, less politically sensitive ambiguities, like USA/US/United States/United States of America/America.
