### ISSUE TITLE
Add Nature Medicine correspondence to /research 

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2229]
@rkassa let's please add this new publication to our research page too cc: @Mougk 

https://www.nature.com/articles/s41591-021-01545-w

**Comment by joe-brilliant** [comment]
@rkassa bumping this issue to add to /research, thanks

**Comment by sergioloporto** [comment]
Done.
Links: https://test-globalhealth.pantheonsite.io/research/
Homepage preview: https://test-globalhealth.pantheonsite.io/
