### ISSUE TITLE
Add API documentation and links to FAQ

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2256]
Once we formally announce the API, we should also update our FAQ with information/instructions/links 

Draft doc:

https://docs.google.com/document/d/1EKoWmJKRXU9CSQipIurPrP_nOT60fRD_xw58BkpRPAc/edit 

Current FAQ: https://global.health/faqs/

**Comment by sergioloporto** [comment]
@joe-brilliant 
Done
Link: https://test-globalhealth.pantheonsite.io/faqs/

**Comment by sergioloporto** [comment]
@Mougk @abhidg @iamleeg kind request if the technical FAQ for API is ready.
If everything is correct I will deploy.

**Comment by iamleeg** [comment]
Hi @sergioloporto! I added a paragraph at the bottom of the google doc about the Python and R helper scripts. Would be great to add that to the FAQ too (sorry I'd do it myself but I don't believe I have access). Everything else looks good, good to go :+1:. Thank you!

**Comment by sergioloporto** [comment]
@iamleeg Thank you for the message. The changes you suggested are ready. Please double check and confirm.

**Comment by iamleeg** [comment]
Looks good, thank you!

**Comment by abhidg** [comment]
@sergioloporto Thanks! Could you update the contrast or add underline to links?
![image](https://user-images.githubusercontent.com/62665/151164123-0fe3b773-32cd-44bc-8189-a11e9cbb9f41.png)

**Comment by joe-brilliant** [comment]
thanks all! @sergioloporto I've copied my comments from Slack below as well so you have them all together 

>Joe Brilliant  17 hours ago
@Sergio Lo Porto we can also delete this Q and A :

Is there a public API for Global.health?

Joe Brilliant  17 hours ago
And let's change title of this new Q to "How do I access the Global.health API?"

Can we also update "As of publication, our database includes over 5 million cases from over 100 countries" to "over 60 million?" thank you!

**Comment by joe-brilliant** [comment]
@sergioloporto we can also link "contact us" to trigger a mail to info@global.health

**Comment by sergioloporto** [comment]
@abhidg @joe-brilliant  all changes are ready to be reviewed: http://test-globalhealth.pantheonsite.io/

**Comment by joe-brilliant** [comment]
Looks great to me @sergioloporto! Let's fire away and line up a Wordpress release once this, any other issues, and @maciekz1996's fix to the Feedback button are ready to go!
