### ISSUE TITLE
Track map interactions

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2280]
When a user applies a filter in the map our system should record information about it.

**Comment by jim-sheldon** [comment]
Related to https://github.com/globaldothealth/list/issues/2205

**Comment by joe-brilliant** [comment]
Thanks for adding this @jim-sheldon ; looping in the HTD team @maciekz1996 @marlenachroscicka @sergioloporto as it pertains to the React rebuild

**Comment by joe-brilliant** [comment]
@maciekz1996 let me know if you need GA access
