### ISSUE TITLE
Add a "Provide Feedback" button to the Wordpress/Pantheon

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2281]
To facilitate gathering user feedback we should add a button to the UI that would present a modal with a prompt to provide input/suggestions/requests in a textbox. A "submit" button in that modal would send that information back to the product team--firing an email to "info@global.health" with the textbox contents and user information would be good.

**Comment by joe-brilliant** [comment]
Adding HTD team so we can also replace the Get Involved button on the website homepage header with a similar button

**Comment by sergioloporto** [comment]
1) Where should the "provide feedback" button be? Only on homepage? Should be a floating button, that stays at the window edge and stays always at the same height?
2) After clicking should be a popup? Or can it redirect to a subpage with a contact form?
3) Can you please reword the changes about the "Get Involved" button? Does it mean  that you would like to remove it from the navbar and have the "Get Involved" button next to the "Provide feedback" button? So if the "Provide feedback" is a floating button, also the "Get Involved" will be there next, below or behind it?

**Comment by maciekz1996** [comment]
@joe-brilliant I added "Provide Feedback" button in the footer menu. After clicking on this button popup appears with a text field. The content from this textfield is being sent to Global.health email address after submitting the form. Below are the screenshots showing this feature. You can also take a look at it yourself at: https://dev-globalhealth.pantheonsite.io 

Please let me know what do you think about it
<img width="1310" alt="Screen Shot 2022-01-04 at 12 29 13" src="https://user-images.githubusercontent.com/44740625/148052938-de55a727-3832-45aa-93f6-c680d565cb6a.png">
<img width="1894" alt="Screen Shot 2022-01-04 at 12 28 30" src="https://user-images.githubusercontent.com/44740625/148052951-4c17b5ae-7e39-40e7-8f90-a6296608f4cf.png">

**Comment by joe-brilliant** [comment]
Thanks @maciekz1996 as we discussed today let's replace the upper right "Get Involved" button on homepage with the "Feedback" button. Also at @jim-sheldon's excellent suggestion let's also add similar buttons to the Map and Data applications.

**Comment by maciekz1996** [comment]
@joe-brilliant @jim-sheldon Sounds like a good idea, we have just created tasks for those features: #2359 and #2358

**Comment by maciekz1996** [comment]
@joe-brilliant I changed "Get involved" to "Provide Feedback" in the upper right corner. After clicking on this button the popup appears. After submitting the content is being sent to info@global.health address. Feel free to test it out here: https://test-globalhealth.pantheonsite.io/ and let me know if anything needs to be changed.

**Comment by joe-brilliant** [comment]
@maciekz1996 I just realized we don't include an email field. This is important so we can follow up with users directly. Can you add this to the module? Also the confirmation message flashed very fast and I wasn't able to view it. thanks!

**Comment by joe-brilliant** [comment]
Also @maciekz1996 when I clicked on Feedback a second time I did see the confirmation message, and not a new modal. this was fixed when I clearned the browser cache
