### ISSUE TITLE
Add SGTF value to schema and curator UI

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2296]
In order to be able to host case data with SGTF information as leading indicators for Omicron variant detection, we'll need to either add or repurpose an existing column to the schema and the curator UI. What we'll need to decide is what to name the column and the values. We could either name it "S Gene Target Failure (SGTF)" with "True" and "False" as the options, but that might be confusing (since "True" would = "Fail"). Another approach would be to name the column "S Gene Target Results" with "Pass" and "Fail" as the options, with a "Fail" value =  "SGTF", which we could then add as another column etc.

Thoughts and other approaches welcome; would be good to verify best practices with our partners who are collecting and reporting these data

More context / info below and attached

https://www.cdc.gov/coronavirus/2019-ncov/science/science-briefs/scientific-brief-omicron-variant.html 

https://wwwnc.cdc.gov/eid/article/27/12/21-0652_article 

https://twitter.com/kaitejohnson9/status/1466611340210958339?s=21 

[technical-brief-and-priority-action-on-Omicron.pdf](https://github.com/globaldothealth/list/files/7654599/technical-brief-and-priority-action-on-Omicron.pdf)

https://twitter.com/kallmemeg/status/1469350830864322560?s=20

**Comment by jim-sheldon** [comment]
Should SGTF exist as a field in the base of the schema, or nested inside another field?
For UI changes, how about a new column in the case data table labeled "S Gene Target Results" and a corresponding button in the filter modal with "Pass" and "Fail" as valid search terms?

**Comment by joe-brilliant** [comment]
Great questions @jim-sheldon . @Mougk do you have any recommendations or sample data sets we can refer to?

**Comment by joe-brilliant** [comment]
Per @Mougk let's use this as an example to build on and name the column SGTF and indicate results with "0" and "1" (1 stands for S-, representing the deletion), i.e. how data is represented in the UK line list https://zenodo.org/record/5105921/files/reduced_data_20210225.csv.zip?download=1

**Comment by joe-brilliant** [comment]
UK data here via @Mougk 

"
https://khub.net/documents/135939561/405676950/Confirmed+Omicron+cases+SGTF+LTLA+2021-12-08.xlsx/8003737a-cfc5-a320-2b55-794495cdbb09 (link to webpage here: https://www.gov.uk/government/publications/covid-19-variants-genomically-confirmed-case-numbers/variants-distribution-of-case-data-10-december-2021). Ideally we also add cases to that sheet that are total number of cases which can easily be extracted from this API: https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&metric=newCasesBySpecimenDate&format=csv (https://coronavirus.data.gov.uk/details/download)."

**Comment by joe-brilliant** [comment]
Here's the source / citation info for the above data via @iamleeg https://zenodo.org/record/4579857#.Ybd1EH3ML64
