### ISSUE TITLE
Add field completeness script to Map UI

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2297]
Quick placeholder issue to incorporate @fojackson8's awesome new script to illustrate completeness % across all our db fields into our data viz when we roll out the new react rebuild for our map : ). This feature will help users get a snapshot of data completeness across our schema, which has been long requested 

Will take some design thinking and tinkering but maybe it could live as an enhancement to our Coverage Map tab with some contextual options in the left-hand module to select different fields to view completeness by country. 

![image](https://user-images.githubusercontent.com/74671973/144723244-17dd95da-1643-45ce-b158-0cf56b96889c.png)

@fojackson8 if you could add the CSV to this issue that would be great, thanks!

**Comment by fojackson8** [comment]
[Gh_full_country_completeness_dict.csv](https://github.com/globaldothealth/list/files/7712385/Gh_full_country_completeness_dict.csv)

**Comment by joe-brilliant** [comment]
Thanks @fojackson8 ! (see above @maciekz1996 )

**Comment by joe-brilliant** [comment]
Following up email threads/chats today, would be great to add the equivalent of a "freshness" field that shows the latest date of ingestion per country (cc @fojackson8 @maciekz1996 @abhidg @jim-sheldon @Mougk)

**Comment by abhidg** [comment]
Add completeness to aggregate code to generate JSON in covid-19-aggregates bucket

**Comment by abhidg** [comment]
@maciekz1996 Completeness data is at s3://covid-19-aggregates/metrics/completeness.json, let me know if you need any changes. The country labels will change to two letter codes once that migration is over. I have set the script to run weekly on Sundays.

**Comment by joe-brilliant** [comment]
That's awesome thanks @abhidg! Does this also include "freshness"?
