### ISSUE TITLE
aggregate: Is not running, make it run

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2302]
Currently, aggregate fails to run automatically even though an EventBridge﻿ rule is setup to trigger the Batch job definition.

Manually triggering the job definition works, so this is probably due to the EventBridge rule and the job definition being in different zones.

**New**: Idea is to hook it up to prune-uploads and make it run from there, it still fails though.

**Comment by jim-sheldon** [comment]
I made a new EventBridge rule in the same region (eu-central-1) as the Batch job definition, so it should run automatically now. Normally you can pass event triggers through a bus, but this does not work with custom scheduling enabled. There does exist another issue with the job timing out, even when run manually, which I will look into as part of this issue.

**Comment by jim-sheldon** [comment]
The job can run manually now. Once I see the EventBridge rule trigger the job I will close this issue.

**Comment by jim-sheldon** [comment]
EventBridge works but an error occurred when the script ran. Creating a separate issue for that.
