### ISSUE TITLE
Data dictionary links broken

### ISSUE THREAD

**Issue by rasmi** [globaldothealth/list#2309]
Hi Global.health team,

The sidebar at: https://data.covid-19.global.health/cases is referencing the old data dictionary file [here](https://github.com/globaldothealth/list/blob/main/data-serving/scripts/export-data/functions/01-split/fields.txt) (404 link, since moved to [here](https://github.com/globaldothealth/list/blob/main/data-serving/scripts/export-data/fields.txt)), but the actual data dictionary file is now [here](https://github.com/globaldothealth/list/blob/main/data-serving/scripts/export-data/data_dictionary.txt) (see #1610). There are quite a few references (some automated scripts, some direct links, some documentation) that seem split beetween the old [`fields.txt`](https://github.com/globaldothealth/list/search?q=fields.txt) and the new [data dictionary](https://github.com/globaldothealth/list/search?q=data+dictionary) files. It would be great to fix the link and any other references that need to be updates where `data_dictionary.txt` is the correct file to use!

**Comment by joe-brilliant** [comment]
Thanks for flagging this @rasmi ! Looping in @jim-sheldon and @iamleeg as well as @abhidg and tagging/prioritizing accordingly.
