### ISSUE TITLE
Replace Python print statements with logging to StreamHandler

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2319]
Calling `print` in Python does not automatically write its output to stdout; when a script runs in Docker and hangs on a line, it can result in a timeout with incomplete (even no) output written to Cloudwatch logs.
We should use `logging` instead of `print` statements, and we need to use a `StreamHandler` to ensure each log statement gets flushed from the buffer and made visible in Cloudwatch.

https://docs.python.org/3/library/logging.handlers.html#streamhandler

**Comment by iamleeg** [comment]
Looks like there's still stuff to do in ingestion, I'll take that on.
