### ISSUE TITLE
Add Omicron Travel History Dataset to G.h

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2321]
@Mougk and collaborators have compiled a dataset of travel history associated with verified Omicron cases, which is updated regularly: https://docs.google.com/spreadsheets/d/1LHfVWlUfIFp-4NiAoyI4xIrq3v56juuK2-KrNquwtmo/edit#gid=0 

While not line list per se, these data are valuable, unique, and time-sensitive to make available to the global research and epidemiological community. We should find a simple and fast way to host these data via G.h in a downloadable format similar to our core LL db. A simple option could be to write a script to ingest/geocode the data and host on our github as a .CSV with some accompanying documentation on methodology, sources, data dictionary, authors etc. We can then create either a button and/or top level nav on our homepage to link to this GitHub page and/or a Wordpress page similar to our Data Deep Dives. Suggestions/ideas welcome on the best MVP approach!

**Comment by abhidg** [comment]
I think it's best to put data files in another repo, I'll create covid19-omicron and put up a WIP script there.

**Comment by abhidg** [comment]
WIP at https://github.com/globaldothealth/covid19-omicron, there are some issues with geocoding, looking into that.

**Comment by joe-brilliant** [comment]
Thanks @abhidg ! Good idea and great progress

**Comment by joe-brilliant** [comment]
@abhidg copying slack notes from @Mougk :

"could you add more details on the LTLA dataset from UK gov and direct link to data description?

Moritz  1 hour ago
and pls add data dictionary to travel dataset and ltla dataset (similar to denmark readme)"

**Comment by abhidg** [comment]
@joe-brilliant done!

**Comment by joe-brilliant** [comment]
@abhidg I think we can close this issue now and add updates as needed?
