### ISSUE TITLE
Variants/omicron wordpress page

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2326]
Following the look, feel, and structure of our data deep dive pages, an exploratory feature idea to create a simple word press page to organize, contextualize, and connect to our various and evolving Omicron data sets, resources, and research (and potentially for other variants in the future)

Essentially I see this page containing 3 main elements to start with that we can link to and provide some brief commentary on methodology around that we can update periodically: 

1. Travel History (#2321)
2. SGTF data, where available (#2296)
3. Policy data via G.h consortium partner COVID AMP 
(https://covidamp.org/policymaps?mapId=global&view= and https://covidamp.org/data?filters_policy=%7B%22subtarget%22%3A%5B%22Omicron%22%5D%2C%22dates_in_effect%22%3A%5B%222021-12-10%22%2C%222021-12-10%22%5D%2C%22primary_ph_measure%22%3A%5B%22Travel%20restrictions%22%5D%7D&placeType=affected&type=policy
4. BNO Newsnodes Tracker https://newsnodes.com/omicron_tracker

From an implementation and information hierarchy perspective, I could see this living either under a dedicated homepage menu for variants, under the data navigation, and/or a dedicated link above the fold, similar to COVID AMP (see upper right of homepage: https://covidamp.org/) Open to recommendations.

Suggested URL structure: global.health/variants/omicron

![image](https://user-images.githubusercontent.com/74671973/145613438-351e76a1-c7a7-41f2-92b4-8b7930f7b6b8.png)

**Comment by sergioloporto** [comment]
@joe-brilliant  here is the link:
https://dev-globalhealth.pantheonsite.io/variants/variants-omicron/

That page can be edited here:
https://dev-globalhealth.pantheonsite.io/wp-admin/edit.php?post_type=page
![image](https://user-images.githubusercontent.com/51946947/146035543-a6923ccb-a374-435a-9018-262fa989ba18.png)


Menu screenshot:
![image](https://user-images.githubusercontent.com/51946947/146035657-fe31d949-84a7-4c25-b7fb-c9bfa496ee94.png)

Screenshots:
![chrome-capture](https://user-images.githubusercontent.com/51946947/146036080-54208dfe-2585-4e99-a8a6-17cd20a59d4c.jpg)
![chrome-capture (1)](https://user-images.githubusercontent.com/51946947/146036099-1d2a53d3-dd0a-4465-a3f1-1f71ac60537c.jpg)

**Comment by joe-brilliant** [comment]
Thanks @sergioloporto !

**Comment by joe-brilliant** [comment]
could we also just do the URL as "global.health/variants/omicron/"

**Comment by sergioloporto** [comment]
Hi @joe-brilliant 
renaming done. Please confirm.

URL change too. Please confirm.

**Comment by joe-brilliant** [comment]
@sergioloporto looks good to me! Will draft up a Gdoc for content / copy tomorrow.
