### ISSUE TITLE
Colombian cases share the same note

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2328]
There appears to be a parsing error with Colombia; cases have the same entry in the note field: "Case still active, Patient self-isolated and recovered at home., Case transmission under investigation (currently unknown)., Symptom severity was Mild, Date reported online was 12/04/2021., Date reported to SIVIGILA was 11/20/2021."

**Comment by abhidg** [comment]
I checked the country export for Colombia, and I get 115,656 unique note entries, which admittedly is far lesser than the number of rows. The notes field in this parser is not taking in notes from upstream, instead being used as a place to note further fields in the dataset schema that we do not have corresponding fields for. The text above only appears in 111 rows.

Closing this, feel free to reopen if there is some other issue relating to the notes field.

```python
>>> import pandas as pd
>>> df = pd.read_csv("colombia.csv.gz", dtype=str)
>>> len(set(df.notes))
115656
>>> len(df[df.notes == "Case still active, Patient self-isolated and recovered at home., Case transmission under investigation (currently unknown)., Symptom severity was Mild, Date reported online was 12/04/2021., Date reported to SIVIGILA was 11/20/2021."])
111
```
