### ISSUE TITLE
Broken links on https://global.health

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2347]
* Terms of Use: Privacy policy link on https://global.health/terms-of-use/ goes to https://global.health/policy, should be https://global.health/privacy
* FAQ: What kind of data are available? schema link goes to https://github.com/globaldothealth/list/blob/main/data-serving/data-service/schemas/cases.schema.json, should be https://raw.githubusercontent.com/globaldothealth/list/main/data-serving/scripts/export-data/data_dictionary.txt
* FAQ:  How can I stay up to date on your progress and plans? links to https://globaldothealth.substack.com/p/coming-soon should be https://globaldothealth.substack.com

**Comment by joe-brilliant** [comment]
Thanks for flagging these @abhidg; @marlenachroscicka @sergioloporto can we please add these to the fixes for the next website update?
