### ISSUE TITLE
Countries with spaces in them do not use pre-exported data

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2353]
**Describe the bug**
Countries with spaces in them do not use pre-exported data, instead going through the usual filtered download route.

**To Reproduce**
1. Go to https://data.covid-19.global.health
2. Click on Filter, then New Zealand
3. Click Download Dataset

**Expected behavior**
A file named new_zealand.csv.gz to appear, like in the case of countries without spaces

**Additional context**
Probably due to quotes in query not being replaced at https://github.com/globaldothealth/list/blob/76a2c210501369f24dd4e55f74268d963a95dd4a/verification/curator-service/api/src/controllers/cases.ts#L110

**Comment by jim-sheldon** [comment]
Will be done when #2223 is done

**Comment by joe-brilliant** [comment]
@abhidg @jim-sheldon  looks like it might be done as well, can we close?

**Comment by jim-sheldon** [comment]
Confirmed working using US JSON download
