### ISSUE TITLE
Change schema for SGTF field

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2356]
We currently use an optional number, with 0 for no S-Gene dropout, 1 for S-Gene dropout, and no value when there's no value. Request from Moritz is to use "NA" for no value, in line with other sources.

**Comment by abhidg** [comment]
Does this mean that SGTF will be NA for a case which has no information but is from a source that provides SGTF info, or will all parsers need to put SGTF = NA?

**Comment by jim-sheldon** [comment]
Done as part of https://github.com/globaldothealth/list/pull/2355

**Comment by jim-sheldon** [comment]
> Does this mean that SGTF will be NA for a case which has no information but is from a source that provides SGTF info, or will all parsers need to put SGTF = NA?

Sorry, I did not address this before closing the ticket. With the change set tagged in this issue SGTF should get a default value of NA, so parsers without SGTF information should not need to change.
