### ISSUE TITLE
Technology migration from BCH accounts to PPI accounts—see what we need to do and do it

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2365]
Make sure everything in the current G.h deployment owned by BCH becomes owned by PPI. Track any engineering needs here.

**Comment by joe-brilliant** [comment]
Thanks for getting this started @iamleeg ! I sense the lion's share of this work will be around migrating any services currently nested under BCH or Healthmap accounts (i.e. AWS, GoDaddy, Mapbox, Google Analytics). Will add a dedicated doc for us to work from as we make headway here.

**Comment by abhidg** [comment]
@ksewalk are there any action items here? would be good to schedule a milestone for this, or close if not planned.
