### ISSUE TITLE
Images research from Unsplashed

### ISSUE THREAD

**Issue by marlenachroscicka** [globaldothealth/list#2367]
Search new images that fit the articles.
Replace the images that are duplicated.

**Comment by sergioloporto** [comment]
@joe-brilliant 
Done
Link: https://test-globalhealth.pantheonsite.io/research/

**Comment by joe-brilliant** [comment]
@sergioloporto images look great! Would it be possible to get the top line "Explore insights and research enabled by Global.health data" to appear without wrapping, and also get the first row of images to align too by getting "Sharing, synthesis and sustainability of data analysis for epidemic preparedness in Europe" to fit in 3 lines? Maybe change "and" to "&"?

**Comment by sergioloporto** [comment]
- Box containing  "Explore insights and research enabled by Global.health data" (first line) is now enlarged. Longer titles may still wrap.

For that post to fit in 3 lines, "and" to "&" is not enough:
![image](https://user-images.githubusercontent.com/51946947/150305128-71c44050-1110-4146-be61-ea9ca580674a.png)


A workaround could be to word-break all, but it can create inconsistencies in other places:
![image](https://user-images.githubusercontent.com/51946947/150305353-075ed56c-184e-44f7-b067-d04a8f93889d.png)


How would you like to proceed for this one?

**Comment by joe-brilliant** [comment]
Thanks @sergioloporto. In that case let's just revert the title to "Sharing, synthesis and sustainability of data analysis for epidemic preparedness in Europe" to match the source article (and remove the "&"). Page looks great. Let's make that last change and we can close this out

**Comment by sergioloporto** [comment]
@joe-brilliant ready. If all is ok I can deploy to live

**Comment by joe-brilliant** [comment]
Looks good to go!
