### ISSUE TITLE
batchValidate passes but batchUpsert fails validation at DB

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2410]
**Describe the bug**
batchValidate passes but batchUpsert fails with BulkWriteError for SRAG data after adding vaccine fields

**To Reproduce**
Re-run SRAG parser.

Previous log at https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/brazil_srag-srag-ingestor-prod$252Fdefault$252Fd3457dba353f43f2a3db4f8123bd56c4

Tried re-inserting document in MongoDB 5.0 (which shows validation errors), and the vaccines field is correctly inserted.

**Comment by iamleeg** [comment]
And I tried manually inserting a case from the AWS logs you linked into dev (4.4.12) and it failed validation. Here's what I'd try next: turn off validation (in dev or locally!), insert the documents, turn validation back on, [validate the collection](https://docs.mongodb.com/manual/reference/method/db.collection.validate/).
