### ISSUE TITLE
Update all country links for filtered data results on Data Deep Dive pages to reflect new ISO country codes

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2422]
Current DDD links are as follows, and there are some links in the page content as well that may need updating to new URLs:

https://data.covid-19.global.health/cases?country=peru
https://data.covid-19.global.health/cases?country=mexico
https://data.covid-19.global.health/cases?country=colombia
https://data.covid-19.global.health/cases?country=Brazil
https://data.covid-19.global.health/cases?country=argentina
https://data.covid-19.global.health/cases?country=Germany
https://data.covid-19.global.health/cases?country=%22United+States%22

**Comment by iamleeg** [comment]
I don't think that I have access to the data deep dives in prod, but I can supply the changes:

Peru -> PE
Mexico -> MX
Colombia -> CO
Brazil -> BR
Argentina -> AR
Germany -> DE
United States -> US

Just replace the country name in the link with the code above and you're good to go.

**Comment by joe-brilliant** [comment]
Updated URLS below

https://data.covid-19.global.health/cases?country=PE
https://data.covid-19.global.health/cases?country=MX
https://data.covid-19.global.health/cases?country=CO
https://data.covid-19.global.health/cases?country=BR
https://data.covid-19.global.health/cases?country=AR
https://data.covid-19.global.health/cases?country=DE
https://data.covid-19.global.health/cases?country=US
