### ISSUE TITLE
Create pop up message for users viewing Data and Map applications on small screen resolutions or mobile devices

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2423]

**Comment by sergioloporto** [comment]
@joe-brilliant here is a screenshot as you requested:
![Uploading image.png…]()

**Comment by joe-brilliant** [comment]
@sergioloporto looks good! Might suggest saying "larger" instead of "bigger". This will only appear on Map and Data pages, correct?

**Comment by sergioloporto** [comment]
@joe-brilliant text changed.
Yes, I confirm, on data pages and on Map

**Comment by joe-brilliant** [comment]
Awesome thanks @sergioloporto !
