### ISSUE TITLE
Setup infrastructure in eu-central-1

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2508]
- [x] create duplicates of existing S3 buckets in eu-central-1 AZ
- [x] create new SES configuration in eu-central-1
- [x] create new batch queues and job definitions in eu-central-1
- [x] create new eventbridge triggers in eu-central-1
- [x] create new cloudwatch log groups in eu-central-1

**Comment by jim-sheldon** [comment]
Also created new batch compute environments, eventbridge rules and targets, sns topics, and cloudwatch alarms
