### ISSUE TITLE
Setup EKS cluster and DNS (eu.*) in eu-central-1

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2510]
- [x] create new k8s cluster for dev
- [x] copy k8s secrets/config to new cluster, substituting us-east-1 based values for eu-central-1
- [x] deploy main-eu packages to dev cluster
- [x] create new route53 entry for dev-eu-data.covid-19.global.health
- [x] test that new stack is available and functional at new hostname (accepting 504 errors or other timeouts)

**Comment by jim-sheldon** [comment]
Done for dev and QA
