### ISSUE TITLE
Deployment of parallel infrastructure in eu-central-1

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2511]
- [x] schedule new eventbridge triggers
- [x] prod only: pause ingestion
- [x] deleteMany({list: {$exists: false}}) to remove cruft
- [x] copy dev database to eu-central-1 instance
- [x] deploy viz repo to the new bucket
- [x] point route53 for dev-data.covid-19.global.health at the new dev cluster
- [x] point route53 for dev-map.covid-19.global.health at the new S3 bucket for map
- [x] test that new stack is available and functional at intended hostnames (do not accept 504 errors or other timeouts, it should work now)

Repeat for production, after disabling ingestion. Note that at least one ingestion (Mexico) is expected to break as the source data file is georestricted and not downloadable from Europe IPs (at least, it does not work in UK, but it does in us-east-1).

**Comment by jim-sheldon** [comment]
Remnants rolled to https://github.com/globaldothealth/list/issues/2684
