### ISSUE TITLE
Cleanup and removal of us-east-1 resources

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2512]
- [x] merge main-eu to main
- [x] repeat for release branch
- [x] unschedule old eventbridge triggers
- [ ] delete us-east-1 based resources
- [ ] undeploy old k8s cluster
- [x] pull requests to globaldothealth/react new map repo to update data locations

**Comment by jim-sheldon** [comment]
Remnants rolled to https://github.com/globaldothealth/list/issues/2685
