### ISSUE TITLE
Replace API documentation in FAQ with link to API documentation in Github

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2556]
> [7:59 AM] Also, the instructions here: https://github.com/globaldothealth/list/tree/main/api
> [8:00 AM] are different and better than the instructions here: https://www.global.health/faqs/

**Comment by joe-brilliant** [comment]
Hi @iamleeg @maciekz1996 I can make this change on Pantheon on dev and we can review and push to prod tmrw, will post a link once updated.

**Comment by joe-brilliant** [comment]
Another thought, should we consider a dedicated footer link on the website homepage for the API to surface it a bit more prominently @Mougk @iamleeg ?

**Comment by joe-brilliant** [comment]
Updated on Dev: https://dev-globalhealth.pantheonsite.io/faqs/
