### ISSUE TITLE
Ensure API documentation refers to ISO 3166-1 codes, not country names

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2558]
> [8:05 AM] c1 = get_cases(key, country="New Zealand")
> [8:05 AM] ^ this doesn't work for me
> [8:05 AM] I get an error
> [8:06 AM] and it loads with zero observations

**Comment by abhidg** [comment]
9eb0de128d8b92e39ab4d6c2b3b4ef74e0c5f273 :tada:
