### ISSUE TITLE
Supply canonical list of ISO 3166-1 country codes used

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2559]
> [8:06 AM] Lol. Well my next suggestion was going to be to supply a list of available country codes :slightly_smiling_face:

Currently we have a lot of different sources: a JS library, a Python library, and some workarounds for country names that Mapbox uses that neither of those recognise. Would be good to build a list of the country codes we use with maps to the name. Best would be to do this in Python and R as part of our API libraries.

**Comment by abhidg** [comment]
The current documentation links to the Wikipedia entry on ISO 3166 codes which has a comprehensive list.

**Comment by joe-brilliant** [comment]
I think we can closer this @iamleeg @abhidg ?

**Comment by iamleeg** [comment]
No, the wikipedia list is not sufficient.

> Would be good to build a list of the country codes we use with maps to the name.

This won't include all of the weird workarounds we have for Mapbox (e.g. it uses "United States" for country US, which most libraries don't use because it's ambiguous with "United States Minor Outlying Islands" when you're searching), and the names otherwise might not be the same as the ones we use. We actually have to prepare a list of the country codes we use and map them to the names of the countries we use.

**Comment by joe-brilliant** [comment]
Duly noted; thanks for the clarification + explanation @iamleeg !

**Comment by joe-brilliant** [comment]
@abhidg please close if this has been deployed
