### ISSUE TITLE
Update Wordpress site with orgs, news, and FAQs

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#2563]
New headshots and logos:

Gorgas
Genomics.africa 

Add Google.org blog

**Comment by joe-brilliant** [comment]
@Mougk please add any new logos / and headshots to this issue when you have them. For the Google.org announcement to be added to /News, suggest we go with Keyword blog since it's timestamped and links back to Google main site (good for SEO : ) : https://blog.google/outreach-initiatives/google-org/nonprofit-leaders-to-watch-2022/

**Comment by maciekz1996** [comment]
@joe-brilliant @Mougk I've added this article to `/press` section, you can see it here: https://dev-globalhealth.pantheonsite.io/press/

Please let me know if it looks good to you

**Comment by joe-brilliant** [comment]
LGTM thanks @maciekz1996 !

**Comment by Mougk** [comment]
yep, lgtm

**Comment by maciekz1996** [comment]
@Mougk Did you get the photos of new members that should go on the `/about` page? I'm wondering if I should deploy current changes to production or wait for those images (fyi @joe-brilliant )

**Comment by Mougk** [comment]
sent follow up via email (cc'd you @maciekz1996 )

**Comment by joe-brilliant** [comment]
thanks @Mougk @maciekz1996. New Gorgas ogo on Dev HP looks great, suggest we add a link to others (to http://www.gorgas.gob.pa/ ). I'd like to send out the newsletter by Wed latest so hopefully we can get the photos and add to the site this week and do a release no later than Monday w/ the updated Iubenda script. We can always add more pix later

**Comment by maciekz1996** [comment]
@joe-brilliant I've added the link to the Gorgas website

**Comment by joe-brilliant** [comment]
Thanks!
________________________________

**Comment by joe-brilliant** [comment]
Split out headshot updates to #2576 so we can close this issue out after next release @maciekz1996
