### ISSUE TITLE
Date confirmed before/after are the wrong way around in the UI

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2567]
The case filter UI has "date confirmed before" then "date confirmed after". But as this is a date range, that means that the end of the range is filled in _before_ the start of the range (i.e. I say something like "date confirmed before 2022-02-28, date confirmed after 2022-02-01". That's not the way I'd expect, so when I tried to search by confirmation date I got this wrong and put the beginning of the range in the "before" field and the end of the range in the "after" field.

**Comment by joe-brilliant** [comment]
Thanks @iamleeg looping in @Ania661
