### ISSUE TITLE
Collect filter usage data

### ISSUE THREAD

**Issue by maciej-zarzeczny** [globaldothealth/list#2581]
We should collect usage data of particular filters on Data portal. Especially which ones are used most often by the users .

**Comment by joe-brilliant** [comment]
Thanks for flagging this @maciekz1996. @jim-sheldon are we tracking any of these metrics in the db already?

**Comment by jim-sheldon** [comment]
We track filters applied when the user downloads in the database; we log all filters applied, including when the user does not download. The Cloudwatch query is `{$.log = "*Applying filter*"}`.

**Comment by abhidg** [comment]
We are tracking filters, reopen / create new issue if further tracking is needed
