### ISSUE TITLE
Make Batch jobs run on Fargate

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2662]
Our Batch jobs run on EC2, which works fine, but [AWS recommends](https://docs.aws.amazon.com/batch/latest/userguide/fargate.html) running on Fargate, primarily because it results in a shorter feedback loop.

Runs using version Fargate 1.4.0 fail with the error message `ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve ecr registry auth: service call has been retried 3 time(s)`.

Runs using Fargate 1.3.0 fail with the error message `CannotPullContainerError: Error response from daemon: ... net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`.

**Comment by abhidg** [comment]
@jim-sheldon can this be closed?
