### ISSUE TITLE
Remove notes section for all countries, make available upon request

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#2673]
The automatically-ingested notes contain free text that the upstream data providers added to the cases and these can be pretty specific and identifying, as the HDX partners have already discovered. Don't make notes part of the general data set, create a new 'note-viewer' role that has exclusive access and let admins give out (and revoke) that role as required.

**Comment by abhidg** [comment]
There are two classes of notes -- A. ones added upstream, which I think we should just remove entirely, and B. generated during ingestion, to add information that is not captured by our schema, such as in https://github.com/globaldothealth/list/blob/main/ingestion/functions/parsing/colombia/colombia.py

At the moment, these are not disambiguated. We might want to treat these differently depending upon how useful these B.notes are.

**Comment by joe-brilliant** [comment]
Per @abhidg, done on main needs to be deployed
