### ISSUE TITLE
Store Monkeypox data

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2699]
Set up a script to run daily that gets data from [this Google Spreadsheet](https://docs.google.com/spreadsheets/d/1THKTgAPxNRwISU9VeShaqfHPkEOaGb1W5TsNHi7WstA/edit#gid=0) and stores it.

The script should also clean the data (check date formatting), geocode, and assign better IDs.

A data dictionary should also exist.

**Comment by abhidg** [comment]
This should be a separate public repository

**Comment by jim-sheldon** [comment]
I will keep the repo private pending stakeholder feedback and further requirements gathering.

**Comment by jim-sheldon** [comment]
Moving geocoding to #2700 and data cleaning and ID assignment to #2701
