### ISSUE TITLE
Set up G.h cluster/compute for Monkeypox-tailored services

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/list#2703]
At present the G.h Monkeypox system works using (largely) Google Sheets. Instead, it should run as a set of containerized services. To do this, we need a k8s cluster and supporting AWS services (terraformed elsewhere for Covid-19 and turnkey infra).

**Comment by ksewalk** [comment]
Blocked - we need the curator UI updated

**Comment by jim-sheldon** [comment]
Not needed for automated curation
