### ISSUE TITLE
Parametrise disease name

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2712]
Parametrise disease name (which is currently set to covid-19) to make it easy to start up new line list instances.

**Comment by jim-sheldon** [comment]
This is related to https://github.com/globaldothealth/monkeypox/issues/21. It might be better to work with the script in the Monkeypox repo, since that is certainly closer to a Minimum Viable Product.

**Comment by abhidg** [comment]
Both products need parametrization:

1. One is a transformed dataset from a private Google spreadsheet, with a corresponding map. This dataset should also ideally be behind a ToS/privacy policy and require authentication to access (it's not right now, but there are no substantial differences in the privacy requirements between this and product 2). It'll also have associated map viz. There will be no support for adding additional sources, this product would only be for first N cases (let's say 10000 but could be higher depending on curator availability), this is https://github.com/globaldothealth/monkeypox/issues/21

3. Product corresponding to this repo, which supports multiple sources and more complex data schemas. The dataset from 1, can be bulk uploaded / inserted as was the case when the COVID-19 line list transitioned.

It's worthwhile to parametrize disease in this repo as well, since we might soon have to support restricted sources / more complex schemas, if not for the current monkeypox outbreak, but for the next pathogen. Partners may also want to try the full-fledged version for something other than COVID-19.

**Comment by iamleeg** [comment]
Calling this done, with the following work covered by other issues:

1. the database setup script, default database names, data-service model, and OpenAPI schema are all still coupled to the COVID-19 case schema. Issues #2714, #2715, #2704, and #2725 relate to supporting a different database with a different schema.
2. Terms of Use have some specific citations and statements about the COVID-19 data: these need rewriting anyway (#2675) so we can work out how to load the new terms of use when we have them.
