### ISSUE TITLE
Split out ingestion scripts into covid19-ingestion

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#2713]
Currently globaldothealth/list contains covid-19 ingestion scripts. With #2712, we'll no longer be catering to only one disease, so it makes sense to move ingestion scripts into separate repo, one for each for disease/pathogen.

**Comment by jim-sheldon** [comment]
This is related to https://github.com/globaldothealth/monkeypox/issues/21, insofar as we need one generic script for any new disease.

**Comment by abhidg** [comment]
We'll need multiple scripts in general as government sources will not follow our schema.

**Comment by abhidg** [comment]
Not a priority right now, will re-open when we are setting up new turnkey system.
