### ISSUE TITLE
Add Monkeypox to Landing Page Navbar

### ISSUE THREAD

**Issue by maciej-zarzeczny** [globaldothealth/list#2760]
Based on the design: https://www.figma.com/file/CAPeN2qSKoxUYva461b40p/Global-Health?node-id=1679%3A53304

**Comment by joe-brilliant** [comment]
Will aim to get sign off from leads early next week cc: @ksewalk

**Comment by joe-brilliant** [comment]
This can be closed once we push new Nav bar to prod

**Comment by abhidg** [comment]
New Nav bar is in prod
