### ISSUE TITLE
Add button to share the data (selected data in app should be stored in url)

### ISSUE THREAD

**Issue by OskarKocjan** [globaldothealth/list#2794]
dev link: https://dev-map.monkeypox.global.health/country

**Comment by joe-brilliant** [comment]
@OskarKocjan @maciej-zarzeczny please post links to test on Dev

**Comment by OskarKocjan** [comment]
Before adding the share button: 

![Image](https://user-images.githubusercontent.com/63292127/187967820-2a731164-d578-4e88-8676-90f9cc5e53ed.png)

![Image](https://user-images.githubusercontent.com/63292127/187967829-cee1b412-a7e8-485e-8d0e-8accd9685224.png)

After adding the share button:

![Image](https://user-images.githubusercontent.com/63292127/187967897-9d01feae-812e-4da0-9e21-21489cc7461d.png)


![Image](https://user-images.githubusercontent.com/63292127/187967910-333a3bcd-d39b-400b-94b1-2ab62667a30a.png)
