### ISSUE TITLE
Add 7 day rolling average to the chart

### ISSUE THREAD

**Issue by OskarKocjan** [globaldothealth/list#2795]

**Comment by OskarKocjan** [comment]
Dev link to test: http://dev-map.monkeypox.global.health.s3-website.eu-central-1.amazonaws.com/chart

Old look: 
![Image](https://user-images.githubusercontent.com/63292127/186896921-cb4457ca-aeb0-4f09-bea5-d03cdc1b51ad.png)

New look:

![Image](https://user-images.githubusercontent.com/63292127/186896994-d7230800-bc42-4ec4-8229-c5aa0e39e93b.png)

**Comment by abhidg** [comment]
Done, thanks @OskarKocjan!
