### ISSUE TITLE
Location field does not support county-level lookup in the US.

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#426]
Location field does not support county-level lookup for the US.
This is a standard expectation to be able to enter the county (in the US) in which a case is occurring.
“In the United States, having county level data is critical”

**Comment by attwad** [comment]
Still waiting Jared's for this, he sent an email to their mapbox contact and we're awaiting a reply.

**Comment by JaredHawkins** [comment]
Hey all!  I haven't heard back from Mapbox.  I have a follow-up email set to go out this afternoon if I still haven't heard back.

**Comment by sratcliffe118** [comment]
Hi Jared, any update here, this is a key blocker for our first milestone

**Comment by JaredHawkins** [comment]
They said: "Sounds like we do not currently have counties as a returnable data type in the US. If you have a counties layer then you could do a spatial join to extract that information for your current dataset."  I know that Mapbox has county layer(s), and followed up asking if we can speak to an engineer on their recommended work around - but I haven't heard back yet.

**Comment by JaredHawkins** [comment]
Mapbox says:

> If you are using the points returned from the geocoder AND you have a county tileset then I would recommend that you try using our Tilequery API. You can pass the lat/long coordinates to our Tilequery API to retrieve the county name.
> 
> Tilequery information
> 
> - Documentation: https://docs.mapbox.com/api/maps/#tilequery
> - Tutorials:
> 
> - https://docs.mapbox.com/help/tutorials/create-a-timezone-finder-with-mapbox-tilequery-api/
> 
> - https://docs.mapbox.com/help/tutorials/tilequery-healthy-food-finder/#add-the-tilequery-api
> 
> Hope this helps!

I've asked them if there is an existing Mapbox tileset for county (I believe there is), and am awaiting more info.  They have confirmed that county is not returned for US, and I'm also waiting on some more clarity as to why that is the case.

**Comment by JaredHawkins** [comment]
OK, I just had a nice talk with Mapbox.  This sums it up:

> Counties are not available in our geocoder because they are tied directly to our Mapbox Boundaries product. This is a bit frustrating, I know, but it's one of our high-value products. Counties are a fairly easy geospatial file to track down. I can talk to the team about opening up access to boundaries for your map, but it might just be easier to upload your own tileset to Mapbox. I usually get my US data from the [census website](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2019&layergroup=Counties+%28and+equivalent%29) (tigerline files). I've attached the 2019 county shapefile from the site, as well as a file named `US_County.mbtiles`. I used [Tippecanoe](https://github.com/mapbox/tippecanoe) to create the mbtiles so that the counties are visible at every zoom level. The recipe for creating a `Continuous polygon features (states and provinces), visible at all zoom levels`. 

I have the files she mentions - @sratcliffe118 who is best to take a look?  Alternatively to using the Tilequery API, we could just use these shapefiles to do our own local lookup (for the US) to see what county any given point falls in.  I'd imagine that would be straightforward.

**Comment by JaredHawkins** [comment]
As a follow-up, if we feel that we really need Mapbox Boundaries (https://www.mapbox.com/boundaries/), lets regroup.  We can definitely ask this of Mapbox, as long as we articulate why we need this product vs a the layer approach (either via mapbox or locally).

**Comment by sratcliffe118** [comment]
@allysonjp715 is this something you can look at while Tim is out, or should we park this US requirement until Tim is back and pivot to some other countries.

Note @axmb I don't see any reason not to test the bulk entry with ohio data but we will have to limit location to state and not county level

Thoughts?

**Comment by allysonjp715** [comment]
Tim is the one who has been doing all the mapbox integration so he'd certainly be more familiar with it. Is 1.5 weeks too long to wait? I can take a deeper read into this tomorrow or Friday and see if I can pick it up.

**Comment by sratcliffe118** [comment]
@allysonjp715 I think we are good to wait for Timothe to return, we can pivot to other geo's in the short term so we are not blocked

**Comment by dakrownie** [comment]
@attwad Welcome back!
This is an open issue with the MapBox API. PTAL.

**Comment by attwad** [comment]
Hmm so we're in the same position as when I left, we already had identified the counties in the tileset API but optimally we wouldn't have to do two queries (or even upload our own tileset!) that's quite frustrating...
I could look into doing that tileset query as mentioned in Jared's comment from mapbox engineers, if it turns out too cumbersome we'll have to figure another way out.

**Comment by dakrownie** [comment]
Thanks Tim! Please let me know if you need me to do anything.

**Comment by attwad** [comment]
We have to account for the fact that no geocoder will have 100% recall (and no 100% precision either), so I made the Location part of the form editable: if the mapbox geocoder fails one can enter the location manually as it was done previously in the sheets system.

Another way to do things when no results are given by the geocoder: one can also now try something in the vicinity and then fix the fields that are not exactly what they wanted them to be (name for example).

I consider this bug fixed, there is still an open question of batch geocoding in https://github.com/globaldothealth/list/issues/622 when no results are found.
