### ISSUE TITLE
Symptoms: Show the most relevant symptoms for the disease as a quick selection option

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#439]
See attached UX
<img width="305" alt="Screen Shot 2020-07-03 at 11 24 26 AM" src="https://user-images.githubusercontent.com/63205311/86460276-fd540800-bd1f-11ea-90ee-bc99940a69b8.png">

**Comment by allysonjp715** [comment]
Do we want these to be a reflection of the most commonly used symptoms in the DB? Or shall we hard code some in that we know are common to COVID?

**Comment by acansler** [comment]
I think it would be appropriate to make them for Covid. Otherwise, we will likely see a lot of searching for those, and given that there are multiple forms of "cough", this may improve data consistency.

**Comment by shroothless** [comment]
I would say they should be the most commonly used symptoms in the DB and not hardcoded. Also I think this is a nice to have since likely behaviour.

**Comment by sratcliffe118** [comment]
Yes lets go with the most commonly used symptoms in the DB, no hardcoding
