### ISSUE TITLE
New field in the schema: Events section: Case Status

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#457]
A number of sources provide details of suspected cases based on symptoms and clinical diagnosis e.g. Argentina

Here a line list case is logged based on symptoms displayed or a clinical diagnosis. After such a time an PCR test is run to verify and it can be found to be negative or no test is run or available so the status remains suspected and can never be moved to confirm.

To support this we will look at add another field to the schema in the events section, to be located after method of confirmation:

Field title: Case Status
Options from a list: Suspected, Confirmed, Discarded, Unknown

Updated: Line List schema:
https://docs.google.com/spreadsheets/d/1qOnGJQg1gtbmNxAW8c9hC1TvFpIQmSnORD-x-iXrpJ0/edit?usp=drive_web&ouid=100301246100161861605

**Comment by outbreakprepared** [comment]
A couple of additional categories below:

Confirmed
Suspected
Probable
Discarded
Negative
Unknown

**Comment by allysonjp715** [comment]
Should we then change "confirmation date" and "method of confirmation" to no longer be required?

**Comment by sratcliffe118** [comment]
@outbreakprepared 
Thinking more about this, it's a significant scheme change as currently our working assumption is the dataset ONLY includes positive cases of covid-19, this change would mean that some cases would now be confirmed as negative and not covid-19 cases.

I propose a discussion on the priority and value of this against the other streams to assess if we want to prioritize this specific support feature

**Comment by sratcliffe118** [comment]
Adding to feature backlog
