### ISSUE TITLE
Mexico case data automatic importer

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#480]
https://www.gob.mx/salud/documentos/datos-abiertos-152127

**Comment by outbreakprepared** [comment]
Data are at the municipality level but municipality ID's are non-unique and have to be matched with state ID's. You can find a lookup table in the "Diccionario de Datos" that can be downloaded on the same webpage.

**Comment by axmb** [comment]
We ran into a little error today while backfilling:

```
2020-09-30T11:28:55.242-04:00Copy[ERROR] KeyError: '09106'Traceback (most recent call last):  File "/var/task/mexico.py",
line 201, in lambda_handler    return parsing_lib.run_lambda(event, context, parse_cases)  File "/opt/python/parsing_lib.py",
line 293, in run_lambda    common_lib.complete_with_error(  File "/opt/python/common_lib.py",
line 98, in complete_with_error 
[...]
File "/var/task/mexico.py", line 39, in convert_location     query_list.append(_MUNICIPALITIES[state_code + municipality_code])
-- | --
```

Should we add a catch for lookups that aren't found in the dictionary, @calremmel ?

**Comment by z023** [comment]
Any updates? Still getting an error with ingestion.

**Comment by calremmel** [comment]
Just submitted a PR that deals with the case of a missing location code!

**Comment by iamleeg** [comment]
@calremmel still seeing a similar error today:

        {
            "timestamp": 1603162939470,
            "message": "[ERROR] KeyError: '08113'\nTraceback (most recent call last):\n  File \"/var/task/mexico.py\", line 201, in lambda_handler\n    return parsing_lib.run_lambda(event, context, parse_cases)\n  File \"/opt/python/parsing_lib.py\", line 307, in run_lambda\n    common_lib.complete_with_error(\n  File \"/opt/python/common_lib.py\", line 98, in complete_with_error\n    raise exception\n  File \"/opt/python/parsing_lib.py\", line 292, in run_lambda\n    count_created, count_updated = write_to_server(\n  File \"/opt/python/parsing_lib.py\", line 120, in write_to_server\n    batch = batch_of(cases, cases_batch_size)\n  File \"/opt/python/parsing_lib.py\", line 104, in batch_of\n    batch.append(next(cases))\n  File \"/opt/python/parsing_lib.py\", line 230, in <genexpr>\n    return (case for case in case_data if case_is_within_range(case, cutoff_date, op))\n  File \"/opt/python/parsing_lib.py\", line 86, in prepare_cases\n    for case in cases:\n  File \"/var/task/mexico.py\", line 158, in parse_cases\n    \"location\": convert_location(\n  File \"/var/task/mexico.py\", line 39, in convert_location\n    query_list.append(_MUNICIPALITIES[state_code + municipality_code])",
            "ingestionTime": 1603162948495
        },

**Comment by calremmel** [comment]
@iamleeg This PR should be the solution: https://github.com/globaldothealth/list/pull/1311
I think everyone who is going to review it probably has. Any other steps before merging?

**Comment by iamleeg** [comment]
Nope, sorry, hadn't noticed it was still waiting on merge, I've done it (in general merging after review is fine, I often wait for a second opinion when I'm not very familiar with the code and then forget to press the button!)

**Comment by calremmel** [comment]
This is now working! Thanks to you all.

**Comment by z023** [comment]
@calremmel Mexico doesn't have UUIDs in the ingested data but isn't ID_REGISTRO the unique ID?

**Comment by calremmel** [comment]
UUIDs added!
