### ISSUE TITLE
Import Zurich (CH) case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#483]
https://github.com/openZH/covid_19/blob/master/fallzahlen_kanton_alter_geschlecht_csv/COVID19_Fallzahlen_Kanton_ZH_alter_geschlecht.csv

**Comment by attwad** [comment]
All's left is to setup the parser automation in prod.

**Comment by attwad** [comment]
Format changed, new data can be found at https://raw.githubusercontent.com/openZH/covid_19/master/fallzahlen_kanton_alter_geschlecht_csv/COVID19_Fallzahlen_Kanton_ZH_altersklassen_geschlecht.csv

I will fix the existing parser
