### ISSUE TITLE
Import Brazil—Goias case data 

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#489]
https://extranet.saude.go.gov.br/pentaho/api/repos/:coronavirus:paineis:painel.wcdf/generatedContent

**Comment by rahul18cracker** [comment]
I would like to claim and work on this, seems to me google translate can do the trick almost for this one

**Comment by rahul18cracker** [comment]
Hi @AnyaLindstromBattle 

I was caught up in the local setup for this, now i am able to start injestion function and start the parsing part. Before i start work on this in the git repo just wanted to make sure that you have not committed it ?

If yes then i will claim some other issue 

Thanks
~Rahul

**Comment by AnyaLindstromBattle** [comment]
Hi Rahul :) Yes, I have basically finished the Goias parser so if you could tackle something else that would be great. We were trying to bash out all the Brazil ones hence why I poached it from you!

**Comment by rahul18cracker** [comment]
Hi @AnyaLindstromBattle 

Thanks for the confirmation, i would switch to something else. I am very new to this, have a basic question. This is a HTML page and i see the retrival function extract data from json URl's or CSV URl's. How did you do this HTML case without using BeautifulSoup or Selenium type tools ?

Can you please point me to your code ? 

Thanks
~Rahul
