### ISSUE TITLE
Import Brazil—Amapa case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#495]
http://painel.corona.ap.gov.br/

**Comment by iamleeg** [comment]
Now seeing this parser fail because:

        {
            "timestamp": 1603195548415,
            "message": "[ERROR] KeyError: 'start'\nTraceback (most recent call last):\n  File \"/var/task/amapa.py\", line 180, in lambda_handler\n    return parsing_lib.run_lambda(event, context, parse_cases)\n  File \"/opt/python/parsing_lib.py\", line 307, in run_lambda\n    common_lib.complete_with_error(\n  File \"/opt/python/common_lib.py\", line 98, in complete_with_error\n    raise exception\n  File \"/opt/python/parsing_lib.py\", line 292, in run_lambda\n    count_created, count_updated = write_to_server(\n  File \"/opt/python/parsing_lib.py\", line 120, in write_to_server\n    batch = batch_of(cases, cases_batch_size)\n  File \"/opt/python/parsing_lib.py\", line 104, in batch_of\n    batch.append(next(cases))\n  File \"/opt/python/parsing_lib.py\", line 230, in <genexpr>\n    return (case for case in case_data if case_is_within_range(case, cutoff_date, op))\n  File \"/opt/python/parsing_lib.py\", line 216, in case_is_within_range\n    case_date = get_case_date(confirmed_event[\"dateRange\"][\"start\"])",
            "ingestionTime": 1603195555677
        },

My reading is that the `parsing_lib` is trying to get the `case["event"]["dateRange"]["start"]` to compare with the filter criterion, and that the `start` key doesn't exist. @AnyaLindstromBattle is it possible that the source data has empty values for some cases in its `dataNotificacao` column, and that the parser creates an event without setting a date in those cases?

**Comment by iamleeg** [comment]
OK, I'm talking to myself, but this is indeed what's happening. There are rows in the database with the date "None 12:30:00" which the parser can't cope with. @Mougk @z023 what should happen in that case? Do we drop the cases? They have demographic and test information but no usable date.

**Comment by Mougk** [comment]
if no usable date, remove.

**Comment by iamleeg** [comment]
Ah, they've also changed their date format: the e2e test uses "2020-04-21T03:00:00.000Z" and the download now contains "2020-06-23 12:30:00". I can change that but it'll be a while as I replace @AnyaLindstromBattle's e2e test setup with a new one.

**Comment by z023** [comment]
There are quite a few different times. Is this problematic?

**Comment by iamleeg** [comment]
@z023 I just downloaded the CSV and all of the dates are in the format yyyy-mm-dd hh:mm:ss (and actually all of the specific times are 12:30:00): do you see something different? Maybe they change the formats fairly frequently.

**Comment by z023** [comment]
I just downloaded the CSV earlier and mostly they are T03:00:00 but I can see a fair few different times

![Screenshot 2020-10-20 at 18 44 36](https://user-images.githubusercontent.com/65172419/96624262-6a59d080-1304-11eb-8764-5884dccb3db9.png)

**Comment by iamleeg** [comment]
Ah, OK, I'll support both. Weird that we saw different formats in such a short time.

**Comment by AnyaLindstromBattle** [comment]
Hi both, thanks for working on this yday, was on holiday hence the radio silence from me. Working today though so ping me if anything.
