### ISSUE TITLE
Import Brazil—Sao Paolo case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#497]
https://raw.githubusercontent.com/seade-R/dados-covid-sp/master/data/dados_covid_sp.csv

**Comment by SandraAdele** [comment]
Error: Request failed with status code 500 when trying to add rate to AWS schedule box

**Comment by AnyaLindstromBattle** [comment]
Hey Sandra! I'm afraid I'm really not familiar with the curator portal setup, perhaps @z023 @iamleeg @calremmel could help you?

**Comment by calremmel** [comment]
Thanks, @SandraAdele ! These issues are really only for problems with the parsing code, not really for problems with the curator portal. For those, it's best to get in touch with @z023 to see how she has solved it before, or open a new issue specifically for the error so we can work on it as a team.

For this, I'd suggest opening a new issue, calling it something "Status code 500 when trying to add rate to AWS schedule box," and tagging me, @z023 , and @iamleeg .

**Comment by z023** [comment]
@calremmel I have looked back at when this type of error message has come up before and I think, as with most of the Latin America sources, it needs more memory.
