### ISSUE TITLE
Import Estonia case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#502]
https://opendata.digilugu.ee/opendata_covid19_test_results.csv

**Comment by attwad** [comment]
Description of dataset here:
https://www.terviseamet.ee/et/koroonaviirus/avaandmed

**Comment by attwad** [comment]
Needs to be setup in the UI now.

**Comment by z023** [comment]
The Estonia source lists all people tested so includes both those who were positive and negative so would need to be able to identify those who were positive and negative??
Also the Estonia CSV file when opened is changing some of the age ranges into dates, e.g. age 5-9 is coming through as 5-Sept. This might just be excel when opening and there isn't actually a problem with the file.

**Comment by attwad** [comment]
Yes only positive cases are imported. And ages should be parsed correctly as well.

**Comment by Mougk** [comment]
Ok, will add feature request to add negatives but that can wait until October.

**Comment by attwad** [comment]
Why? The list has always been about only positive cases, not a list of all test data. Did something change about that recently?

**Comment by attwad** [comment]
FTR we have no way of storing negative tests results in the schema, only positive cases.

**Comment by allysonjp715** [comment]
We have an issue about non-positive cases already: #457

**Comment by Mougk** [comment]
Thanks @allysonjp715 @attwad !

**Comment by z023** [comment]
Estonia is set up but isn't being ingested.

**Comment by attwad** [comment]
The parser is a CSV parser but it was setup with a JSON source, I've changed the URL to be https://opendata.digilugu.ee/opendata_covid19_test_results.csv, should be ingested in next run, feel free to trigger it yourself if you want before that.
