### ISSUE TITLE
Import Colombia case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#504]
https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data

**Comment by axmb** [comment]
@fojackson8 -- Zoe and I hit an issue backfilling Colombia data.

Seems we're inadvertently leaving out the location from the parsed case -- mind TAL?

https://github.com/globaldothealth/list/blob/main/ingestion/functions/parsing/colombia/colombia.py#L41
