### ISSUE TITLE
Import New Zealand case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#509]
https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-current-situation/covid-19-current-cases/covid-19-current-cases-details

**Comment by abhidg** [comment]
Source URL: https://www.health.govt.nz/system/files/documents/pages/covid_cases_{YYYY}-{MM}-{DD}.csv

Data is at DHB (district health board level). There are 20 of them: https://www.health.govt.nz/new-zealand-health-system/key-health-sector-organisations-and-people/district-health-boards/location-boundaries-map
