### ISSUE TITLE
Import Thai case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#516]
daily dump: https://data.go.th/en/dataset/covid-19-daily
API: https://covid19.th-stat.com/th/api

**Comment by z023** [comment]
Location.name is in English but location.admins are not being translated.

**Comment by attwad** [comment]
I just fixed that an hour ago, please drop Thai data and reimport it will have English names.

**Comment by z023** [comment]
There are still Thailand location.admins not being translated.

**Comment by attwad** [comment]
After dropping and reimporting data, all admins seem to be translated (I've looked at 10 random pages).

**Comment by z023** [comment]
There are 2 cases which are the same case ID duplicated (source case ID 3219), coming through with an Austria location. The original source states their nationality is Egyptian and possibly the positive detection location is unknown?

**Comment by attwad** [comment]
Those are the 3 cases:
https://curator.ghdsi.org/cases/view/5f61cbe70142a772cba2df0f
https://curator.ghdsi.org/cases/view/5f61faf00142a772cba59d79
https://curator.ghdsi.org/cases/view/5f6858bccb263be4ff56b244

the raw entry is:

```json
{"ConfirmDate":"2020-07-13 00:00:00","No":"3219","Age":43,"Gender":"\u0e0a\u0e32\u0e22","GenderEn":"Male","Nation":"Egypt","NationEn":null,"Province":"\u0e44\u0e21\u0e48\u0e1e\u0e1a\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25","ProvinceId":78,"District":"\u0e40\u0e21\u0e37\u0e2d\u0e07","ProvinceEn":"Unknown","Detail":null,"StatQuarantine":1}
```

pretty printed:
```
Age: 43
ConfirmDate: "2020-07-13 00:00:00"
Detail: null
District: "เมือง"
Gender: "ชาย"
GenderEn: "Male"
Nation: "Egypt"
NationEn: null
No: "3219"
Province: "ไม่พบข้อมูล"
ProvinceEn: "Unknown"
ProvinceId: 78
StatQuarantine: 1
```

The geolocation query that gets done with this case is
"เมือง, Unknown, Thailand"

and that "Unknown" seems to confuse the hell out of mapbox which gives us a randon location each time... 
![image](https://user-images.githubusercontent.com/1255432/94109876-ef56e480-fe41-11ea-8e97-e5176ffda38c.png)

I will have to filter out those "Unknowns" and use the Thai province name which was available instead.

**Comment by attwad** [comment]
I've deleted the two cases, they will be reimported correctly on next ingestion run.
