### ISSUE TITLE
Import Taiwan case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#517]
https://data.cdc.gov.tw/en/dataset/agsdctable-day-19cov

**Comment by attwad** [comment]
https://data.cdc.gov.tw/en/download?resourceid=3c1e263d-16ec-4d70-b56c-21c9e2171fc7&dataurl=https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.csv

**Comment by attwad** [comment]
Dataset seems to be only in Chinese, let's see how mapbox copes with that.

**Comment by attwad** [comment]
License is: http://data.gov.tw/license

**Comment by attwad** [comment]
Needs to be setup in the UI now.

**Comment by z023** [comment]
Unique case IDs are not coming through in the line list and some location.admins not being translated. 
Too many cases so possibly duplication??

**Comment by attwad** [comment]
There are no unique case IDs provided for Taiwan, most of the case data do not have a finer location granularity than "Taiwan" and the admins are now all translated (I had to drop all of them first to properly get the English translation this time).

**Comment by z023** [comment]
Taiwan should have unique case IDs according to this: https://data.cdc.gov.tw/en/dataset/agstable-19cov/resource/27ed0b70-c28f-4a44-8a1b-ef13e487ed20

**Comment by attwad** [comment]
Unfortunately no, this is just the web widget that they use to display a CSV that adds row ids incrementally but the data set itself looks like this:

```
確定病名,個案研判日,縣市,性別,是否為境外移入,年齡層,確定病例數
嚴重特殊傳染性肺炎,2020/01/22,空值,女,是,55-59,2
...
```

it doesn't have unique ids.

**Comment by z023** [comment]
Ok, @attwad could you delete all the Taiwan cases currently in the line list and I'll set up a back fill.

**Comment by attwad** [comment]
There are only 2k cases for Taiwan, as a curator you should be able to search by country:Taiwan and delete them all, let me know if you encouter any hicups

**Comment by z023** [comment]
Ah yes I've just checked there aren't that many. Thanks.

**Comment by Mougk** [comment]
@AnyaLindstromBattle cases noted as 'immigrant' are currently not considered to have travel history. From my understanding in the raw data these are imported cases and should probably be labeled as such. Can you take a look?

**Comment by AnyaLindstromBattle** [comment]
@Mougk you wouldn't happen to know if there was a data dictionary? I assume when you say you want to add travel history you mean that traveledPrior30Days == "Yes" but in the absence of a data dict I can't tell for sure that 'immigrant' means the case travelled in the last 30 days.

**Comment by Mougk** [comment]
I don't but am reasonably sure that's what it means. cc @outbreakprepared for information.

**Comment by AnyaLindstromBattle** [comment]
@Mougk OK will tackle this now
