### ISSUE TITLE
Import Hong Kong case data

### ISSUE THREAD

**Issue by iamleeg** [globaldothealth/list#518]
https://data.gov.hk/en-data/dataset/hk-dh-chpsebcddr-novel-infectious-agent/resource/12b0e451-9ee4-439f-9807-0ab684404fc6

**Comment by attwad** [comment]
Static URL is: http://www.chp.gov.hk/files/misc/enhanced_sur_covid_19_eng.csv

**Comment by attwad** [comment]
All's left is to setup the parser automation in prod.

**Comment by Mougk** [comment]
Original data have information of whether the case was imported vs. local. This information is stored in notes. It should also be added to the travel history field.

<img width="671" alt="Screenshot 2020-09-12 at 22 30 04" src="https://user-images.githubusercontent.com/8478551/93013246-e5fa8c00-f5a6-11ea-8d05-2d35962864bc.png">

Original file example: 
"4,24/01/2020,23/01/2020,F,62,,Discharged,Non-HK resident,Imported case,Confirmed"

**Comment by Mougk** [comment]
Another note that will need reviewing on this parser: 

There is an additional file provided via API from the HK Government that has more information about the location of the cases. Specifically the districts will be relevant as they are Admin 3 regions. There are matching ID's for many of the cases so should be easy to map this file against the HK case doc.

Example of file is below and can be found for last two weeks here: https://www.chp.gov.hk/files/misc/building_list_eng.csv
<img width="892" alt="Screenshot 2020-09-13 at 11 02 52" src="https://user-images.githubusercontent.com/8478551/93014347-b94b7200-f5b0-11ea-9d4e-ea9af5d1c1b4.png">


Historical data can be downloaded via a number of API links here: https://data.gov.hk/en-data/dataset/hk-dh-chpsebcddr-novel-infectious-agent/resource/50b8852f-837d-40a0-9b5c-9eed949d2694

<img width="1033" alt="Screenshot 2020-09-13 at 11 04 02" src="https://user-images.githubusercontent.com/8478551/93014368-d8e29a80-f5b0-11ea-946b-806d0ace2816.png">

**Comment by attwad** [comment]
I've sent a PR to consider "imported case" as having traveled in the past 30 days, that sounds reasonable.
I got freaked out by the fine grained detail of the other data set though, going at the admin3 level sounds reasonble but that last link has Residential building level data with "2 or more probable/confirmed cases", from a privacy standpoint that sounds totally untenable.

**Comment by Mougk** [comment]
Merged PR on imported cases. 

I think admin3 is still useful. Not sure who is best place to implement @attwad @sratcliffe118

**Comment by sratcliffe118** [comment]
Agree with @attwad we should not be including Residential building level data in any data. 
@attwad any thoughts on how we can bring in the Admin 3 data. I know this it moving beyond scope for MVP but if we have thoughts good to document here.

**Comment by attwad** [comment]
This is definitely out of MVP but a very good feature request nonetheless, I've filed https://github.com/globaldothealth/list/issues/1104 to track that.

**Comment by sratcliffe118** [comment]
HK data available in prod
