### ISSUE TITLE
Format of the date and time fields in the line list

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#532]
Format of the data and time is hard to read in the line list. We need to standardize across each field in the UI.
![Screen Shot 2020-07-13 at 1 41 27 PM](https://user-images.githubusercontent.com/63205311/87305669-c72c3a80-c50e-11ea-8073-86692338fec9.png)

**Comment by allysonjp715** [comment]
Any suggestions on the desired format?

**Comment by sratcliffe118** [comment]
YYYY-MM-DD
with the standard timezone we use BST / GMT / EST

**Comment by allysonjp715** [comment]
With that last PR dates are in the local timezone rather than UTC, we should change them to be standard UTC so they don't change when viewing in different timezones.

**Comment by sratcliffe118** [comment]
Good point @allysonjp715 

@scarpino @outbreakprepared to confirm using UTC as the standard timezone in the data

**Comment by attwad** [comment]
Yes always use UTC please, although really in our case we don't go to the hour granularity when reporting cases so there should be little difference.

**Comment by scarpino** [comment]
I agree. UTC.
