### ISSUE TITLE
Determine which columns to show in the linelist

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#551]
Open question for discussion.

What fields do we want the summary line list tab view to show the curator for find, edit and delete CUJs

**Proposal: default table view to display the line list case data in on the Line list view tab. This will be the screen which supports the find, edit and delete use cases.**

**Table columns** 
1. Unique identifier - @attwad @axmb thoughts to creating a line list case number for each unique identity. @acansler from research do we feel there is a need for this?
2. Date of creation
3. Source name
4. Location (admin 3)
5. Location (admin 2)
5 Country (Admin 1)
5. Age
6. Gender
7. Outcome

**Comment by sratcliffe118** [comment]
Unique identifier @allysonjp715 also thoughts on this?

**Comment by allysonjp715** [comment]
We previously discussed a unique identifier being useful if people want to discuss a case among themselves (e.g. "Case #abc looks like it has an error, could you check it out?"). Could also help when deduping to have an identifier for a case. But I definitely defer to @acansler, Lauren, and other curators.

**Comment by outbreakprepared** [comment]
+1 Allyson's comment and reasoning behind why its useful to have a unique identifier. Also, unique identifiers in source may not be stable.

**Comment by sratcliffe118** [comment]
Agree, let's see if there is value and a use case for one.

**Comment by lagood1** [comment]
+1 Allyson and Moritz's thoughts on having a unique identifier, it definitely will be helpful for internal conversations about cases

I also think case confirmation date would be a valuable column to display for quick browsing. (Open for discussion here or other thoughts)

**Comment by allysonjp715** [comment]
Recently remembered that we'll need to surface the case ids in the linelist because in the new case entry flow we have an input for "linked case ids".

**Comment by sratcliffe118** [comment]
Can we lock in the requirement for Case IDs as a decision here, I think the curator experience both for input / discussing specific cases and linking cases are strong enough for this to be supported

**Comment by allysonjp715** [comment]
Yes we're currently showing Case IDs and plan to keep it. Other table columns in the Linelist are still up for discussion AIUI.

**Comment by lagood1** [comment]
I think the columns proposed earlier work.. interested to know what @outbreakprepared thinks. Thanks!

**Comment by sratcliffe118** [comment]
Current proposal for MVP, data fields to show in the line list default view

@outbreakprepared any additional feedback, or we will lock this in

Date of creation
Source name
Location (admin 3)
Location (admin 2)
Country (Admin 1)
Age
Gender
Outcome

**Comment by allysonjp715** [comment]
Is "Date of creation" the date they entered the case into our linelist or should it be "Date of confirmation" i.e. when the case was confirmed to have the disease?

I assume we are keeping the linelist ID in that list of columns?

**Comment by sratcliffe118** [comment]
Date of confirmation should be the key date we use here

I assume we are keeping the linelist ID in that list of columns? Yes
