### ISSUE TITLE
Help Copy: Manual data entry form for line list

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#562]
Help copy data matrix for the line list case manual data entry form

https://docs.google.com/spreadsheets/d/1mPYrNaO799ZDSTEgCn2WSHEGlwYYxuG2MG9t5TGpN0E/edit?usp=drive_web&ouid=100301246100161861605

**Comment by allysonjp715** [comment]
Could we add copy for New Case Entry sections? @shroothless said we want tooltips for sections rather than fields.

**Comment by sratcliffe118** [comment]
Put the help copy into sections here: https://docs.google.com/spreadsheets/d/1mPYrNaO799ZDSTEgCn2WSHEGlwYYxuG2MG9t5TGpN0E/edit#gid=316665458

**Comment by allysonjp715** [comment]
The sections that need tooltips can be found here:
https://github.com/globaldothealth/list/blob/main/verification/curator-service/ui/src/components/CaseForm.tsx#L822

And the tooltips can be added to the FieldTitle elements within the sections, e.g. https://github.com/globaldothealth/list/blob/main/verification/curator-service/ui/src/components/common-form-fields/Source.tsx#L33

**Comment by allysonjp715** [comment]
Related: #932

**Comment by sergioloporto** [comment]
@joe-brilliant can we please have a review of what is in this document? https://docs.google.com/spreadsheets/d/1mPYrNaO799ZDSTEgCn2WSHEGlwYYxuG2MG9t5TGpN0E/edit#gid=0

**Problem 1:**
I already started to fix the tooltips text according to this document. However in many places there are so many mispelling/wrong syntax, etc... uncorrect English language used.

Where I was sure I put the changes to the code.
Where I saw something wrong or potentially wrong I added a comment on **column F**. For now I worked it up to **row 19**.

**Request:**
- Can anybody please check my comments and reply to the with the fixed final version that should appear in the tooltips?
- Can someone please check from row 20 inclusive to the bottom to check other English mistakes?



**Problem 2**
The tooltip in the "event" section is too high for most resolutions/monitors.

Possible resolutions, please suggest:
- Either we shorten the texts for the Event section, or
- We increase the width of all tooltips (for consistency), for example of 50-100px

![image](https://user-images.githubusercontent.com/51946947/105505714-956c0b80-5cc9-11eb-82bb-6b5de64b9b80.png)


Please let me know asap

**Comment by zbigiman-htd** [comment]
Add Problem 2 @sergioloporto Is it possible to set auto width for tooltips? 
```
min-width: corrent with value;
width: "auto"
max-width: "90vw" - or something like that
```

**Comment by joe-brilliant** [comment]
Thanks for the detailed updates @sergioloporto! I'll take a look next week but as this appears for curators only it can take lower priority vs. any issues that affect general users.

**Comment by WeronikaMichaluk** [comment]
@Mougk
