### ISSUE TITLE
Import India case data

### ISSUE THREAD

**Issue by axmb** [globaldothealth/list#563]
https://api.covid19india.org/

Note that the required fields from this data are already populated in the [example India parser](https://github.com/open-covid-data/healthmap-gdo-temp/tree/master/ingestion/functions/parsing/india).

We'll need to add remaining fields, and make sure the parser works for all of the `raw_dataN` data files.

**Comment by z023** [comment]
@axmb Is the India parser changed to CSV?

**Comment by axmb** [comment]
Yep! I've just now pushed [an update](https://github.com/globaldothealth/list/pull/1245) including transitioning it to CSV.

**Comment by axmb** [comment]
Before we backfill, I've bounced one last data quality question off Moritz in #1275.
