### ISSUE TITLE
Mapbox missing key location data in the UK

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#572]
Mapbox has spotty coverage of Admin level 3 data such as Districts / Councils and Boroughs (specifically for London)

As an example the London boroughs of Southwark, Westminster and Kensington and Chelsea, 3 of the biggest areas are missing completely from the MapBox autocomplete options. This is on top of the USA county level issues we have run into.

I propose we meet to discuss this item with Timothe when back next week, as we will need to make a call on how we want to proceed urgently.

**Comment by sratcliffe118** [comment]
**Summary of issues**

**England**
- Missing London Borough information: Westminster, Southwark, Lambeth, Tower Hamlets, Hammersmith and Fulham, Richmond upon Thames
- Missing district level data: Example, Ribble Valley
- Mixed regions coverage: 
Included: West Midlands, London
Not included: South West, South East, East of England, East Midlands. Yorkshire and The Humber, North West, North East

**USA**
No county level data

**Comment by attwad** [comment]
I am back, this is similar to #426 hopefully the tileset/boundaries APIs can give us that information, I should have more clarity on it after I got a bit more familiar with those.

**Comment by attwad** [comment]
Ah that's actually different, there are NO results at all for southwark, london. That's problematic indeed and the tileset API wouldn't help at all... We can:
1. ask mapbox folks why there are no London Boroughs in their data
2. figure out a way for curators to manually provide geocoding information when there are no results
3. plug-in another geocoder as fall-back method

@JaredHawkins could you please send an email to your mapbox contacts asking why they are missing that data? (1)

in the meantime I can quickly draft a component to submit geolocation information (2) and we can think about (3) later.

**Comment by JaredHawkins** [comment]
@attwad @sratcliffe118 Happy to email Mapbox, but can you give me a bit more info (and maybe some example queries)?  And can you please confirm if you have also looked at the Boundaries API for the same locations?  Thanks!

**Comment by attwad** [comment]
Stefen summarized the issue in https://github.com/open-covid-data/healthmap-gdo-temp/issues/572#issuecomment-659549805, I also checked that searching for "Southwark" in their geolocation api playground didn't return the Borough as expected so this is unrelated to us using the permanent places API endpoint.

This is also unrelated to the boundaries API, we would use the boundaries API to get the right admin levels for a given point but here we don't even have a point.

**Comment by JaredHawkins** [comment]
I saw Stephens comment, but I don't understand.  Are you searching for a Borough and getting 0 results?  If you search for other locations within the Borough, does that work?  If so, is any Admin 3 (I think that is Borough) info returned?  Is all of this true with districts too (I don't really understand the difference between the two)?  I also don't understand the mixed regions breakdown comment.  

Also, out of curiosity - is data reported at the Borough level?  What is the use case here?

**Comment by attwad** [comment]
Correct, searching for "Southwark, London" gives no usable results.
![image](https://user-images.githubusercontent.com/1255432/87931307-de78a400-ca89-11ea-81bc-035d204c5cc0.png)

Even the first result in there (the station) doesn't have Borough information in its context:
```
"context":[
{"id":"postcode.903207452626700","text":"SE1 8JZ"},
{"id":"locality.10168116354885890","text":"Cathedrals"},
{"id":"place.8780954591631530","wikidata":"Q84","text":"London"},
{"id":"district.14664713661976620","wikidata":"Q23306","text":"Greater London"},
{"id":"region.13483278848453920","short_code":"GB-ENG","wikidata":"Q21","text":"England"},{"id":"country.12405201072814600","wikidata":"Q145","short_code":"gb","text":"United Kingdom"}]}
```

I can't speak for the usefulness of Borough information but I suspect if this bug was filed it means that some data is reported at that level.
I will let @sratcliffe118 comment on your other question given that I don't know what/where "Ribble Valley" is.

**Comment by JaredHawkins** [comment]
Thanks!  @sratcliffe118 can you also give me examples of other similar strings (same Admin level) returning results?

**Comment by sratcliffe118** [comment]
Sure:
Place 1: Lewisham, London, Greater London, England, United Kingdom
Place 2: London Borough of Barnet, Greater London, England, United Kingdom
Place 3: Hackney, London, Greater London, England, United Kingdom

**Comment by attwad** [comment]
We have to account for the fact that no geocoder will have 100% recall (and no 100% precision either), so I made the Location part of the form editable: if the mapbox geocoder fails one can enter the location manually as it was done previously in the sheets system.

Another way to do things when no results are given by the geocoder: one can also now try something in the vicinity and then fix the fields that are not exactly what they wanted them to be (name for example).

I consider this bug fixed, there is still an open question of batch geocoding in https://github.com/globaldothealth/list/issues/622 when no results are found.
