### ISSUE TITLE
Bulk CSV upload in progress: Progress bar / UI template

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#573]
Feature: UI pattern to show that a CSV bulk upload is in progress, e.g. upload progress bar / spinner / time left to upload. 

Currently: There is no indication that anything has happened or is taking place which caused me to click multiple times and think the process was broken.

Where: On the bulk upload CSV screen once the file has been submitted

**Comment by sratcliffe118** [comment]
Current UI has no indication as to state of the upload.

![Screen Shot 2020-07-16 at 5 57 10 PM](https://user-images.githubusercontent.com/63205311/87700159-cd7c1a00-c78d-11ea-9f5e-87d8ec7981e9.png)

**Comment by shroothless** [comment]
![image](https://user-images.githubusercontent.com/67452108/87727691-6fe8cd00-c78f-11ea-89f5-1e244619f2c9.png)
 Can we do this?

**Comment by axmb** [comment]
Yep! I implemented something similar earlier today. I'll submit that, and tweak/move that into position when I move the buttons.

**Comment by axmb** [comment]
To update: I'm working through #571 and once done will swing back to bring the bulk upload UI to spec (including this specific issue).
