### ISSUE TITLE
Rename org and repo

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#607]
We need to be Global.Health not open-covid-data and we need a repo name that is not temporary.

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization

https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

Happy to volunteer and break everyone once we have a repo name and are ready to go.

**Comment by dakrownie** [comment]
@attwad Who needs to make the decision on this?

**Comment by attwad** [comment]
Long term owners (so not us), perhaps Jared, Moritz and Spencer?

**Comment by dakrownie** [comment]
@JaredHawkins Please make the call or direct this to someone who can.

**Comment by JaredHawkins** [comment]
Moritz owns this repo, though perhaps we should have it transferred over to BCH as part of the handoff?

**Comment by dakrownie** [comment]
@mougk over to you.

**Comment by outbreakprepared** [comment]
did we make a final call here ?

**Comment by attwad** [comment]
as per slack poll, it will be `globaldothealth/list`, will prepare the changes now.

**Comment by dakrownie** [comment]
Thanks @attwad!
