### ISSUE TITLE
Generate acronyms for preexisting conditions

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#619]
So that the suggest box can suggest using those acronyms.

**Comment by sratcliffe118** [comment]
@attwad do we need someone from BCH or a set of curators to take a pass through these to confirm they make sense?

**Comment by attwad** [comment]
The file is here:
https://github.com/globaldothealth/list/blob/main/suggest/preexisting_conditions.txt

We have about 9K suggestions in this dialog, a good thing would be for someone knowledgeable to have a pass at it first and remove some of the cruft.

Then we have two choices, do we always want to see the acronyms in the form and the details pages? if so we have to generate them and store them in the same file. Otherwise we can generate the acronyms only for the suggest input. Either way I think we should try to just auto-generate them and we can manually apply fixes for those who ended up wrong based on feedback from curators.

My personal take: generate all acronyms automatically and show them everywhere next ot the name, example: "Brucella abortus brucellosis" -> "Brucella abortus brucellosis (BAB)".

sg?

**Comment by sratcliffe118** [comment]
SG, @lagood1 would you be able to take a pass through?

"Brucella abortus brucellosis" -> "Brucella abortus brucellosis (BAB)".
I agree with this  @attwad to confirm, if a curator was to search BAB, this option would come up? If so then I think this gives us what we need

**Comment by attwad** [comment]
> SG, @lagood1 would you be able to take a pass through?
> 
> "Brucella abortus brucellosis" -> "Brucella abortus brucellosis (BAB)".
> I agree with this @attwad to confirm, if a curator was to search BAB, this option would come up? If so then I think this gives us what we need

Yes it would suggest it.

**Comment by sratcliffe118** [comment]
Great, that approach LGTM

**Comment by attwad** [comment]
I've added a script and generated the list of basic acronyms for preexisting conditions, whoever does a pass can give some feedback, I can amend accordingly.

**Comment by lagood1** [comment]
Yes, I will take a look and get the edited file back to you
