### ISSUE TITLE
Manual data entry: Source Entry ID

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#629]
This should be auto populated by the system as per the standard line list schema (https://docs.google.com/spreadsheets/d/1qOnGJQg1gtbmNxAW8c9hC1TvFpIQmSnORD-x-iXrpJ0/edit#gid=0)

Currently this is appearing as a free text field
![Screen Shot 2020-07-27 at 11 09 44 AM](https://user-images.githubusercontent.com/63205311/88530864-eab8b000-cff9-11ea-88d8-1f408a187aea.png)

**Comment by allysonjp715** [comment]
This is the source *entry* id, as opposed to the source id which is system generated. Details here: https://github.com/globaldothealth/list/issues/454

The Source entry ID is the ID that the source gave the case, and needs to be added to our DB as well. We need to add this to the standard line list schema. Open to other names if this name is confusing!

**Comment by sratcliffe118** [comment]
Ah okay, got it now.

I think the naming is slightly confusing here as this is linked to the source information being added

I would propose the following:

1. Rename the field: Unique case ID from source
2. Provide copy in the form of a tooltip to explain the field. 
Unique case ID: Enter the unique ID for the case if provided by the data source e.g. If the source provides the unique case ID of 1837 then enter 1837 in the field. If no unique case ID is provided leave blank.

**Comment by allysonjp715** [comment]
SG. Is it okay if that copy is added to the tooltip next to Source at the top of the section? @shroothless said the tooltips should be per-section rather than per-field.

**Comment by sratcliffe118** [comment]
If we are going to do this (tooltip next to Source at the top of the
section) then i think we need to provide some more copy around the header
to explain the field and what is required as it might not be clear to the
curator without some context.


We can look at moving it to another section, but I don't see a good spot
that would fit.



@Shruti Chandra <shroo@google.com> WDYT?

**Comment by abhidg** [comment]
We are phasing out source entry IDs for better privacy, closing.
