### ISSUE TITLE
Manual data entry: Data source entry

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#632]
Bug: Modify data source field to allow curators to copy paste the source, and if source already exists, not having to select it from the drop down.

@allysonjp715 can we support this functionality with the current form? Essentially an auto complete without a picker if the exact source already exists?

If this is more than a small tweak, @shroothless can we tweak the UX to make clearer to the curator that they need to select the source to continue

**Comment by allysonjp715** [comment]
Dup of #630 ?

We can certainly remove the need to click the option when it's a new source. For an existing source I'll need to think it through more...

**Comment by allysonjp715** [comment]
This also would be a lot easier if we didn't have source names. I know that's been a contentious issue and we we're hoping for some UXR. @acansler do you have any data there? Or could we prioritize it?
