### ISSUE TITLE
Manual entry: Date picker allowed future dates and limited dates in past

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#636]
Bug: Date picker allows forward dates to 2100, but only back to 2019 (-1 year). 

Change: Allow the picker to go back a maximum of 3 years and no forward data allowed as a valid input option

**Comment by allysonjp715** [comment]
Which picker allowed future dates? I'm seeing disabled future dates and an error message:
![Screen Shot 2020-07-27 at 3 57 20 PM](https://user-images.githubusercontent.com/30459667/88557271-ea340f80-d021-11ea-9572-db3ed5b9a418.png)
![Screen Shot 2020-07-27 at 3 57 09 PM](https://user-images.githubusercontent.com/30459667/88557275-ebfdd300-d021-11ea-808f-7dfaf7ba2396.png)

I chose the minimum date to be the first date we had recorded in the data so far, but can extend that.

**Comment by sratcliffe118** [comment]
Ah I just saw the picker allowed you to select one, if there is validation
that prevents entry that is fine.
As a matter of interest did we set the limit to how far back you can go?

**Comment by allysonjp715** [comment]
The date pickers I'm seeing don't let you select one. They are disabled buttons. Have you seen a date picker where you can select a date in the future? 

Yes I chose the minimum date to be the first date we had recorded in the data so far, but can extend that if we want

**Comment by sratcliffe118** [comment]
I couldn't select, just found it strange was even an option.

Yes I chose the minimum date to be the first date we had recorded in the data so far, - **This is fine**

Closing bug as think has what we need
