### ISSUE TITLE
Manual Entry: Place of transmission, free text and common selection for quick entry

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#638]
**Feature request**

1. Allow for a fee text option if the place of transmission for the case is not in the autocomplete list
2. Provide the most common place of transmission options in the database for quick entry (as is done for symptoms below)
![Screen Shot 2020-07-27 at 11 41 02 AM](https://user-images.githubusercontent.com/63205311/88536630-150f6b00-d004-11ea-86bc-5451973c9965.png)

**Comment by allysonjp715** [comment]
1 is now implemented. I wonder if we want 2. Places of transmission is fairly straightforward and only has 30 options to choose from, compared to thousands of available options for symptoms.

**Comment by sratcliffe118** [comment]
@allysonjp715 
As per slack conversation lets go for 5 options for places of transmission
