### ISSUE TITLE
Bulk CSV: Additional field columns to include in Bulk upload template

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#646]
**Feature Request**
Add the **bolded** data fields to the Bulk upload template

1. sourceEntryId
2. country
3. admin1
4. admin2
5. admin3
6. gender
7. ageRangeStart
8. ageRangeEnd
9. **Race / ethnicity**
10. **Nationality**
11. **Occupation**
12. dateConfirmed
13. **Method of confirmation**
14. **Symptom onset date: (Note when there is data entered into this field we should also set the field Symptom status = Symptomatic )**
15. **Symptoms**
16. hospitalized 
17. dateHospitalized
18. **ICU admission: yes / no**
19. **ICU admission date**
20. **Pre existing conditions: yes/ no**
21. outcome 
22. dateOutcome
23. caseCount

**Comment by axmb** [comment]
@allysonjp715 made a fair point here, which is can we reliably say that `symptom status` should be set to `Symptomatic`, as opposed to `Presymptomatic`?

It seems that `Symptomatic` will be appreciably more popular (I'm not sure I've seen any sources with the latter), but the field could technically contain either given the presence of symptoms.

**Comment by sratcliffe118** [comment]
This is a slightly nuanced case. If the curator enters a symptom onset data then the case must have had symptoms, otherwise no data could be added. So in this case I am fine to set to Symptomatic. 

A pre symptomatic case will not show an onset of symptom date until a time symptoms are evident so there is not a way for bad data to enter the system, without a curator error which this would not solve for.

With this @axmb approach SGTM

**Comment by allysonjp715** [comment]
> A pre symptomatic case will not show an onset of symptom date until a time symptoms are evident so there is not a way for bad data to enter the system, without a curator error which this would not solve for.

Sorry, I'm not quite understanding this. It's true that a case can have a list of symptoms and also be "Presymptomatic" right? If so, I don't think we should populate "Symptomatic" when given a list of symptoms. 

In general, I think it's not a good idea to populate any data the curator didn't enter themselves. We don't want them to be surprised by changes the system makes. It may be a slightly higher learning curve when they first enter data, but once learned it will be easier the next time around.

**Comment by sratcliffe118** [comment]
A case which is Presymptomatic
<https://medicalxpress.com/news/2020-06-difference-asymptomatic-presymptomatic-coronavirus.html#:~:text=WHO%20defines%20asymptomatic%20spread%20as,will%20eventually%20get%20symptoms%20later.>
cannot have symptoms at the time they are recorded as this state in the DB.
They do however develop symptoms at a later date, and thus are not consider
asymptomatic. When they develop symptoms the case will be updated to
symptomatic and the date of symptom onset if provided will be populated.

I agree in general we do not want to populate any data the curator does not
enter, but in this case if you have a symptom onset date by definition you
must be symptomatic

**Comment by allysonjp715** [comment]
I see, I didn't fully understand pre-symptomatic, thanks for the link. With this definition, would we *ever* populate pre-sympotmatic in our linelist? If they are a confirmed case with no symptoms at the time, we would choose asymptomatic. Then when they develop symptoms we would label them as symptomatic.

It seems pre-symptomatic can only be used when discussing spread from one person to the next, but can't be used to define a single case. Am I understanding that correctly? WDYT?

**Comment by sratcliffe118** [comment]
With this definition, would we ever populate pre-sympotmatic in our linelist? If they are a confirmed case with no symptoms at the time, we would choose asymptomatic. Then when they develop symptoms we would label them as symptomatic.
- Yes conceptually we would if the case was reported a positive test with no symptoms it's likely to be pre symptomatic and then over time if they show symptoms changed to symptomatic / if no symptoms then asymptomatic
- In reality i expect the majority of cases entered will have symptoms, but we need to keep the differentiation between asymptomatic and pre-sym as its a key value to the data and CUJs for researchers

**Comment by allysonjp715** [comment]
Could you describe the situation when we would select pre-sym?

**Comment by sratcliffe118** [comment]
Sure,
There is a positive PCR test for a case but there are no reported symptoms. As the test has only just taken place it's too early to confirm if the case is asymptomatic so the status would be set to pre-sym. Then after checking in 10-14 days later the case could be confirmed as either asymp or symptomatic. Essentially its a status for a case with no symptoms where it's too early to define them as asym.

I expect this will be more of an edge case but from speaking to the research team this is an important use case and the data is valuable.

**Comment by allysonjp715** [comment]
Interesting, okay. So they would select pre-sym when there are no symptoms - we have that wrong currently in the single case form, will fix that.

**Comment by sratcliffe118** [comment]
Pre-sym when there are no symptoms -> Yes this would be the case if there had not been the adequate time for symptoms to appear. It's a slight nuance but an important one

**Comment by allysonjp715** [comment]
AB, is there anything left to do as per the original bug after that fix?

**Comment by axmb** [comment]
Making sure I'm clear -- what's the verdict on the originally suggested inference of Symptomatic/PreexistingConditions?

**Comment by axmb** [comment]
All set with the current behavior.
