### ISSUE TITLE
Bulk CSV upload: Larger-than-memory (>50MB) files support (USA, Mexico)

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#647]
There are data sources that have larger than memory files e.g. USA, Mexico.
These files are updated with the latest status of the cases so there is a requirement to be able to support these size files on an ongoing basis.

USA: 180MB (and growing)
Mexico: 130MB (and growing)
It's expected more countries will be at the level soon

**Comment by axmb** [comment]
We've decided that these types of files won't be officially supported via bulk upload (instead capping the recommended file size at ~10k rows of data). This is a nice to have, in case an adventurous curator tries such an upload, but I'll deprioritize for now.

**Comment by axmb** [comment]
Unassigning myself, but this is still a nice-to-have we could consider in the future.

For these types of files, it'd be reasonable to chunk/batch the upload into multiple requests, like we're doing for ADI.

**Comment by sratcliffe118** [comment]
Ack and agree

**Comment by abhidg** [comment]
Large files are being ingested by ADI, reopen if there’s a request to manually upload large files
