### ISSUE TITLE
Bulk CSV Upload: New upload and error handling / correction process

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#649]
**Feature request**
Proposal for new error handling process a and bulk csv uploads CUJ  following the curator testing.

**Current process**
- Curator manipulates the data from the raw data source to the template CV format, both in terms of column order, but also content
- Curator uploads the file and submits
- File is processed and if all files pass then the data is uploaded to G.h list
- If any of the rows fail the whole file files and the curator receives an error message for each row that fails with error details
- The curator is required to amend each row with an error and then resubmit
- Process continues until each row is correctly formatted and then can be successfully uploaded to G.h List
- No cases are uploaded until they are all in the correct format. 
- Some files can be large in nature, this can cause long delays and a number of upload cycles to get all the data in the correct format and uploaded into the system. 
- Not efficient and found to be confusing and frustrating for curators.

**Proposed new process**
- Curator manipulates the data from the raw data source to the template CV format, both in terms of column order, but also content
- Curator uploads the file and submits
- All rows that pass the validation are uploaded to G.h List immediately. Curator is informed of the number of rows that were successfully added and number that failed.
- The rows that fail validations and upload are returned in the a CSV file with a new column citing the error / failure reason for that row
- The curator can download the CSV and then make the amends to each row based on the error message
- Once complete the file can then be re uploaded using the same process
- The same process occurs, number that are uploaded are indicated and if there are failures these are also flagged, a CSV to download with error messaging is provided. 
- The process / cycle continues until all the rows (cases) are successfully uploaded to G.h List

**Rationale for change**
1. Rows that pass validation are added to G.h list automatically
2. Curators receive back a file with each failed row and reason in a clear, easy and digestible format 
3. Correcting and resubmitting is a clearer process, curator reads the error and correct the field(s) that are failing
4. Addresses direct feedback from curator testing, where error messages were +ve received, but navigating fixes was hard and time consuming.
5. Rows that pass validation are automatically added to G.h List, there is not All or None trade off. Leaves curators to focus on the failing rows and makes it as easy as possible to identify and fix the failures

**Comment by axmb** [comment]
Interesting trade-off, here.

- For the modest files we used in UXR testing, all-or-nothing was the expected, and IMO correct, behavior.
- For very large files (say, 10,000+ rows), I can imagine this partial behavior is better. Uploading this many rows takes time. It'd be unfortunate to validate 100,000 rows, and for a failure in the final row to require resubmitting the entire file.

It's a tough call, since I think the partial behavior is preferable, and the partial behavior sort of necessitates having the new CSV downloaded to easily indicate what rows remain. The downshot there is that involving more files in the process adds complexity.

I think it'd be best to settle on a single behavior for the gamut. Should get Aaron/Shru's thoughts on this.

**Comment by scarpino** [comment]
Two thoughts.  1.) Often, if a few rows fail that's indicative of a bigger issue with the data set.  So, we might want to proceed with caution here.  But, 2.) What if we shard the csv into chunks in the browser and then spin off a separate worker to handle each chunk?  Then if a worker fails we would only have to handle re-uploading that chunk.  Maybe failure triggers a workflow to prompt and then save the chunk as a CSV so the user can ideally address the issue and re-upload the smaller file.

**Comment by sratcliffe118** [comment]
Thanks Alex / Sam,

The main thrust of my proposal was to make the workflow easier for curators
especially with large CSV, so that if there are errors  they can be
identified easily and there is no painful reupload process
I certainly do not propose adding complexity or jeopardizing data
integrity, so very much open to these ideas.

If we state our main goals are:
1. Data integrity: We do not want to increase the ease of upload if it adds
great risk to 'bad' data getting into the system
2. Simple and easy process to identify and fix data errors

I like the idea of sharding the CSV into chunks so if you have a 100k row
file and the final row fails then that only impacts the last shard say 10k,
meaning 90% of cases make it into the database for review and then the
curator can download and correct the final shard before reuploading.

Thoughts? Are there other potential solutions here?

**Comment by sratcliffe118** [comment]
Update following offline discussion with @axmb 

- Goal of phase 1 is to get as many sources on auto ingestion as possible. 
- Bulk CSV works to a level to support small / medium size files which such meet requirements
- Supporting large files through bulk CSV is out of scope for the project. Large files will need to be processed via auto ingestion
- New proposal for error handling for small / medium size files, see below
