### ISSUE TITLE
Addition of an upload ID for each Bulk CSV and Automated ingestion upload

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#713]
**Feature request**
1. Addition of an upload ID for each Bulk CSV and Automated ingestion upload
2. Upload ID should be searchable in the line list screen, so cases can be filtered to specific uploads

**Rationale**
- Curator needs to filter and do some spot checks of the data quality for a specific upload
- Curator finds a large scale issue with an upload (column completely missing for 5,000 rows / parser converted data incorrectly) and needs to delete them from the dataset before fixing and reuploading.

**Comment by axmb** [comment]
I can take care of populating the upload ID, after which we'll then need to add the search criteria.
