### ISSUE TITLE
Symptom option: Mild to Moderate

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#737]
Not sure what this option means : /
Also how are we deciding the options to show here currently, it should be most popular ?

@allysonjp715 is this in the taxonomy? We should remove

![Screen Shot 2020-08-06 at 3 34 27 PM](https://user-images.githubusercontent.com/63205311/89544754-68e73480-d7fa-11ea-9b74-7e4b08c2c7c8.png)

**Comment by allysonjp715** [comment]
"Mild to moderate" isn't in the dropdown list, so it must come from the sheets. Any ideas, @khmoran ? Perhaps many people entered "cough, mild to moderate" and it got separated into its own symptom? Do we usually capitalize the first letter?

**Comment by khmoran** [comment]
Quite possible. I'm not sure how much effort we want to put into diagnosing/fixing issues with the imported data given that we're going to drop it before launch. WDYT @sratcliffe118?

**Comment by khmoran** [comment]
(hit the wrong button, sorry)

**Comment by sratcliffe118** [comment]
If it's in the sheets data then we can ignore, not required for MVP
