### ISSUE TITLE
Create data dictionary and provide it on github alongside data exports

### ISSUE THREAD

**Issue by khmoran** [globaldothealth/list#780]
We should provide a data dictionary to accompany the CSV and JSON exports of the case data so users know (1) what it contains and (2) how to interpret it.

**Comment by sratcliffe118** [comment]
@outbreakprepared 
I think it would be good practice to have someone who is going to be on the project long time compile this. Happy to consult and partner but needs to be well understood post fellowship.

Moritz - please let me know who can lead this and I will work with them.

**Comment by dakrownie** [comment]
@outbreakprepared 
Bumping this up in your inbox.
Who do you suggest per Stephen's comment above?
