### ISSUE TITLE
Figure out how to handle sources with unstable but predictable URLs

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#831]
**Is your feature request related to a problem? Please describe.**
Japan issue https://github.com/globaldothealth/list/issues/481 points to a source URL of https://github.com/reustle/covid19japan-data/tree/master/docs/patient_data, there the latest.json file points to the name of the file that has the latest data in it:
https://github.com/reustle/covid19japan-data/blob/master/docs/patient_data/latest.json
contains
`2020-08-20.json` at the time of writing.

**Describe the solution you'd like**
Figure out a parsing lambda schedule/strategy to handle that case.

**Comment by axmb** [comment]
It's a pattern we've seen in other sources, too. One variation is India's data, which isn't daily, but has a file number that increments once the current file becomes sufficiently large (i.e., it's currently on https://api.covid19india.org/raw_data13.json).
