### ISSUE TITLE
Downloadable URL for Paraiba Brazil parsing source

### ISSUE THREAD

**Issue by AnyaLindstromBattle** [globaldothealth/list#880]
**Describe the bug**
500 Server Error if run retrieval function when using https://superset.plataformatarget.com.br/superset/explore_json/?form_data=%7B%22slice_id%22%3A1549%7D&csv=true as source URL

**To Reproduce**
1. Create new source using https://superset.plataformatarget.com.br/superset/explore_json/?form_data=%7B%22slice_id%22%3A1549%7D&csv=true
2. create valid_scheduled_event.json with sourceID
3. run sam build
4. run retrieval function
5. see error

**Comment by attwad** [comment]
Thanks for reporting, will tackle this now.

**Comment by attwad** [comment]
OK so, the URL is stored correctly in mongo (that is it's not double encoded there: 

```
> db.sources.find()
{ "_id" : ObjectId("5f4626eee8aeac002eb7dab4"), "name" : "badurl", "origin" : { "_id" : ObjectId("5f48b835f970420028466ef3"), "url" : "https://superset.plataformatarget.com.br/superset/explore_json/?form_data=%7B%22slice_id%22%3A1549%7D&csv=true" }, "format" : "JSON", "uploads" : [ { "_id" : ObjectId("5f462789e8aeac002eb7dab9"), "status" : "IN_PROGRESS", "summary" : {  }, "created" : ISODate("2020-08-26T09:12:41.846Z") }, { "_id" : ObjectId("5f462826e8aeac002eb7dabc"), "status" : "ERROR", "summary" : { "error" : "INTERNAL_ERROR" }, "created" : ISODate("2020-08-26T09:15:18.664Z") } ], "__v" : 2, "dateFilter" : { "_id" : ObjectId("5f48b835f970420028466ef4") } }
```

So the issue is in the retrieval function.

**Comment by attwad** [comment]
Note that the decoded URI is:

`https://superset.plataformatarget.com.br/superset/explore_json/?form_data={"slice_id"%3A1549}&csv=true`

What is happening is that I recently added date formatting to the URL, but it's mangling URLs that have % operators without date meaning like this URL.

I guess Ill have to go with the other approach I was thinking when I added date-based changing URLs, will do that now.
