### ISSUE TITLE
No ability to download selected line list data

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#909]
No ability to download selected line list data from the line list tab

@shroothless do you have the UX design for the download functionality?

**Comment by shroothless** [comment]
![image](https://user-images.githubusercontent.com/67452108/91873714-5ddfc280-ec47-11ea-98b3-71b4c4df4bbd.png)
 Is this what you are referring to?

**Comment by sratcliffe118** [comment]
Yes that is correct. My current UI doesn't shows this in PROD or DEV
![Screen Shot 2020-09-01 at 5 06 44 PM](https://user-images.githubusercontent.com/63205311/91877211-a01ff880-ec75-11ea-9690-79945a7e92ec.png)

**Comment by shroothless** [comment]
UX was delivered recently so likely in progress.

**Comment by sratcliffe118** [comment]
@allysonjp715 is the download functionality still in development?
