### ISSUE TITLE
No data showing in prod version: Internal Error message

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#917]
All data dashboards showing an internal error message when logging in

InternalErrorWe encountered an internal error. Please try again.062B7F83ACC0A74Brn75Aum3riP9FQUnYGNe27bcubgJ+w1Jx8vJgowfo2O/+C1EYY1SSA+tMuVB8z3P8vGcmtuJviU=
![Screen Shot 2020-09-02 at 11 50 43 AM](https://user-images.githubusercontent.com/63205311/91972451-a912d780-ed12-11ea-91cf-1225276e8700.png)

**Comment by allysonjp715** [comment]
No longer reproducible. "Internal error" means it was a mongo error that we probably didn't have control over anyways. Please do reopen if you see errors again.
