### ISSUE TITLE
Line list search is case sensitive 

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#925]
Line list search is case sensitive 
e.g Search for gender: male -> returns no results
e.g Search for gender: Male -> returns results

Expected behavior: search functionality should return the same results for male and Male. Search should not be case senstive

**Comment by attwad** [comment]
FYI albeit feasible, case insensitivity is incredibly awkward in mongo.

https://docs.mongodb.com/manual/core/index-case-insensitive/#create-a-case-insensitive-index

**Comment by sratcliffe118** [comment]
Ack, can we add some copy next to search title to note that search functionality is case sensitive

**Comment by sratcliffe118** [comment]
Note if i search france I get results so it doesn't appear to apply to all fields?

**Comment by attwad** [comment]
I will look at making those case insensitive first, if not well supportable by mongo I'll look into helper text.

**Comment by attwad** [comment]
This is fixed in dev, will bump prod and push the new schema indexes there too later today.

**Comment by attwad** [comment]
okay search for country:china returns the same resutls as country:China now in prod.
