### ISSUE TITLE
Line List tab: Provide content to help explain and guide users

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#928]
@shroothless 
Thinking more about this, users of the data will be accessing and using this view to search / query and then download the datasets. WDYT on some user content from the marketing folks to help explain and guide users on the page. Currently it feels sparse and fine for users with context and experience with the dataset, but for new users I think we need to provide some more information to guide and help support them.

![Screen Shot 2020-09-03 at 12 34 11 PM](https://user-images.githubusercontent.com/63205311/92109944-ca8ec480-ede1-11ea-9f41-ff733d255ad8.png)

**Comment by abhidg** [comment]
There's now a filter guide, and the new filter UI which should improve the experience.
