### ISSUE TITLE
Reader Access view showing source and upload tabs 

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#930]
- If a profile is reader access they should only be able to access the tabs: Home / Line list / Profile

- Currently they can also see sources and uploads tabs which is not correct.

- Can we remove access to these two tabs for reader profiles

**Comment by attwad** [comment]
Yes we thought read only access to the sources and upload wouldn't hurt. I don't feel strongly so if you want to remove access altogether happy to do it.

**Comment by sratcliffe118** [comment]
Yes please remove
