### ISSUE TITLE
Tool tips: Formmating to include spacing and titles

### ISSUE THREAD

**Issue by sratcliffe118** [globaldothealth/list#932]
Adding spacing and titles to tool tips

Copy and format: https://docs.google.com/document/d/1q2wpSXUmCqgDNWDw0TJ0hClzOJaLXkP7RKndgqqEgBs/edit#

![Screen Shot 2020-09-03 at 4 19 40 PM](https://user-images.githubusercontent.com/63205311/92134911-03d72c80-ee02-11ea-8c33-1df07fd2a2dd.png)

**Comment by attwad** [comment]
@sratcliffe118 that docs in your comment points to the bugbash doc, is that intended? I'm sorry I don't really get what's expected of this issue, can you clarify please? thank you

**Comment by allysonjp715** [comment]
I'm guessing this is the doc he meant to link: https://docs.google.com/spreadsheets/d/1mPYrNaO799ZDSTEgCn2WSHEGlwYYxuG2MG9t5TGpN0E/edit#gid=316665458
