### ISSUE TITLE
Auto-populate searchable categories in fields in the line list

### ISSUE THREAD

**Issue by scarpino** [globaldothealth/list#936]
**Is your feature request related to a problem? Please describe.**
When I search for a particular field, e.g., curator, I have to know ahead of time what the possible options are. 

**Describe the solution you'd like**
The categories associated with records within a particular field auto-populate in the search, e.g., country: Canada, China, etc.

**Describe alternatives you've considered**
It's possible to guess and also to inspect records and see what categories are recorded. 

**Additional context**
<img width="1085" alt="Screen Shot 2020-09-03 at 11 42 46 AM" src="https://user-images.githubusercontent.com/1714728/92136925-98c62f80-edda-11ea-8749-0cee38e41ae0.png">

**Comment by abhidg** [comment]
@maciekz1996 How feasible is this? Not a problem for countries but I guess would need a background process for auto filling the other fields. Not sure whether this makes sense for fields like occupation

**Comment by joe-brilliant** [comment]
This may be resolved partially with #2083 CC: @maciekz1996
