### ISSUE TITLE
Search bar UX tweaks

### ISSUE THREAD

**Issue by shroothless** [globaldothealth/list#938]
**Describe the bug**
Move the Search bar to the top and add filter drop down

**To Reproduce**
1. Click on search field
2. Filters appear below

**Expected behavior**
1. Click on search field
2. Type search. string
3. Or click on filter icon/label
4. Show dropdown of available filters

**Screenshots**
![image](https://user-images.githubusercontent.com/67452108/92137772-931d1980-eddb-11ea-978a-2d092e73af2c.png)

Following this model
https://screenshot.googleplex.com/3fPaywGeiSGmUTz

**Comment by allysonjp715** [comment]
Will track moving the search bar to the top of the screen in #948
