### ISSUE TITLE
Clicking on "verify" or "unverify" selected row doesn't change the status of that row sometimes triggers at 500 error

### ISSUE THREAD

**Issue by scarpino** [globaldothealth/list#939]
**Describe the bug**
When I select a row (or rows) in the line list and then click either "verify" or "unverify" nothing seems to happen and sometimes I get a 500 error. 

**To Reproduce**
1. Go to https://dev-curator.ghdsi.org/cases
2. Click on a row
3. Scroll up and find the "v" and "p" icons for verifying or unverifying a row at the top
4. See the row not change status.

**Expected behavior**
Either the row should change status or a message should inform me that it may take a few minutes for the status to updat

**Screenshots**
<img width="1019" alt="Screen Shot 2020-09-03 at 11 50 47 AM" src="https://user-images.githubusercontent.com/1714728/92137883-b8aa2300-eddb-11ea-957e-3805c79becef.png">

**Environment (please complete the following information):**
 - OS: mac  10.15.6
 - Browser Chrome
 - Version 85.0.4183.83 

**Additional context**
Often I will end up with a 500 error, which persists even if I try to click through and edit the record.

**Comment by allysonjp715** [comment]
We should add a loading indicator after clicking those buttons. I'm guessing something like https://github.com/globaldothealth/list/issues/940#issuecomment-686605625 happened to cause the 500 error. If we add a loading indicator showing the progress of the update, that will prevent users from selecting the action again before the first action has completed.

**Comment by allysonjp715** [comment]
Hopefully the cases can no longer get in the faulty state. Please re-open if you see the errors again.
