### ISSUE TITLE
Viewing Uploads Tab in Reader Mode

### ISSUE THREAD

**Issue by dakrownie** [globaldothealth/list#941]
**Describe the bug**
Uploads tab available in reader mode

**To Reproduce**
- In reader mode 
- Navigate to the uploads tab
- Click and see error below

**Expected behavior**
A reader should not see the upload tab button 

**Screenshots**

![reader view](https://user-images.githubusercontent.com/33044735/92139542-2b34f600-ee10-11ea-811c-4e2cc0d15bf4.png)

**Environment (please complete the following information):**

**Comment by attwad** [comment]
This was fixed in another PR.
