### ISSUE TITLE
Move profile from main menu to top right 

### ISSUE THREAD

**Issue by shroothless** [globaldothealth/list#949]
**Describe the bug**
Profile item should be in the top right using the avatar from Google login

**Screenshots**
Details here in this screen shot
https://screenshot.googleplex.com/792ktJR6xsLuKG4

**Comment by attwad** [comment]
Happy to look into this. A few questions though:

Should the avatar be an image button then? or a menu with items to go to the profile page and to logout?
Do we need a default picture when no avatar is set on a person's profile?
Do we need to keep th epicture in sync somehow when they change it in Google?

**Comment by shroothless** [comment]
Do we get integration for free using the google sign on? The avatar is less important than the placement. Let me turn it into a generic account icon and simplify.

**Comment by shroothless** [comment]
![image](https://user-images.githubusercontent.com/67452108/92489708-149af000-f1be-11ea-86a8-d3bada4481cc.png)

**Comment by attwad** [comment]
@shroothless Yes we do get the profile url, I actually played a bit with it today and it's fairly easy to keep up to date as well so I think we can go with the actual picture of the user.

The question of what happens when that icon is clicked remains though, is this a menu with two items (profile, logout)?

**Comment by shroothless** [comment]
Yes, there should be a menu.  Profile, About Global.health, Report an
issue, Logout.
And then we will eliminate the three-dot menu.

**Comment by attwad** [comment]
@shroothless What about the logged-out state then? where should the login action be?

**Comment by shroothless** [comment]
In the logged out state we could add it to that menu and.  introduce a
login button to the right of the account icon - just trying to keep it
super simple.
