### ISSUE TITLE
Add UI-configurable email alerts for automation

### ISSUE THREAD

**Issue by axmb** [globaldothealth/list#978]
**Describe the solution you'd like**

- Curators can specify email recipients for a given automated source.
- Email notifications are sent for source creation.
- Email notifications are sent for failed ingestion of the source.

**Describe alternatives you've considered**
We use CloudWatch alarms now, but it won't really suite the curation team. When a Lambda fails, an alarm can be sent along an SNS topic, but since we want different UI-configurable recipients for every source, we'd have a mess of SNS topics/alarms to deal with.

**Comment by axmb** [comment]
@shroothless / @acansler -- any thoughts on email content for source creation or failed ingestion runs?

I'm just using a basic message now, but if you're keen to put together a couple HTML templates, I can switch to those. Not a big deal, IMO, but a nice to have.

**Comment by shroothless** [comment]
What would a template look like? Can you send me a sample please..

**Comment by axmb** [comment]
Yep! Sent over an email.
