### ISSUE TITLE
Search Guide button and text placement

### ISSUE THREAD

**Issue by z023** [globaldothealth/list#992]
**Describe the bug**
When searching in the line list for admin1:Zurich the correct cases are listed but when searching for admin1:Hong or admin1:Hong Kong no cases are listed. All Hong Kong cases are listed when searching country:China

**Comment by attwad** [comment]
Search with keywords like "admin1" supports exact matches only (it only ignores case), I suggest simply using the full text search functionality in this case: just searching for "Hong Kong" (with parentheses or not, doesn't matter in this particular case) works as intended.

Happy to document that better somewhere if needed!

**Comment by z023** [comment]
Thanks, yes it works when searching "Hong Kong" so might need that added somewhere.

**Comment by attwad** [comment]
Okay we need to find a better place for the search documentation then, right now it's just the helper tooltip at the right of the search bar, I am not sure where/how this should be made more visible, calling out our UX friends here for help :)

![image](https://user-images.githubusercontent.com/1255432/93180534-9ac3b300-f737-11ea-9e2c-78dd46a79bad.png)

**Comment by shroothless** [comment]
Got it let me find a spot.

**Comment by sratcliffe118** [comment]
@shroothless ping

**Comment by shroothless** [comment]
Have asked Avani to take a stab at this will have a mock today.

**Comment by WeronikaMichaluk** [comment]
**Acceptance criteria:**

Next to the “?” icon will insert text: “Search Guide”

Search Icon and text “Search Guide” to be placed between the filter button and search input.

Look of the tooltip as described in GH-2.
