### ISSUE TITLE
More useful format of console.log lines

### ISSUE THREAD

**Issue by attwad** [globaldothealth/list#995]
**Is your feature request related to a problem? Please describe.**
When looking at logs in kubernetes, we don't have the context in which they're appearing (time, file, line number).

**Describe the solution you'd like**
standard apache log format or anything really that would make it more useful to debug issues.

Not sure what's the nodejs standard here, perhaps @axmb has an idea?

**Comment by axmb** [comment]
Winston and Pino are the most popular logg[ers|ing frameworks], AFAICT. Winston seems a bit much for the size of our app; I'll give Pino a swing and see how it plays locally and with our k8s setup. Looks pretty solid.
